# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/chaos-mesh.yaml.j2

# Configuration for the official chaos-mesh chart

chaos-mesh:
  fullnameOverride: "fusaka-devnet-ssl-chaos-mesh-6"
  webhook:
    certManager:
      enabled: false
    FailurePolicy: Ignore
    timeoutSeconds: 2
  dashboard:
    create: true
    securityMode: false
    persistentVolume:
      enabled: true
      storageClassName: "do-block-storage"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: chaos-mesh.fusaka-devnet-ssl-chaos-6.yolkie.xyz
      hosts:
        - name: chaos-mesh.fusaka-devnet-ssl-chaos-6.yolkie.xyz
      paths: ["/"]
      ingressClassName: nginx
      
  controllerManager:
    replicaCount: 1
    # Disable mTLS for physical machine connections
    chaosdSecurityMode: False
  
  # Chaos Daemon configuration
  chaosDaemon:
    runtime: containerd
    socketPath: /run/containerd/containerd.sock

# Custom physical machines configuration (not supported by upstream chart)
# These will be created by our custom template
physicalMachines:
  enabled: true
  machines:
    - name: prysm-geth-1
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-1.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: geth
        nodename: prysm-geth-1
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Geth node"
    - name: prysm-geth-2
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-2.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: geth
        nodename: prysm-geth-2
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Geth node"
    - name: prysm-geth-3
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-3.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: geth
        nodename: prysm-geth-3
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Geth node"
    - name: prysm-geth-4
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-4.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: geth
        nodename: prysm-geth-4
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Geth node"
    - name: prysm-geth-5
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-5.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: geth
        nodename: prysm-geth-5
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Geth node"
    - name: prysm-nethermind-1
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: nethermind
        nodename: prysm-nethermind-1
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Nethermind node"
    - name: prysm-nethermind-2
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-2.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: nethermind
        nodename: prysm-nethermind-2
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Nethermind node"
    - name: prysm-nethermind-3
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-3.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: nethermind
        nodename: prysm-nethermind-3
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Nethermind node"
    - name: prysm-nethermind-4
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-4.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: nethermind
        nodename: prysm-nethermind-4
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Nethermind node"
    - name: prysm-nethermind-5
      address: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-5.fusaka-devnet-ssl-chaos-6.yolkie.xyz/chaosd/"
      labels:
        consensus: prysm
        execution: nethermind
        nodename: prysm-nethermind-5
        network: fusaka-devnet-ssl-chaos-6
      annotations:
        description: "Prysm + Nethermind node"
