#  ░██████╗░██╗░░░░░░█████╗░██████╗░░█████╗░██╗░░░░░  ██╗░░░██╗░█████╗░██████╗░░██████╗
#  ██╔════╝░██║░░░░░██╔══██╗██╔══██╗██╔══██╗██║░░░░░  ██║░░░██║██╔══██╗██╔══██╗██╔════╝
#  ██║░░██╗░██║░░░░░██║░░██║██████╦╝███████║██║░░░░░  ╚██╗░██╔╝███████║██████╔╝╚█████╗░
#  ██║░░╚██╗██║░░░░░██║░░██║██╔══██╗██╔══██║██║░░░░░  ░╚████╔╝░██╔══██║██╔══██╗░╚═══██╗
#  ╚██████╔╝███████╗╚█████╔╝██████╦╝██║░░██║███████╗  ░░╚██╔╝░░██║░░██║██║░░██║██████╔╝
#  ░╚═════╝░╚══════╝░╚════╝░╚═════╝░╚═╝░░╚═╝╚══════╝  ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░

domain: yolkie.xyz
network_subdomain: "{{ ethereum_network_name }}.{{ domain }}"
server_fqdn: "{{ inventory_hostname }}.{{ network_subdomain }}"

ethereum_network_id: >-
  {{ (lookup('file', eth_testnet_config_local_dir_src + '/genesis.json') | from_json).config.chainId }}
ethereum_network_deposit_contract: >-
  {{ lookup('file', eth_testnet_config_local_dir_src + '/deposit_contract.txt') }}
ethereum_network_deposit_contract_block: >-
  {{ lookup('file', eth_testnet_config_local_dir_src + '/deposit_contract_block.txt') }}

ethereum_node_rcp_hostname: "rpc.{{ server_fqdn }}"
ethereum_node_beacon_hostname: "bn.{{ server_fqdn }}"

ethstats_url: "ethstats.{{ ethereum_network_name }}.{{ domain }}"
ethstats_secret: "{{ secret_ethstats }}"

### Checkpoint sync specific for Ansible & Kubernetes
checkpoint_sync_node: bootnode-1
ethereum_node_cl_checkpoint_sync_enabled: true
#checkpoint_sync_url: https://checkpoint-sync.{{ ethereum_network_name }}.{{ domain }}
checkpoint_sync_url: https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@bn.{{ checkpoint_sync_node }}.{{ ethereum_network_name }}.{{ domain }}
checkpoint_sync_url_kube: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.{{ checkpoint_sync_node }}.{{ ethereum_network_name }}.{{ domain }}
#  ██████╗░░█████╗░██╗░░░░░███████╗  ██╗░░░██╗░█████╗░██████╗░░██████╗
#  ██╔══██╗██╔══██╗██║░░░░░██╔════╝  ██║░░░██║██╔══██╗██╔══██╗██╔════╝
#  ██████╔╝██║░░██║██║░░░░░█████╗░░  ╚██╗░██╔╝███████║██████╔╝╚█████╗░
#  ██╔══██╗██║░░██║██║░░░░░██╔══╝░░  ░╚████╔╝░██╔══██║██╔══██╗░╚═══██╗
#  ██║░░██║╚█████╔╝███████╗███████╗  ░░╚██╔╝░░██║░░██║██║░░██║██████╔╝
#  ╚═╝░░╚═╝░╚════╝░╚══════╝╚══════╝  ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░

# role: ethpandaops.general.ethereum_genesis
ethereum_genesis_generator_container_image: "{{ default_tooling_images.ethereum_genesis_generator }}"
ethereum_genesis_generator_version: "{{ ethereum_genesis_generator_container_image.split(':')[-1] }}"
ethereum_genesis_network_seed: "{{ ansible_inventory_sources[0] }}"
ethereum_genesis_chain_id: "70{{ 99999999 | random(start=10000000, seed=ethereum_genesis_network_seed) }}"
ethereum_genesis_generator_output_dir: "../network-configs/{{ ethereum_network_name }}"
ethereum_genesis_timestamp: "1749635258"
ethereum_genesis_timedelay: 3000
ethereum_genesis_fork_version_suffix: "{{ 999999 | random(start=100000, seed=ethereum_genesis_network_seed) }}"
ethereum_genesis_timestamp_relative_cmd:
  Linux: "date +%s -d '+45 minutes'"
  Darwin: "date -v +45M +%s"
ethereum_genesis_mnemonic: "{{ secret_genesis_mnemonic }}"
ethereum_genesis_generator_config_files:
  cl/config.yaml: "{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/ethpandaops/ethereum-genesis-generator/v{{ethereum_genesis_generator_version}}/config-example/cl/config.yaml', split_lines=false) }}" # noqa yaml[line-length]
  cl/mnemonics.yaml: "{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/ethpandaops/ethereum-genesis-generator/v{{ethereum_genesis_generator_version}}/config-example/cl/mnemonics.yaml', split_lines=false) }}" # noqa yaml[line-length]
  el/genesis-config.yaml: "{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/ethpandaops/ethereum-genesis-generator/v{{ethereum_genesis_generator_version}}/config-example/el/genesis-config.yaml', split_lines=false) }}" # noqa yaml[line-length]
  values.env: |-
    export CHAIN_ID="{{ ethereum_genesis_chain_id }}"
    export EL_AND_CL_MNEMONIC="{{ ethereum_genesis_mnemonic }}"
    export NUMBER_OF_VALIDATORS=576
    export GENESIS_FORK_VERSION="0x10{{ ethereum_genesis_fork_version_suffix }}"
    export ALTAIR_FORK_VERSION="0x20{{ ethereum_genesis_fork_version_suffix }}"
    export BELLATRIX_FORK_VERSION="0x30{{ ethereum_genesis_fork_version_suffix }}"
    export CAPELLA_FORK_VERSION="0x40{{ ethereum_genesis_fork_version_suffix }}"
    export DENEB_FORK_VERSION="0x50{{ ethereum_genesis_fork_version_suffix }}"
    export ELECTRA_FORK_VERSION="0x60{{ ethereum_genesis_fork_version_suffix }}"
    export FULU_FORK_VERSION="0x70{{ ethereum_genesis_fork_version_suffix }}"
    export FULU_FORK_EPOCH=1
    export MAX_BLOBS_PER_BLOCK_ELECTRA=9
    export MAX_BLOBS_PER_BLOCK_FULU=128
    export MAX_BLOBS_PER_BLOCK=128
    export TARGET_BLOBS_PER_BLOCK_ELECTRA=9
    export TARGET_BLOBS_PER_BLOCK_FULU=128
    export TARGET_BLOBS_PER_BLOCK=128
    export GENESIS_TIMESTAMP={{ ethereum_genesis_timestamp }}
    export GENESIS_DELAY={{ ethereum_genesis_timedelay }}
    export WITHDRAWAL_TYPE=0x01
    export BPO_1_EPOCH=2
    export BPO_1_MAX_BLOBS=128
    export BPO_1_TARGET_BLOBS=128
    export BPO_1_BASE_FEE_UPDATE_FRACTION="5007716"

ethereum_genesis_validator_keys_output_dir: "{{ ansible_inventory_sources[0] | dirname }}/files/validator_keys"
ethereum_genesis_validator_bls_change_execution_address: "{{ ethereum_node_cl_validator_fee_recipient }}"
ethereum_genesis_validator_keyranges: >-
  {%- set ns = namespace() -%}
  {%- set ns.ethereum_genesis_validator_keyranges = {} -%}
  {%- for host in groups['all'] -%}
  {%-   if hostvars[host].validator_start is defined and hostvars[host].validator_end is defined -%}
  {%-      set v = {'start':hostvars[host].validator_start, 'end': hostvars[host].validator_end } -%}
  {%-     set _ = ns.ethereum_genesis_validator_keyranges.update({host: v}) -%}
  {%-   endif -%}
  {%- endfor -%}
  {{ ns.ethereum_genesis_validator_keyranges }}

# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_plain:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDydvn29/4Sf4f7XEFVzMeRmCLFmeiFettCBUFxmBa6o"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYyP/M+BVYZ+JkedNSmWZ4ADSlxbx3KB8CWnsRvMUtp"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFfLBwAbDlFi8edJH0VTpHEXjhaGtY9cLLQQMLWNT2YN"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJOnyPEkI8z9bGijIrGmSGirKjtdfnm/89W8+GgmDQO8"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJFUyoyxjwlUuff4/noZz2fG/QjM22gsmPowogTYilo+"
bootstrap_default_user_authorized_keys_github_all:
  - mininny
  - ImTei
  - parkgunou
  - sm-stack
  - sunnysidedJ
bootstrap_default_user_authorized_keys_github: >
  {{
    (bootstrap_default_user_authorized_keys_github_all | default([])) +
    (bootstrap_default_user_authorized_keys_github_team_el | default([])) +
    (bootstrap_default_user_authorized_keys_github_team_cl | default([]))
  }}

node_exporter_container_image: "{{ default_tooling_images.node_exporter }}"
prometheus_container_image: "{{ default_tooling_images.prometheus }}"
vector_container_image: "{{ default_tooling_images.vector }}"
json_rpc_snooper_container_image: "{{ default_tooling_images.json_rpc_snooper }}"

# role: ethpandaops.general.ethereum_node
ethereum_node_images_always_pull: true
ethereum_node_metrics_exporter_enabled: true
ethereum_node_xatu_sentry_enabled: true
ethereum_node_cl_validator_enabled: "{{ validator_start is defined and validator_end is defined }}"
ethereum_node_cl_validator_fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
ethereum_node_cl_ports_p2p_tcp: 9000
ethereum_node_cl_ports_p2p_udp: 9000
ethereum_node_cl_ports_http_beacon: 5052
ethereum_node_cl_ports_metrics: 5054
ethereum_node_el_ports_p2p_tcp: 30303
ethereum_node_el_ports_p2p_udp: 30303
ethereum_node_el_ports_http_rpc: 8545
ethereum_node_el_ports_ws_rpc: 8546
ethereum_node_el_ports_engine: 8551
ethereum_node_el_ports_metrics: 6060
ethereum_node_skip_cleanup: true

ethereum_node_json_rpc_snooper_engine_enabled: true
ethereum_node_json_rpc_snooper_engine_port: 8561
ethereum_node_json_rpc_snooper_engine_name: "snooper-engine"

# role: ethpandaops.general.xatu_sentry
xatu_sentry_container_image: "{{ default_tooling_images.xatu_sentry }}"
xatu_sentry_config_name: "{{ ethereum_network_name }}-{{ inventory_hostname }}"
xatu_sentry_config_server_address: "{{ secret_xatu_sentry.server_address }}"
xatu_sentry_config_server_auth_user: "{{ secret_xatu_sentry.user }}"
xatu_sentry_config_server_auth_password: "{{ secret_xatu_sentry.password }}"
xatu_sentry_config_network_name_override: "{{ ethereum_network_name }}"
xatu_sentry_config: |
  logging: "info"
  metricsAddr: ":9090"
  name: "{{ xatu_sentry_config_name }}"
  ethereum:
    beaconNodeAddress: {{ xatu_sentry_config_beacon_uri }}
    overrideNetworkName: {{ xatu_sentry_config_network_name_override }}
  proposerDuty: 
    enabled: true
  outputs:
  - name: grpc
    type: xatu
    config:
      address: {{ xatu_sentry_config_server_address }}
      tls: false
      headers:
        authorization: "Basic {{ (xatu_sentry_config_server_auth_user + ":" + xatu_sentry_config_server_auth_password) | b64encode }}"

xatu_cannon_container_image: "{{ default_tooling_images.xatu_cannon }}"
xatu_cannon_config_name: "{{ ethereum_network_name }}-{{ inventory_hostname }}"
xatu_cannon_config_server_address: "{{ secret_xatu_sentry.server_address }}"
xatu_cannon_config_server_tls_enabled: false
xatu_cannon_config_beacon_uri: "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@bn.lighthouse-geth-1.{{ ethereum_network_name }}.{{ domain }}"
xatu_cannon_config_server_auth_user: "{{ secret_xatu_sentry.user }}"
xatu_cannon_config_server_auth_password: "{{ secret_xatu_sentry.password }}"
xatu_cannon_config_coordinator_address: "{{ secret_xatu_sentry.server_address }}"
xatu_cannon_config_coordinator_tls_enabled: false
xatu_cannon_config_coordinator_authorization: "1ff1cb1f94f3a2ff1227c2909fbc4deeefca48bae9e5d7bd4888c900f719351a"
xatu_cannon_config_network_name_override: "{{ ethereum_network_name }}"


# role: ethpandaops.general.ethereum_metrics_exporter
ethereum_metrics_exporter_container_image: "{{ default_tooling_images.ethereum_metrics_exporter }}"

# role: eth_testnet_config
eth_testnet_config_dir: /data/ethereum-network-config/metadata
eth_testnet_config_local_dir_enabled: true
eth_testnet_config_local_dir_src: "{{ ethereum_genesis_generator_output_dir }}/metadata/"

#gen_kubernetes_config_ethereum_node: # noqa var-naming[no-role-prefix]
#  el: geth
#  cl: lighthouse
#  value: "001"

# role: gen_basic_auth_nginx
gen_basic_auth_nginx_name: "{{ secret_nginx_shared_basic_auth.name }}"
gen_basic_auth_nginx_password: "{{ secret_nginx_shared_basic_auth.password }}"
docker_nginx_proxy_container_image: "{{ default_tooling_images.nginx_proxy }}"
docker_nginx_proxy_docker_gen_container_image: "{{ default_tooling_images.nginx_proxy_gen }}"
docker_nginx_proxy_acme_companion_container_image: "{{ default_tooling_images.nginx_proxy_acme }}"

# role: ethpandaops.general.docker_nginx_proxy
docker_nginx_proxy_container_name: nginx-proxy
docker_nginx_proxy_default_email: "certs@{{ domain }}"
docker_nginx_proxy_docker_gen_container_name: nginx-proxy-gen
docker_nginx_proxy_docker_gen_container_env:
  RESOLVERS: "1.1.1.1"
docker_nginx_proxy_acme_companion_container_name: nginx-proxy-acme
docker_nginx_proxy_acme_companion_container_env:
  DEFAULT_EMAIL: "{{ docker_nginx_proxy_default_email }}"
  NGINX_PROXY_CONTAINER: "{{ docker_nginx_proxy_container_name }}"
  NGINX_DOCKER_GEN_CONTAINER: "{{ docker_nginx_proxy_docker_gen_container_name }}"
  ACME_CA_URI: https://acme.zerossl.com/v2/DV90
  ACME_EAB_KID: "{{ secret_zerossl.ACME_EAB_KID }}"
  ACME_EAB_HMAC_KEY: "{{ secret_zerossl.ACME_EAB_HMAC_KEY }}"
docker_nginx_proxy_container_networks: "{{ docker_networks_shared }}"
docker_nginx_proxy_docker_gen_container_networks: "{{ docker_networks_shared }}"
docker_nginx_proxy_acme_companion_container_networks: "{{ docker_networks_shared }}"
docker_nginx_proxy_datadir: /opt/nginx-proxy
docker_nginx_proxy_container_volumes:
  - "{{ docker_nginx_proxy_datadir }}/conf:/etc/nginx/conf.d"
  - "{{ docker_nginx_proxy_datadir }}/vhost:/etc/nginx/vhost.d"
  - "{{ docker_nginx_proxy_datadir }}/certs:/etc/nginx/certs:ro"
  - html:/usr/share/nginx/html
  - "{{ docker_nginx_proxy_datadir }}/htpasswd:/etc/nginx/htpasswd:ro"

# role: ethpandaops.general.prometheus

# role: ethpandaops.general.vector
vector_config: |
  [sources.in]
    type = "docker_logs"
    exclude_containers = [
      "{{ vector_container_name }}",
      "ethereum-metrics-exporter",
      "nginx-proxy",
      "node_exporter",
      "prometheus",
      "snooper-",
    ]

  [sinks.out]
    type = "loki"
    inputs = ["in"]
    out_of_order_action = "accept"
    labels.forwarder = "vector"
    labels.instance = "{{ inventory_hostname }}"
    labels.network = "{{ ethereum_network_name }}"
    labels.testnet = "{{ ethereum_network_name }}"
    labels.ingress_user = "{{ secret_loki.username }}"
    labels.container_name = "{{ '{{ container_name }}' }}"
  {%- if ethereum_node_el is defined +%}
    labels.ethereum_el = "{{ ethereum_node_el }}"
  {%- endif +%}
  {%- if ethereum_node_cl is defined +%}
    labels.ethereum_cl = "{{ ethereum_node_cl }}"
  {%- endif +%}
    encoding.codec = "json"
    endpoint = "{{ secret_loki.endpoint }}"
    auth.strategy = "basic"
    auth.user = "{{ secret_loki.username }}"
    auth.password = "{{ secret_loki.password }}"
