default_ethereum_client_images:
  ### Consensus layer clients
  lighthouse: sigp/lighthouse:v8.0.0-rc.0
  lodestar: chainsafe/lodestar:v1.35.0-rc.0
  nimbus: statusim/nimbus-eth2:multiarch-v25.9.1
  prysm: public.ecr.aws/s5g8t9d9/ethereum-devnets/prysm:partial-columns
  prysm_validator: public.ecr.aws/s5g8t9d9/ethereum-devnets/prysm-validator:partial-columns
  teku: consensys/teku:25.9.3
  grandine: ethpandaops/grandine:develop
### Execution layer clients
  besu: hyperledger/besu:25.9.0
  geth: public.ecr.aws/s5g8t9d9/ethereum-devnets/geth:getBlobsV3
  erigon: erigontech/erigon:v3.2.0-rc1
  nethermind: nethermind/nethermind:1.34.0
  reth: ghcr.io/paradigmxyz/reth:v1.8.2
  nimbusel: ethpandaops/nimbus-eth1:master

# mev boost
  mev_boost: ethpandaops/mev-boost:develop

default_tooling_images:
  mev_boost: ethpandaops/mev-boost:develop
  mev_builder: ethpandaops/reth-rbuilder:develop
  mev_relay: ethpandaops/mev-boost-relay:main
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_cannon: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_mimicry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_cl_mimicry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:latest
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:0.0.6-fulu
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:master-latest
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: ethpandaops/ethereum-genesis-generator:5.0.6
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:0.0.26-debian
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:fusaka-devnet-3
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:master-latest
  erpc: docker.ethquokkaops.io/gh/erpc/erpc:0.0.49
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  cl_bootnode: docker.ethquokkaops.io/dh/protolambda/eth2-bootnode:cleanup
  json_rpc_snooper: docker.ethquokkaops.io/dh/ethpandaops/rpc-snooper:latest
  nginx_proxy: docker.ethquokkaops.io/dh/nginx:alpine
  nginx_proxy_gen: docker.ethquokkaops.io/dh/nginxproxy/docker-gen
  nginx_proxy_acme: docker.ethquokkaops.io/dh/nginxproxy/acme-companion
  vector: docker.ethquokkaops.io/dh/timberio/vector:0.46.1-alpine
  spamoor: docker.ethquokkaops.io/dh/ethpandaops/spamoor:master-latest
  xatu_relay_monitor: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  blobber: docker.ethquokkaops.io/dh/ethpandaops/blobber:pr-43
  syncoor_web: docker.ethquokkaops.io/dh/ethpandaops/syncoor-web:master
  syncoor_server: docker.ethquokkaops.io/dh/ethpandaops/syncoor:master