secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:8whfedx1tvGv0iPWa7IMWcPXGi2MQYGX9bfUrXqwZQ+WbSUk7SA=,iv:kuI1mmXyqMgnoiXDzKo1kkAN3GVepoCEdvsfwMiiODI=,tag:nAYdZW9Emgt/ZBIwxZWYIg==,type:str]
    username: ENC[AES256_GCM,data:a/mPVEHy,iv:nS9GIaN+j3kRi46WZZSbCoGZNe+eF9iclklemQhf05c=,tag:sYIn9I7D2UpXonoaAZDCKw==,type:str]
    password: ENC[AES256_GCM,data:5WYsn2W2GQ3itQqR,iv:S1mJGO/fvyJ8tFAVREwkmPJsehFVhW74KzfL7rPj0VU=,tag:ZqsLRdfizNetOEkiChrcrw==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:yWxdeQ1Gf/0KaGQTsWE4cIDMikFH71HKRA==,iv:JW4xqNy/cOCHUE7UXHLa8iXVW/50n62d/Az9qtzMtkQ=,tag:Uzq+sEY54SPCgK5PmxdQrw==,type:str]
    username: ENC[AES256_GCM,data:ys1wA4eF,iv:dmEYdXuSkLE732ru0ZennUqOuSl0k+dpYVqKgJy2/XQ=,tag:hXzSUEuwR9tN4+4dAJemHA==,type:str]
    password: ENC[AES256_GCM,data:M7q6WiPBMkUAHtqi,iv:p6yJMtTHCSOVuH8y6L8G+8GOJ7JWzmCYl4CyKnX6A8s=,tag:BQMZmeC4cfm+DHESOX2qYg==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:rtDI1EENSPmTDAKrwGPPJpmimOdM5NfzDLB5yvc7GtfZuYlOrOjjMp3ut0rp1TqWGSel+Kb5ARxvHhl5DdNqdQ==,iv:bA2Vcb0oXaeM31H6o3/wIsjmOlM/rVnRuHxFHLcXqxQ=,tag:Uh8++84dkGIrQxH/17Vceg==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:H19oOrXAk7RCaOAyStG4BaA49vKZsg==,iv:BVt+Tk2rW5uJd7TCSAtJ6JUGOV+FWkONqfWHtRTzzRQ=,tag:sEcnobQTcDBl4YPQabljqg==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:s4hS1gZZTYRR4zray8/pLafdiOHzoTpqCnNwx9UsQTS+J+pVdbiUdGwuhf9WJDHGpTzeEKUYOgC1i6VLbyEEPuJmTY/j3TRzzPFFdCVS+NBoBrx37VU=,iv:Xruu/VNrKfBgnBO86ws7gjVqbemXKAKNlpru9wVzyRo=,tag:MmT3dIJRhzNZMTOexN+4Lw==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:vjjCBG+YrmkW,iv:WsVmdCQaWhvJ6umS1jnR1RlwQOYM39GERTpx+FCi1Xs=,tag:KEvOV5xAWbkykp3FXEY7Ew==,type:str]
    password: ENC[AES256_GCM,data:pApMQB5SfmrUE6Ps,iv:WzQZrp2jICMrARusKCMBDs4dbftE/eMZ+vaFLTpTLMs=,tag:lPyRJus3WCeCnPMF+dltAQ==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:8yDNREmXgQPn,iv:uJIMQBC4oa65iikEvRui262w2J3lJ0jvha+E+lVMpHc=,tag:x+PGB1kSjMPgaGGrgA3kJQ==,type:str]
    password: ENC[AES256_GCM,data:9nwMTZF1hgsbHPgk,iv:beJRTU9FirWVTQuITxJAuauhTwOOGOBrkjHYUohVig8=,tag:TI7UypPFHleYAaONFMrHVA==,type:str]
    server_address: ENC[AES256_GCM,data:C3G6JJcFNW1mUEBXXsEP/DPR,iv:ZfqpNb7B1ZjGgRB7rnmT055+W0tJ3my/hf9+kkbiKXQ=,tag:t7Cer97gTo4EPnfA1V20sQ==,type:str]
secret_ethstats: ENC[AES256_GCM,data:ez0rKnfg+kwZlLpQs/ZXdeW1e8D6d7wkZidXnnhxNj00Ps4YtRDnr9mgv9QoyXeBXvqxhBRrvMzVSAyztjKJ0A==,iv:dYHCOLfICJLFu+9oDNFlQ4Hj4ayY7RIwAiIR2SLFYIE=,tag:pUMwQTdXUCiYGKMmrDccxQ==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:2P8q7k22/hjHjXfX1oLfBFJ6n0u1p+Nr82Y1WUD5ew9l62Jwz9JZP4UYuLqYXJ3ngKCU03sQ1DascSfufij1pRy6ViRBSaAhy205WA1w1u2qNd9VzAzxcLoIRmRMkH2Vq1s8DrunfdMoKxzGtXcQz+AkklwMqWmvnkDB/knXrlWDsrUfx8eMn4MeWF4JWP/lkEft,iv:9gwVdO8FdqH69CDrRNIm7kHlKlph1VXTV2opS50buhs=,tag:TnZTIM3uXrBf89Bo5csumw==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:k94WUWigCEpNyDnZx+bIQ9zMq/WGIksaQ2eeXe++KDynhAGR6MJmNPdfzD7rWOFlcmF0pYnpGSgqa870YnowuoSVzl0oNoUIjmJ4rBkTUvOWAGoogeBnEvyfSd3yW3BRs/nrb22N6JJirxxjIV8t4ZA0c0WcR1HTzQkUi5JIp+swPVgprtNKmtDAaDj9c53PUmMs5tc=,iv:oqQ5kT4QWFjDelkAJACli3xXB0gE37CU+QzaVl+UQcg=,tag:KjUF+qONHAfdKRXI80fxrQ==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:0P86XZITwVuaWp5VeNDUWWk+y4ObOmzN/f3ynjXgwCvEdNWui5gVgbkpgFQQvrTHPPsI3nc3q4Jo6ldgULDXVw==,iv:I3Pil7dqQJwl9K/tQyJ/puli/XsI+5OaXNGECZPbW2U=,tag:DvJOjMTHnbanqUdsBRwjdw==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:gCo6B6jPc7hW3ois/YJOH0DdVKPxjHVQm/RiRXlahsvi1h7TIx1Lwp3UkWw1WS/I3ghOnU9fd8b5zsMlnKxHSA==,iv:uhIJJUbB0psB3umBlbEZChDa6HI/sjjmZV6ZqvaOGFk=,tag:gnmF10zmCSLai5+3AcUNag==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:0woPyZvs+CAQB/Hie8ZpWvbLckPZKpbGQaEdcOlrC8J/pH6Om48TE8smWSYjGf6HbCq+NlrsbgSnb4qTCznJ0g==,iv:+XtNHUjGrhDmb6Gcgr3XtfDVEUJ74j/iJZdfQhbya8g=,tag:B68G1P7p4ArjHW/Dnl9NfA==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:p3ht1jXGq1dJ1fZq5rFPJ9st598N72qce41MsJNlV6UEQE70Db3ByhHSOlk2po71OhKbQEWDArV87w5+t5GkVA==,iv:Yb6QmED4fIXX6p9fzfHj7uFSDkR9YxRiEKv9LXHmmsY=,tag:VY6bshlgh7phlSobs7fCEg==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:sXjE7MHwxmGm,iv:TsU/Wxd4/jEcu/p/MGyJ6s4ugNX4Dwsn4OETURMZ3h0=,tag:fxAy6n7Za8xEt/jCsmgDGQ==,type:str]
goomy_private_key: ENC[AES256_GCM,data:3OkawumXwnL7xdiwHxuzlpQqNV9Uwwb7PIYd+NlbtLPLTpbdnid/+QDoZ6f8wQrARAKjZk8diVvl9UbMLe4v9g==,iv:DIKxr16KPEN3P1jPU5aR4GTzsqu2Nc3wX/9EmU1ApaQ=,tag:n9z64ZZY0Qpzmd32bEwTgQ==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:zstMw5e6/pFGgdYQ+Wf+IIEV8UnGlrM9MfGcnDC4lF1EyVUc+YLKHyuzGrEIRuf/j8lnR50XDWHie7c01bwrvA==,iv:ylg9OgWYywYMT/bUwzS8mzLb/G65eGUCp+kxKiATzAk=,tag:LNSbEzDpWoY7B2oAyRizMA==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:4ZMLAElvm8aT,iv:shaQRWGf4L99Fr7Uqz1hbUJUp4+dcOO1Yn2djn8jHAs=,tag:89TJiNUnarL4HL2N5QdbCw==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:OZUnq5M5dIG3Q9TF,iv:e5gNnAmvBVGsR4Fsm+C86eDCU9BLOjdRn6XTPaVxT8o=,tag:PIykzgAY27KDvsgk6Gk93w==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:GrkPzhlJBCsc9HnvvtQf+C2pFwJQ77/k/uYf61WzAlcFUTxVOv/3HfcnvaUWlDEn1UGYo27snhxrXPt0dq5OLA==,iv:urRHYCczG2PJQjH6nEnC54upkCOMXnRpgpgEm1HP3kk=,tag:jt9cmRqg6yWLO4kCE6PpNw==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:zSc86N87ElQTbLqn,iv:4+fUWUxefKT/va0SA/u1nuqksD8uh6XJTlGFB1trJmk=,tag:P07Du88Zv+f6B7h4spb+Bg==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:Pkyg+kC0VkLt,iv:BIRpj6UI+1Qr8xiuHh94n4jRwZZE7i7ECdQgWNgr4QM=,tag:xSxnVQqzE7N9QxrCwONoVA==,type:str]
sops:
    lastmodified: "2025-07-02T12:35:04Z"
    mac: ENC[AES256_GCM,data:PY5EMgXph7adbaZGKn2Ri+c5NByTvW6mRsOkGvVFPA/g8XBYntvtRKN/EOWdpKPQl8hEz+uOH1YfooZDdjOxXSsNlSil+xTasX7RmVg4ar7ksiGFcVjnJci3lWTvA4gEP6LhkWmc2g0ccriHzG/LsbeOzzPirVjQ64Qz7P7CT1o=,iv:MJ5k60s9g3hhwhTTa79T0fSLS6kw90u3IWgtbtU1X2I=,tag:bl4lpW92Yuq2yg4fkHwldg==,type:str]
    pgp:
        - created_at: "2025-07-02T12:35:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQAQ/9EDW0w+VfI72Sks4nhCgUxfky/V3Q2yTC61J9uFWLZJzB
            YOyWn/h6K0f+fhKdbrPHyuTY8qnUx0lGHG81EHRY/9qZ2OtoneT3UR9fvRWRGu3A
            Yp86KYfCGGgJkVedof8Xx1rzcZKgcT9E+uNqmcriSCl1z3xVvFCHK6l4JwDdj2Un
            MyUNPp6xaJA7HQTP06PN/7njuGmEaFu0rEdFJAytDtvh4sMN0DpdIyA+UDxEqnBx
            OlC3uP15G5ce3xLA+VopaBfQUPGumfFRjS+kKD+U29CRHx9U/ZJEI4Nf/m/PzjqX
            rt2qodIiQpsMXWzpNrBi+eMvq7ajZSmrRaB5NaXgeybUjuIDH/jiOJCnCk42WFur
            1+BJOJScHJjkSZaNWv+zIJ2gRwyUY/LAq2903yRyoJ/AzddVDKcwnrHtBANG+2rU
            uI22x6yIDG1LAzv+rxNGIi6evACpZyWmKkcSIPwts6x16airNPql7S7KxibCUpVY
            Y7oXAsFpePm+uQlF+vAs+LsOLZOC/fyiup+JLx2Id+1OvF57HwYafdNoyYJuwmf0
            GkLrSsvIFZoXKsteePrmWBTT0CE3IKQ9FY6ZDBXSeuOVw1JyaQMBnug6aGnr6IP7
            1CSIx7PMgDrT93Gi5tIPpRihfvZMdjInqUGswEiQVEo2tdJRp8sstpKYVa70WMfU
            ZgEJAhCmYAyN4VvbFFv75zgwyy1XJHQ7cjBUHWxFy9rGI2VEKaY0Thm0s1801Rkg
            Of1OqR5HhRrGxVN3RxB/Hj2FLnUmPsVaOZZFtUqks7OY0E+uDwRf7HjL4S+4lN2j
            Z7Oz1ZxAcg==
            =c1fk
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
