secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:ikwoF0Zyk7uJJ/KY6fh7MaAOQrog7X3RYxY4VquVFyD5Miwx/uw=,iv:/Z5Y7OBlKSEb9JTinQarsg5/QcQl+KjYqXUJL7qCQxo=,tag:qsbXKSgs35yKURjW4SUysw==,type:str]
    username: ENC[AES256_GCM,data:0+QyHfg9,iv:5xRfRS16MjYugtyFjzyzyALFWThO/zdg/iEMj40Axv0=,tag:x35A99YlY2MRHASAqorpjw==,type:str]
    password: ENC[AES256_GCM,data:achkHSX88AiwkP//,iv:ea06hKUaIy4P9YzkcG98cGONenZZzp4G8HtIYi3wGWo=,tag:BI1ZreTHoqgZfBDVZUMzqA==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:sCa8fNg7TH73XNWUwa7fh0YnNwjQXUiFPw==,iv:Te6X7IszXc1d0KXVUeUHWwfIAgbs98NppD7KJ9BNaKo=,tag:Sm2OTFr+INifWEo/w1AZkg==,type:str]
    username: ENC[AES256_GCM,data:/xW5N9g7,iv:2Btw5vom+vmve6Q8vRTkJC6xueST/gq0OUHuO05dXjM=,tag:kW7YW0a2A8VozI1gYvzb4g==,type:str]
    password: ENC[AES256_GCM,data:XNL5XiuLnI3L4EGc,iv:QPA1m3lgIotYTIgBwcW6vfIR9JJF0vJcXl0xVqbejjM=,tag:9mibAYm8mPBqzKnUEGBARg==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:4Qz5a3cvm+NxVtIv+uaHx0b24LEWUvYMnfNGMvN2KVT/8yNVYHfngyb6rQHL8br+/Lpnmjn6yC0tLq2gejpNEA==,iv:bsJE3gTLQuO04MW9q6TkUMNrexRMzYBE4Ob8BznGNzY=,tag:BsdacQninhJzmVDD+tkMHg==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:Pnc9iD0f4hizhsNpttwiKGjOaPyDtQ==,iv:bNauehiwKjo6/vmMST/cPEPgHGgEJ2jubX3X/Yf98UU=,tag:SMXiBVqcRE18F40IfZgavQ==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:+9U7PkgumvjUZat+zaBXlOL0eQbKeUY15FrWE2oU0DeMbgFH73mQyKVYzKbz6wGBoUhtniNGyTFCCZLFISZkCbadp9TlRHLSfNzpeo564CPO39QxzoM=,iv:lV9auGIKKTlrb6NKpxvKvfNbKzAn+RNg1JKR+p5XYDI=,tag:dA+CIlC0u/QaZz0qbWb8Pw==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:3BqbAKXb9rN7,iv:VMrLj0TRs8FsPdIs18ukcgW1g1fHbuWnO/OmMfDn1bA=,tag:0PLfx9wwbAXyLYUPql0+xg==,type:str]
    password: ENC[AES256_GCM,data:OebraPLuC0mkCxBY,iv://HLLjwEeEiy7a+OlZPsns4kpvAzvb/LpUcFnEnGu8E=,tag:i3aggVLQBLmpqnJtETQu1Q==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:/+8GZp7HOXHr,iv:gt1CNhaMRXRdFOZS1N6xs9od5xJK+zxf1H1/cp7zNgk=,tag:WY6q213AYw4DK7KhavGn6A==,type:str]
    password: ENC[AES256_GCM,data:s3/mXX+Qp71k/EsV,iv:Ap7hF8U6NiOr+sJ80cHQte8V2nr9dJjtVj+rcrRodlE=,tag:hte+oMg62bprAjA5VMVxjA==,type:str]
    server_address: ENC[AES256_GCM,data:Esg8jpHbHIkdgPqDEKjaslkp,iv:7mnfCqNR7JJK35G9M5g275aFxgksKHHhiiu5neCbdss=,tag:br/1Fe2xG7DhcOWowSEErQ==,type:str]
secret_ethstats: ENC[AES256_GCM,data:tuOi7Bn+iCFcB8XH28PhQ5TRRorqX4mPLqkYxBMUs2YoFXTAxLXwuVa5hmUkLjnaXSmkwHZ5qDf6mGbXLBSdrw==,iv:waBZeU2txazErPu9RRWivfBZzKkzU23KAGtjxmRCArc=,tag:2AJymWI1fUQTTthCLZFp8Q==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:iB51eiGtiHIwsDkqXfMB4KYrLBu8YxoYiO4VeCs8NHRGqbXTmuyJVv8gKOLpZBf9sIgyAZPFegcPO+uX49QKbxN6DpA/72+qU9AEWhyfMOlE/lgI9g6lSJ8fkUgxRK6fp4D063PWV2I/cvVTkMt1iX0Br8gaQqGwE0GUdf4aLDtdZ5kCHwqpcYg7a194kgKodCc0,iv:4Uz1oonlpgocJM/wxhP7705TIzHYrzCuy/CSIZjPVvw=,tag:HESmeS4++wgrAVv3d3tAtA==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:2lrvMc6ErsIruj3wuCH8WCyJ/CBkcZ399A0tbhWIQ+4sUwF/Nx1MC7xdaZik3zPvg4ORiaAKTq77upnuz+hszdTF5yOefoiy3o+7K1lEaQpXja0XE6wL2Gtulp4slsrj+TH5Ln0imgNlH2AEXHFOsyiAsG8T2VIXz0iRPq5TRRVNwThevwYmQcFJrSJS/sQ3ZkEGsas=,iv:MonDdR9uzEt4NdRhA+f4c94zeCWa2c0ST+o2K84iehM=,tag:7ptCZGaK5YyWWyhTjWhHGw==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:ubXvnuBehr8LgKyM9gQDLuQSop71ljnJfPYMq8VGqV6DnNJc5VHhgbK9utjd8lVVX8XNu1NflVfuWOdcN5DEiA==,iv:HF5f5KPWh668dD+dAEaCGFry6wCksuki5Xvgcxbjj+I=,tag:C3/rWI9Ds2mMFfoSjH0zFA==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:6W7YsV/NpnKyid3MT1cXYH19zgv4sKxCLCvI8oO9X2LqSaldzZxp8mkyzxqlLMxRl8XRwuw/bF3ImFV/Slwhgw==,iv:kQmGM0AvY9WabmBb4yEfUMXK8QQVqbZ5xnTG/l5D8Z8=,tag:p86jkb8NHX96WLXhbzoW8A==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:nIElnSnXmvEH3FadAZdOnHL3A+THDDRjwKa+qzfkU0ah8ZgaUpHrzBA+JKikBj48Qgh1xiNrrFPA2xreJnT7vA==,iv:hLQQ2QWZAKqV5txg/kiJ+fDeaDMkMILvxCvGYE82+g8=,tag:PAhCv25zHFe+nLRDEvnAcQ==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:HgRY0q7/UdWvaMV8tJ4XLysEc/IB8rknsBg40SycNf5irdyCfugSdUj6DiyD482lXwiexR6lYFZ1IBC86s3WVg==,iv:DX9/uLBXNMQXwKqIcPh/J0XpKVlP4PZDRpdYtRe2kqE=,tag:tM6h6wzY2wBYTYByuDqgdA==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:6efiqgx0zo/5,iv:d1OTN/fIoQQEYZyzpr0qC5V82xSlxLv6Gs2R+43aQ4Q=,tag:KAviJ/zM8VH/JLncrstNNg==,type:str]
goomy_private_key: ENC[AES256_GCM,data:VBWw6dK2bp7iqWrQUe0eh0Y/9i3cf/PNPcu+9anraFNWc4adsZg/3NF49d8zVgPCgqS7Uw3Qz6lVHTpepooaPw==,iv:Ghkcew4C+CS53d5L+KEiEqfKaH8+sOkGUSquryN70Sw=,tag:Qw44Ux8R0fDRHBUAsIr63g==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:lFe25fAgl+EUWd2fefy6bs2X9VkZLrgJQRNBtaxq2YkE+lrDVLU8kpHqs4zgmvf5r6kZbyigO94rLBWPZys/xg==,iv:qPuLkDxjOrP9Zcr3ExH1dtwXTebRbKcTVIsub3g6SxY=,tag:EkqKM3iNjYHqqTH28g38WA==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:ZhNJnJQnZJYZ,iv:unZZAZ5rd2prte3rSZT3xlJs06L4/H+G9gSeUIGbBUc=,tag:WAzvsa/taB8R0FaAfC1XNg==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:ijJL/z9I84m6Bnyn,iv:9INbEpvNyCwxtgm8G7fSwBbrbSt/Vm73WUBNKDfLCFs=,tag:FtnZMnlakJsBe7kwGPiyYw==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:ATNBzHsCYWhMh1n+I8DHPxJep/UptjlFgwCkMAH1D2BjDyVuy3dsaV+8oZGCohAFx4lNScaVShA9LiriKcKcUg==,iv:zyVbP4TlipGN9yVIJj/oikH/9ISYKo4GmGH22l0V6Bc=,tag:T4Kir+PDbf76XCXlhNw7Qg==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:lUbUrM8mG9D2hzfD,iv:CZSpqD0eNJPFSpokVfhcJ3TSfWtFR4CbcKEuIu8azLA=,tag:NO+99DhFqCVoO/TTVFzOtA==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:sNuy/Vx0YhUs,iv:crlG/dO3hp0l1k3ttd7GKXKhhNfk0zvo8hARyHDJCOQ=,tag:asl0ZrLGfLQwyUGNpX5Esg==,type:str]
sops:
    lastmodified: "2025-06-11T08:11:32Z"
    mac: ENC[AES256_GCM,data:8+t7v30etWwX2lNPbp8mkMJxMeOpbMwqxwE8jRVjL6+mQBgZ7knFvlz/wh4UTqGEvPUpjZ1XHApgf7EqdKa5GK108SITuVMj9igGcoSLFzrlMu9ObUTFbaaC1bNsd4EJL/sXqlgQZE81KL5NaLyjvybkF8O5ccB1zQ1ISBXSC30=,iv:ZsiP/nuDF/F/pRF69cAxFWy4sp7gKEtnjUAHG3PYvIA=,tag:qIk4McR/8VFSTI86VH9s9w==,type:str]
    pgp:
        - created_at: "2025-06-11T08:11:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQAQ//Ra4Q4RptRhcnHeMHfwiHLNaDeJuuLd40vgKVSMr1jZJ3
            ZsWSl+m0+fyrh17wpRnUBKfT+4M18jYIHECYAK+g7vY5ZdQ+IeVRqs1tT1gzj0/D
            fcoCnBpnUPU2cZibjCnCWwjW4gB00z8sLnes4hMWqxR5cesymIQAe74reiWMe1ni
            2SBDiuVL3l+mGLzUkLEHbiS/qkz4PNzs8o63N8hM26Lxr9+CPcjWUXyM8pRZWANE
            r9DJgQtaYG40cTE8fSGi755gTmtdaIhSOSK3nxSQtxYTxt3e+gXYJIDhUi9D/F4n
            wiJz4OlZyen3RV7PdKQIvJhQbRY7kGmdtlt6F+NfkACih8GX5dhqZf66aWcsJyC5
            jWp31fLnu6d9pytKTH7NP4aEtQE2BsRmDgvdEvqD5LrO9qT29K9OFCGm9Dvt1Ulm
            2lxlyhD2XncDsSCEJoQFQY9h+cwhncBwzTwGdT+Vokgzomv9GUrTUXUDAA+PK/Fv
            43HDXhO/lLdxuNJW4SoSW1ZF58TGYl1Xtj5j+9LZjTEcUwNwlnz1n4rW2JzXfk9d
            OvkasItNnXy7iZHAEI5JYdLVL4R8PDch/ctmezaqMplhNZaR3mk+f4FO4bokEHMf
            OEH806yB6I3RiGb5LmikKszxwTcyEOw1eUgAfid8CjudrNcXidwSnYwXrt3FTevU
            aAEJAhAU4JeyhRDQ/GqsjIvj9XOi/LrAmXPxhZHMCiL2Rmcm0jlWLjWEFCReOB2m
            PwnPa37v38AK1JbbjKPdY9eDXq4taYJH0PFF2G0MKSx+G35+EJBB4GetvlVOCBZ5
            uIJuWEBWbJHE
            =QXs3
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
