# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/spamoor.yaml.j2

spamoor:
  fullnameOverride: spamoor
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/spamoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: spamoor.fusaka-devnet-ssl-part-msg-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  customArgs:
    - --fulu-activation=1761192820

  persistence:
    enabled: true

  privateKey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.spamoor_private_key}>"
  rpcEndpoints:
  # Rpc
  - "http://geth-prysm-001:8545"
  - "name(bootnode-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-1.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-10)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-10.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-11)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-11.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-12)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-12.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-13)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-13.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-14)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-14.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-15)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-15.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-16)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-16.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-2.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-3)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-3.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-4)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-4.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-5)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-5.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-6)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-6.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-7)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-7.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-8)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-8.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
  - "name(prysm-geth-super-9)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-super-9.fusaka-devnet-ssl-part-msg-1.yolkie.xyz"
