default_ethereum_client_images:
### Consensus layer clients
  lighthouse: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:fusaka-devnet-3-1211aaf
  lodestar: docker.ethquokkaops.io/dh/ethpandaops/lodestar:fusaka-devnet-3-e03bda5
  nimbus: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth2:fusaka-devnet-3
  prysm: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain:fusaka-devnet-3-edfa363
  prysm_validator: docker.ethquokkaops.io/dh/ethpandaops/prysm-validator:fusaka-devnet-3-edfa363
  teku: docker.ethquokkaops.io/dh/ethpandaops/teku:fusaka-devnet-3-02d28dd
  grandine: docker.ethquokkaops.io/dh/ethpandaops/grandine:fusaka-devnet-3-457180c
### Execution layer clients
  besu: docker.ethquokkaops.io/dh/ethpandaops/besu:fusaka-devnet-3-947ec72
  geth: public.ecr.aws/s5g8t9d9/ethereum-devnets/geth:gas-limit-fix
  erigon: docker.ethquokkaops.io/dh/ethpandaops/erigon:fusaka-devnet-3-d4e5099
  ethereumjs: docker.ethquokkaops.io/dh/ethpandaops/ethereumjs:fusaka-devnet-2
  nethermind: docker.ethquokkaops.io/dh/ethpandaops/nethermind:fusaka-devnet-3-27f2025
  reth: docker.ethquokkaops.io/dh/ethpandaops/reth:fusaka-devnet-3-8402695
  nimbusel: docker.ethquokkaops.io/dh/ethpandaops/nimbus-eth1:fusaka-devnet-2-7f3fadf

default_tooling_images:
  mev_builder: docker.ethquokkaops.io/dh/ethpandaops/reth-rbuilder:bharath-123-fusaka-devnet-3
  mev_relay: docker.ethquokkaops.io/dh/ethpandaops/mev-boost-relay:bharath-123-fusaka-devnet-3
  xatu_sentry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_cannon: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_mimicry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  xatu_cl_mimicry: docker.ethquokkaops.io/dh/ethpandaops/xatu:latest
  ethereum_metrics_exporter: docker.ethquokkaops.io/dh/ethpandaops/ethereum-metrics-exporter:latest
  tx_fuzz: docker.ethquokkaops.io/dh/ethpandaops/tx-fuzz:latest
  forkmon: docker.ethquokkaops.io/dh/skylenet/nodemonitor:darkmode
  forky: docker.ethquokkaops.io/dh/ethpandaops/forky:latest
  fauceth: docker.ethquokkaops.io/dh/skylenet/fauceth:fix_fee_estimation
  powfaucet: docker.ethquokkaops.io/dh/pk910/powfaucet:v2-stable
  homepage: docker.ethquokkaops.io/dh/ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: docker.ethquokkaops.io/dh/ethpandaops/checkpointz:0.0.6-fulu
  blockscout: docker.ethquokkaops.io/dh/blockscout/blockscout:latest
  blockscout_frontend: docker.ethquokkaops.io/gh/blockscout/frontend:latest
  beacon_metrics_gazer: docker.ethquokkaops.io/dh/dapplion/beacon-metrics-gazer:latest
  eth_fauceth: docker.ethquokkaops.io/dh/chainflag/eth-faucet:latest
  blobscan: docker.ethquokkaops.io/dh/blossomlabs/blobscan:latest
  blobscan_indexer: docker.ethquokkaops.io/dh/blossomlabs/blobscan-indexer:latest
  dora: docker.ethquokkaops.io/dh/ethpandaops/dora:master-latest
  dugtrio: docker.ethquokkaops.io/dh/ethpandaops/dugtrio:latest
  ethereum_genesis_generator: docker.ethquokkaops.io/dh/ethpandaops/ethereum-genesis-generator:4.1.19
  tracoor: docker.ethquokkaops.io/dh/ethpandaops/tracoor:0.0.26-debian
  ncli: docker.ethquokkaops.io/dh/status-im/nimbus-eth2:unstable
  lcli: docker.ethquokkaops.io/dh/ethpandaops/lighthouse:fusaka-devnet-3
  zcli: electra
  assertoor: docker.ethquokkaops.io/dh/ethpandaops/assertoor:master-latest
  erpc: docker.ethquokkaops.io/gh/erpc/erpc:0.0.49
  prometheus: docker.ethquokkaops.io/dh/prom/prometheus:v2.40.7
  node_exporter: docker.ethquokkaops.io/dh/prom/node-exporter:v1.5.0
  cl_bootnode: docker.ethquokkaops.io/dh/protolambda/eth2-bootnode:cleanup
  json_rpc_snooper: docker.ethquokkaops.io/dh/ethpandaops/rpc-snooper:latest
  nginx_proxy: docker.ethquokkaops.io/dh/nginx:alpine
  nginx_proxy_gen: docker.ethquokkaops.io/dh/nginxproxy/docker-gen
  nginx_proxy_acme: docker.ethquokkaops.io/dh/nginxproxy/acme-companion
  vector: docker.ethquokkaops.io/dh/timberio/vector:0.46.1-alpine
  spamoor: docker.ethquokkaops.io/dh/ethpandaops/spamoor:master-latest
  blobber: docker.ethquokkaops.io/dh/ethpandaops/blobber:pr-43
  syncoor_web: docker.ethquokkaops.io/gh/ethpandaops/syncoor-web:master
  syncoor_server: docker.ethquokkaops.io/gh/ethpandaops/syncoor:master