# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: fusaka-devnet-ssl-part-msg-1
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        fusaka-devnet-ssl-part-msg-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-part-msg-1.yolkie.xyz
    clientArgs:
      networks:
        fusaka-devnet-ssl-part-msg-1:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://7dd5f1afaecec279aabede422b1d2383156e99ff3e577168741709c7adbb5b526c2d7432e62d7bf3ede09e50f32dc20f35e0e593f78a85b36b62601c25573cb7@209.38.109.57:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-part-msg-1.yolkie.xyz:443
              - --tx-pool-max-prioritized-by-type="BLOB=72"
              - --target-gas-limit=100000000
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://7dd5f1afaecec279aabede422b1d2383156e99ff3e577168741709c7adbb5b526c2d7432e62d7bf3ede09e50f32dc20f35e0e593f78a85b36b62601c25573cb7@209.38.109.57:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --EthStats.Enabled=true
              - --EthStats.Name=localhost
              - --EthStats.Secret=5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd
              - --EthStats.Server=wss://ethstats.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Blocks.TargetBlockGasLimit=100000000
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7059385040
              - --syncmode=full
              - --bootnodes=enode://7dd5f1afaecec279aabede422b1d2383156e99ff3e577168741709c7adbb5b526c2d7432e62d7bf3ede09e50f32dc20f35e0e593f78a85b36b62601c25573cb7@209.38.109.57:30303?discport=30303,enode://e14c849ccf816794e5a2565bf6f925ee085ea7d0e31b0f51ac5a62a3706d13b65679ae74c5dca2ed907cb3c5f28da4dcdf693d9b524dee12a56657ee324ab4ba@137.184.153.78:30303?discport=30303,enode://b5f8a7d9dae3b95a1ecdbe483897297fb4f88e14bf435a8fb0612095f09027891136f03d1e2dde6c5750715f04893da882212e58fbd177a9bd8c91c87bcfb001@143.198.149.195:30303?discport=30303,enode://ae5ee379ec8b0a43160beb776fc84e3d4a8545c59c35833a8104649a62d642b4aed41ebd260906d07d3d5a09a4a828efeaf0f96925f0dff5eef851666995fcb4@142.93.128.5:30303?discport=30303,enode://b440453dee9af5beb9c4559965aaefc414b41b5ca671ad8de6eaf5916b08dc4ee975ad4024f3e1a4a52b982c3c427e6072ff6d75a9c7e22f6302322df7589189@206.189.26.121:30303?discport=30303,enode://41f501848f9b7629683f3f7c653823cd3fc8cf3a44b8fb228e5456d849f98a305897250b9533e872e9224b5fd260693763a27eb5cd9b27b003cd80067ec400a1@64.226.68.219:30303?discport=30303,enode://4773b9077bd842228cf93e199c8cbf3447bc30b09cc351ac6306a607011914fc0014439fceffe11983e3af86c94a2e0fb262a95492ef95ebfe19b4b919d2aec5@138.197.165.51:30303?discport=30303,enode://eecdd9baf09b188fbe4dd3812bf0a7ed9dffb09c38f55bc716b0140a3d89a5e6220d4b1807dab01bbbea0c125cf6dada4d9f1765563272eaf41bc8d90eed3614@143.110.177.102:30303?discport=30303,enode://50f7b7b6e2d29a4baa1a82303b4fec88226e9f74f4f1bd286a88959a8d6dcc0f63fe454ebb6e6cc1068478497489c9caeef6b41d80a0483a21e3884d417e51d2@134.199.144.99:30303?discport=30303,enode://bd78280dd30bb044feba06a652344b5d49c7a9438e9d70bdaf12783ce52def06ff70c62eb826db626ad27c159bcd2a4a8391c51b16e051bbe7c723a49df22815@143.198.106.95:30303?discport=30303,enode://e3b8e8ba843fdc9e60089fc698f30a1242a5d8dc08824b4d32019aaee8eb4bda9c214c806686e8fb056a691408ab819fef220f5929db940077f7b6e3983ed4ab@167.99.39.48:30303?discport=30303,enode://9e5abbd1c0488f37ee2928c68b3d6977b30043f18dee0bfe50baad1b3fd2d2224c603cceaa9c6a1942a21f1a082df5f9ab9bb922e40d8444af6de8c53ec65ae3@178.128.41.68:30303?discport=30303,enode://c965d8c755b451cd3c4ce4cd6fe0ff82a150a734ed88702ceaca5f3a9165c20dd7dbcfcdad6f543b22513d950a32e1ea55b52c4f0f93ad33aedb0269538e206d@207.154.238.44:30303?discport=30303,enode://1b7959e8e947bee3ade63c761cb4a1d58e67ddbf540357a859ffc6e1f15ca2cabe2ef0f2042648b747f7ad974a5eacce58e17b09e8a15200f782c758e2161e05@143.198.34.94:30303?discport=30303,enode://c8091971836302878ee213fcc4ec538779b70455b9454170dce03497654fd7edf57d32826e30ed4ad85970707d1e7b60a9dd144e2c80d6a328366cbef69111fd@139.59.35.19:30303?discport=30303,enode://183d60360e7b16f01f12ccdd9c666cfad186f268ad907b546f94e33b63d46e6be09d7a45349f9520439167f35741e525861c0703aceeab79697f8bfa9e219769@209.38.18.99:30303?discport=30303,enode://b994f106328221aa2cfdf5ecd270d1da4659f51708ab01aeb6f7cf7f5818eb9b4ac7a8e8bfcd503ecb9d3598c48a36bef6ea8d5582677860a6a92b709d8b17fa@147.182.138.84:30303?discport=30303,enode://45fa9074a23be0512716cc80141c05b0a6370b510878ef5f2fe778e1d67bcab5e083cb636e52103e14c032d8738531f93936c11f68832abba293d32745d38b7e@206.189.193.45:30303?discport=30303
              - --miner.gaslimit=60000000
              - --rpc.allow-unprotected-txs
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --no-downloader
              - --networkid=7059385040
              - --db.size.limit=500GB
              - --bootnodes=enode://7dd5f1afaecec279aabede422b1d2383156e99ff3e577168741709c7adbb5b526c2d7432e62d7bf3ede09e50f32dc20f35e0e593f78a85b36b62601c25573cb7@209.38.109.57:30303?discport=30303
              - --miner.gaslimit=100000000
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-part-msg-1.yolkie.xyz
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QFqyzhwBQvbdYY-a0QdXelkTa0YWd4UOaZpZCvH-GrTFFelGcaAywrBl8GDUUHYwkI3mjnbC5Af8xGjje7kYYg2GAZooAEkqgmlkgnY0gmlwhNEmbTmJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-PC4QDRYP5qNKdJFFGf7FjwwHGM6WR-5SrQWkyfOz2GLUHnzS2xAW-KFVWwI9eBxnDm98s8seu0yCwLEh2wRqf89zc8Dh2F0dG5ldHOIAAAAAAAAAAODY2djBIZjbGllbnTWikxpZ2h0aG91c2WKOC4wLjAtcmMuMIRldGgykMkVWitwSFggAQAAAAAAAACCaWSCdjSCaXCE0SZtOYNuZmSE-PXChYRxdWljgiMpiXNlY3AyNTZrMaECONF4OytftDYBiyHuPdyEC5O9MXM5I9WVUCQbmP8INcqIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --logLevel=debug
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QFqyzhwBQvbdYY-a0QdXelkTa0YWd4UOaZpZCvH-GrTFFelGcaAywrBl8GDUUHYwkI3mjnbC5Af8xGjje7kYYg2GAZooAEkqgmlkgnY0gmlwhNEmbTmJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-PC4QDRYP5qNKdJFFGf7FjwwHGM6WR-5SrQWkyfOz2GLUHnzS2xAW-KFVWwI9eBxnDm98s8seu0yCwLEh2wRqf89zc8Dh2F0dG5ldHOIAAAAAAAAAAODY2djBIZjbGllbnTWikxpZ2h0aG91c2WKOC4wLjAtcmMuMIRldGgykMkVWitwSFggAQAAAAAAAACCaWSCdjSCaXCE0SZtOYNuZmSE-PXChYRxdWljgiMpiXNlY3AyNTZrMaECONF4OytftDYBiyHuPdyEC5O9MXM5I9WVUCQbmP8INcqIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=debug
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --partial-data-column-regex=.*
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QFqyzhwBQvbdYY-a0QdXelkTa0YWd4UOaZpZCvH-GrTFFelGcaAywrBl8GDUUHYwkI3mjnbC5Af8xGjje7kYYg2GAZooAEkqgmlkgnY0gmlwhNEmbTmJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-PC4QDRYP5qNKdJFFGf7FjwwHGM6WR-5SrQWkyfOz2GLUHnzS2xAW-KFVWwI9eBxnDm98s8seu0yCwLEh2wRqf89zc8Dh2F0dG5ldHOIAAAAAAAAAAODY2djBIZjbGllbnTWikxpZ2h0aG91c2WKOC4wLjAtcmMuMIRldGgykMkVWitwSFggAQAAAAAAAACCaWSCdjSCaXCE0SZtOYNuZmSE-PXChYRxdWljgiMpiXNlY3AyNTZrMaECONF4OytftDYBiyHuPdyEC5O9MXM5I9WVUCQbmP8INcqIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QFqyzhwBQvbdYY-a0QdXelkTa0YWd4UOaZpZCvH-GrTFFelGcaAywrBl8GDUUHYwkI3mjnbC5Af8xGjje7kYYg2GAZooAEkqgmlkgnY0gmlwhNEmbTmJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-PC4QDRYP5qNKdJFFGf7FjwwHGM6WR-5SrQWkyfOz2GLUHnzS2xAW-KFVWwI9eBxnDm98s8seu0yCwLEh2wRqf89zc8Dh2F0dG5ldHOIAAAAAAAAAAODY2djBIZjbGllbnTWikxpZ2h0aG91c2WKOC4wLjAtcmMuMIRldGgykMkVWitwSFggAQAAAAAAAACCaWSCdjSCaXCE0SZtOYNuZmSE-PXChYRxdWljgiMpiXNlY3AyNTZrMaECONF4OytftDYBiyHuPdyEC5O9MXM5I9WVUCQbmP8INcqIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --sync-light-client=false
              - --light-client-data-serve=false
              - --light-client-data-import-mode=none
              - --bootstrap-node=enr:-Iq4QFqyzhwBQvbdYY-a0QdXelkTa0YWd4UOaZpZCvH-GrTFFelGcaAywrBl8GDUUHYwkI3mjnbC5Af8xGjje7kYYg2GAZooAEkqgmlkgnY0gmlwhNEmbTmJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-PC4QDRYP5qNKdJFFGf7FjwwHGM6WR-5SrQWkyfOz2GLUHnzS2xAW-KFVWwI9eBxnDm98s8seu0yCwLEh2wRqf89zc8Dh2F0dG5ldHOIAAAAAAAAAAODY2djBIZjbGllbnTWikxpZ2h0aG91c2WKOC4wLjAtcmMuMIRldGgykMkVWitwSFggAQAAAAAAAACCaWSCdjSCaXCE0SZtOYNuZmSE-PXChYRxdWljgiMpiXNlY3AyNTZrMaECONF4OytftDYBiyHuPdyEC5O9MXM5I9WVUCQbmP8INcqIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: public.ecr.aws/s5g8t9d9/ethereum-devnets/geth
      tag: getBlobsV3
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31376
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: fusaka-devnet-ssl-part-msg-1
      testnet: fusaka-devnet-ssl-part-msg-1
      ethereum_network: fusaka-devnet-ssl-part-msg-1
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/el/chainspec.json;
            GENESIS_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/el/genesis.json;
            BESU_GENESIS_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/el/besu.json;
            ENODES_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: public.ecr.aws/s5g8t9d9/ethereum-devnets/geth:getBlobsV3
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: false
      addresses:
        fusaka-devnet-ssl-part-msg-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-part-msg-1.yolkie.xyz
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: public.ecr.aws/s5g8t9d9/ethereum-devnets/prysm
      tag: partial-columns
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32376
    podLabels:
      network: fusaka-devnet-ssl-part-msg-1
      testnet: fusaka-devnet-ssl-part-msg-1
      ethereum_network: fusaka-devnet-ssl-part-msg-1
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.fusaka-devnet-ssl-part-msg-1.yolkie.xyz/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
