localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-chaos-3

[bootnode]
bootnode-1 ansible_host=68.183.3.254 ipv6=2a03:b0c0:2:f0::d9ae:4001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True 

[grandine_geth]
grandine-geth-1 ansible_host=165.227.204.52 ipv6=2604:a880:400:d1:0:2:b986:5001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=360 validator_end=368 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-geth-2 ansible_host=24.199.111.247 ipv6=2604:a880:4:1d0::ee9d:0 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=368 validator_end=376 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-geth-3 ansible_host=164.92.213.10 ipv6=2a03:b0c0:2:f0::d9ae:2001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=376 validator_end=384 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-geth-4 ansible_host=134.209.188.120 ipv6=2a03:b0c0:1:e0::a54b:5001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=384 validator_end=392 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-geth-5 ansible_host=157.230.113.163 ipv6=2a03:b0c0:3:f0:0:1:3789:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=392 validator_end=400 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_nethermind]
grandine-nethermind-1 ansible_host=146.190.66.25 ipv6=2604:a880:400:d1:0:2:b985:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=408 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-nethermind-2 ansible_host=24.144.80.211 ipv6=2604:a880:4:1d0::ee9d:3000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=408 validator_end=416 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-nethermind-3 ansible_host=165.232.87.86 ipv6=2a03:b0c0:2:f0::d9ad:d001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=416 validator_end=424 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-nethermind-4 ansible_host=178.62.32.104 ipv6=2a03:b0c0:1:e0::a54b:f001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=424 validator_end=432 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-nethermind-5 ansible_host=209.38.224.59 ipv6=2a03:b0c0:3:f0:0:1:3787:b000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=432 validator_end=440 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_reth]
grandine-reth-1 ansible_host=157.245.254.147 ipv6=2604:a880:400:d1:0:2:b986:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=440 validator_end=448 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-reth-2 ansible_host=64.23.150.52 ipv6=2604:a880:4:1d0::ee9d:7000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=448 validator_end=456 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-reth-3 ansible_host=134.122.55.217 ipv6=2a03:b0c0:2:f0::d9ae:6001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=456 validator_end=464 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-reth-4 ansible_host=139.59.182.71 ipv6=2a03:b0c0:1:e0::a54c:1 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=464 validator_end=472 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-reth-5 ansible_host=209.38.250.215 ipv6=2a03:b0c0:3:f0:0:1:3787:f000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=472 validator_end=480 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_geth]
lighthouse-geth-1 ansible_host=192.241.131.71 ipv6=2604:a880:400:d1:0:2:b985:d001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=120 validator_end=128 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-geth-2 ansible_host=147.182.230.175 ipv6=2604:a880:4:1d0::ee9d:8000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=128 validator_end=136 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-geth-3 ansible_host=174.138.3.135 ipv6=2a03:b0c0:2:f0::d9ad:b001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=136 validator_end=144 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-geth-4 ansible_host=165.232.34.22 ipv6=2a03:b0c0:1:e0::a54b:6001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=144 validator_end=152 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-geth-5 ansible_host=64.226.75.254 ipv6=2a03:b0c0:3:f0:0:1:3787:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=152 validator_end=160 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=157.230.61.139 ipv6=2604:a880:400:d1:0:2:b986:3001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=160 validator_end=168 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-nethermind-2 ansible_host=137.184.127.226 ipv6=2604:a880:4:1d0::ee9d:2000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=168 validator_end=176 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-nethermind-3 ansible_host=134.209.194.104 ipv6=2a03:b0c0:2:f0::d9ad:c001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=176 validator_end=184 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-nethermind-4 ansible_host=159.65.24.182 ipv6=2a03:b0c0:1:e0::a54b:c001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=184 validator_end=192 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-nethermind-5 ansible_host=167.99.137.170 ipv6=2a03:b0c0:3:f0:0:1:3789:2000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=192 validator_end=200 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_reth]
lighthouse-reth-1 ansible_host=198.211.107.189 ipv6=2604:a880:400:d1:0:2:b986:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=200 validator_end=208 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-reth-2 ansible_host=143.198.56.149 ipv6=2604:a880:4:1d0::ee9c:f000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=208 validator_end=216 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-reth-3 ansible_host=174.138.4.61 ipv6=2a03:b0c0:2:f0::d9ae:1 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=216 validator_end=224 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-reth-4 ansible_host=134.122.96.209 ipv6=2a03:b0c0:1:e0::a54c:1001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=224 validator_end=232 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-reth-5 ansible_host=188.166.163.187 ipv6=2a03:b0c0:3:f0:0:1:3789:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=232 validator_end=240 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_geth]
prysm-geth-1 ansible_host=159.223.106.102 ipv6=2604:a880:400:d1:0:2:b986:2001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-geth-2 ansible_host=143.198.230.170 ipv6=2604:a880:4:1d0::ee9c:d000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=8 validator_end=16 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-geth-3 ansible_host=174.138.1.84 ipv6=2a03:b0c0:2:f0::d9ae:3001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=16 validator_end=24 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-geth-4 ansible_host=64.227.43.181 ipv6=2a03:b0c0:1:e0::a54b:4001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=24 validator_end=32 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-geth-5 ansible_host=209.38.253.4 ipv6=2a03:b0c0:3:f0:0:1:3788:2000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=32 validator_end=40 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_nethermind]
prysm-nethermind-1 ansible_host=167.172.148.222 ipv6=2604:a880:400:d1:0:2:b985:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=40 validator_end=48 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-nethermind-2 ansible_host=137.184.115.46 ipv6=2604:a880:4:1d0::ee9c:e000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=48 validator_end=56 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-nethermind-3 ansible_host=206.189.2.106 ipv6=2a03:b0c0:2:f0::d9ad:f001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-nethermind-4 ansible_host=138.68.154.150 ipv6=2a03:b0c0:1:e0::a54b:e001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=64 validator_end=72 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-nethermind-5 ansible_host=46.101.168.69 ipv6=2a03:b0c0:3:f0:0:1:3788:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_reth]
prysm-reth-1 ansible_host=157.245.87.65 ipv6=2604:a880:400:d1:0:2:b985:a001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=80 validator_end=88 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-reth-2 ansible_host=146.190.43.213 ipv6=2604:a880:4:1d0::ee9d:6000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-reth-3 ansible_host=164.92.150.37 ipv6=2a03:b0c0:2:f0::d9ad:e001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=96 validator_end=104 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-reth-4 ansible_host=167.99.92.30 ipv6=2a03:b0c0:1:e0::a54b:d001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-reth-5 ansible_host=167.99.143.111 ipv6=2a03:b0c0:3:f0:0:1:3788:3000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=112 validator_end=120 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_geth]
teku-geth-1 ansible_host=161.35.52.78 ipv6=2604:a880:400:d1:0:2:b985:9001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=240 validator_end=248 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-geth-2 ansible_host=143.198.236.62 ipv6=2604:a880:4:1d0::ee9c:c000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=248 validator_end=256 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-geth-3 ansible_host=142.93.141.117 ipv6=2a03:b0c0:2:f0::d9ad:a001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=256 validator_end=264 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-geth-4 ansible_host=167.99.200.104 ipv6=2a03:b0c0:1:e0::a54b:8001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=264 validator_end=272 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-geth-5 ansible_host=138.68.86.159 ipv6=2a03:b0c0:3:f0:0:1:3788:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=272 validator_end=280 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_nethermind]
teku-nethermind-1 ansible_host=159.89.95.145 ipv6=2604:a880:400:d1:0:2:b986:4001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=280 validator_end=288 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-nethermind-2 ansible_host=146.190.142.111 ipv6=2604:a880:4:1d0::ee9d:5000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=288 validator_end=296 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-nethermind-3 ansible_host=161.35.145.172 ipv6=2a03:b0c0:2:f0::d9ae:7001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=296 validator_end=304 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-nethermind-4 ansible_host=46.101.76.23 ipv6=2a03:b0c0:1:e0::a54b:7001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=304 validator_end=312 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-nethermind-5 ansible_host=134.209.243.130 ipv6=2a03:b0c0:3:f0:0:1:3789:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=312 validator_end=320 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_reth]
teku-reth-1 ansible_host=134.122.117.150 ipv6=2604:a880:400:d1:0:2:b985:8001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=320 validator_end=328 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-reth-2 ansible_host=143.198.106.23 ipv6=2604:a880:4:1d0::ee9d:4000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=328 validator_end=336 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-reth-3 ansible_host=159.223.227.36 ipv6=2a03:b0c0:2:f0::d9ae:5001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=336 validator_end=344 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-reth-4 ansible_host=209.38.167.75 ipv6=2a03:b0c0:1:e0::a54c:2001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=344 validator_end=352 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-reth-5 ansible_host=164.92.188.158 ipv6=2a03:b0c0:3:f0:0:1:3787:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=352 validator_end=360 bandwidth=0 down_bandwidth=0 up_bandwidth=0


# Consensus client groups

[lighthouse:children]
lighthouse_geth
lighthouse_nethermind
lighthouse_reth
[lodestar:children]
[nimbus:children]
[teku:children]
teku_geth
teku_nethermind
teku_reth
[prysm:children]
prysm_geth
prysm_nethermind
prysm_reth
[grandine:children]
grandine_geth
grandine_nethermind
grandine_reth

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
grandine_geth
lighthouse_geth
prysm_geth
teku_geth
[nethermind:children]
grandine_nethermind
lighthouse_nethermind
prysm_nethermind
teku_nethermind
[erigon:children]
[reth:children]
grandine_reth
lighthouse_reth
prysm_reth
teku_reth
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
prysm
teku

[execution_node:children]
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

[chaosd:children]
ethereum_node
