xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-devnet-ssl-part-msg-1-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-devnet-ssl-part-msg-1"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://7dd5f1afaecec279aabede422b1d2383156e99ff3e577168741709c7adbb5b526c2d7432e62d7bf3ede09e50f32dc20f35e0e593f78a85b36b62601c25573cb7@209.38.109.57:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
