xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-devnet-ssl-part-msg-1-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-devnet-ssl-part-msg-1"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://ae7c7f3189b8f7b8bfd83a4319305e0d02ab98f3466bf32a2e85710e919844aa3304a79436a0ab20d83c8eb1bf048cbbf198a16f0d74e50bee4ae528aafc279e@209.38.109.57:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
