# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: http://geth-prysm-001:8545
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://rpc.bootnode-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-10.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-10
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-11.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-11
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-12.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-12
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-13.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-13
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-14.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-14
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-15.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-15
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-16.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-16
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-17.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-17
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-18.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-18
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-19.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-19
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-2.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-20.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-20
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-21.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-21
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-22.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-22
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-23.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-23
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-24.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-24
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-25.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-25
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-26.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-26
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-27.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-27
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-28.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-28
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-29.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-29
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-3.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-3
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-30.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-30
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-31.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-31
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-32.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-32
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-33.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-33
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-34.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-34
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-35.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-35
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-36.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-36
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-37.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-37
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-38.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-38
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-39.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-39
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-4.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-4
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-40.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-40
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-41.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-41
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-42.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-42
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-43.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-43
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-44.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-44
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-45.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-45
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-5.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-5
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-6.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-6
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-7.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-7
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-8.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-8
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-full-9.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-full-9
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-super-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-super-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-super-2.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-super-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-super-3.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-super-3
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-super-4.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-super-4
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-super-5.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
  name: lighthouse-geth-super-5
  authGroup: pandaops
  priority: -1
  archive: false
