localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-chaos-5

[bootnode]
bootnode-1 ansible_host=165.232.84.100 ipv6=2a03:b0c0:2:f0::de2a:d001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True 

[grandine_besu]
grandine-besu-1 ansible_host=134.209.212.191 ipv6=2604:a880:400:d1:0:2:c4fa:7001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=448 validator_end=456 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-besu-2 ansible_host=146.190.35.13 ipv6=2604:a880:4:1d0::f379:d000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=456 validator_end=464 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_erigon]
grandine-erigon-1 ansible_host=67.205.173.54 ipv6=2604:a880:400:d1:0:2:c4fb:d001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=464 validator_end=472 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-erigon-2 ansible_host=143.198.63.222 ipv6=2604:a880:4:1d0::f379:c000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=472 validator_end=480 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_geth]
grandine-geth-1 ansible_host=192.241.134.96 ipv6=2604:a880:400:d1:0:2:c4fb:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=400 validator_end=408 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-geth-2 ansible_host=146.190.137.90 ipv6=2604:a880:4:1d0::f37a:2000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=408 validator_end=416 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_nethermind]
grandine-nethermind-1 ansible_host=198.199.80.158 ipv6=2604:a880:400:d1:0:2:c4fb:3001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=416 validator_end=424 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-nethermind-2 ansible_host=147.182.235.61 ipv6=2604:a880:4:1d0::f37a:3000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=424 validator_end=432 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[grandine_reth]
grandine-reth-1 ansible_host=192.241.153.197 ipv6=2604:a880:400:d1:0:2:c4fb:c001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=432 validator_end=440 bandwidth=0 down_bandwidth=0 up_bandwidth=0
grandine-reth-2 ansible_host=143.198.66.250 ipv6=2604:a880:4:1d0::f379:2000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=440 validator_end=448 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_besu]
lighthouse-besu-1 ansible_host=142.93.62.142 ipv6=2604:a880:400:d1:0:2:c4fb:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=128 validator_end=136 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-besu-2 ansible_host=164.92.89.12 ipv6=2604:a880:4:1d0::f379:b000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=136 validator_end=144 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_erigon]
lighthouse-erigon-1 ansible_host=143.244.145.227 ipv6=2604:a880:400:d1:0:2:c4fb:6001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=144 validator_end=152 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-erigon-2 ansible_host=64.23.146.42 ipv6=2604:a880:4:1d0::f378:c000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=152 validator_end=160 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_geth]
lighthouse-geth-1 ansible_host=167.71.27.238 ipv6=2604:a880:400:d1:0:2:c4fc:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=80 validator_end=88 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-geth-2 ansible_host=147.182.245.125 ipv6=2604:a880:4:1d0::f379:5000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_nethermind]
lighthouse-nethermind-1 ansible_host=143.198.127.196 ipv6=2604:a880:400:d1:0:2:c4fa:c001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=96 validator_end=104 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-nethermind-2 ansible_host=143.198.135.253 ipv6=2604:a880:4:1d0::f378:9000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lighthouse_reth]
lighthouse-reth-1 ansible_host=192.241.148.26 ipv6=2604:a880:400:d1:0:2:c4fa:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=112 validator_end=120 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lighthouse-reth-2 ansible_host=137.184.183.54 ipv6=2604:a880:4:1d0::f379:0 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=120 validator_end=128 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lodestar_besu]
lodestar-besu-1 ansible_host=192.241.156.226 ipv6=2604:a880:400:d1:0:2:c4fb:8001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=288 validator_end=296 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lodestar-besu-2 ansible_host=147.182.199.225 ipv6=2604:a880:4:1d0::f378:8000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=296 validator_end=304 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lodestar_erigon]
lodestar-erigon-1 ansible_host=104.248.62.150 ipv6=2604:a880:400:d1:0:2:c4fa:5001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=304 validator_end=312 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lodestar-erigon-2 ansible_host=143.198.73.59 ipv6=2604:a880:4:1d0::f37a:0 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=312 validator_end=320 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lodestar_geth]
lodestar-geth-1 ansible_host=198.199.85.83 ipv6=2604:a880:400:d1:0:2:c4fa:a001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=240 validator_end=248 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lodestar-geth-2 ansible_host=24.199.102.154 ipv6=2604:a880:4:1d0::f379:1000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=248 validator_end=256 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lodestar_nethermind]
lodestar-nethermind-1 ansible_host=192.81.217.14 ipv6=2604:a880:400:d1:0:2:c4fb:b001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=256 validator_end=264 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lodestar-nethermind-2 ansible_host=24.199.117.116 ipv6=2604:a880:4:1d0::f379:9000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=264 validator_end=272 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[lodestar_reth]
lodestar-reth-1 ansible_host=198.199.75.180 ipv6=2604:a880:400:d1:0:2:c4fb:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=272 validator_end=280 bandwidth=0 down_bandwidth=0 up_bandwidth=0
lodestar-reth-2 ansible_host=147.182.199.18 ipv6=2604:a880:4:1d0::f378:d000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=280 validator_end=288 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[nimbus_besu]
nimbus-besu-1 ansible_host=157.230.184.133 ipv6=2604:a880:400:d1:0:2:c4fa:b001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=368 validator_end=376 bandwidth=0 down_bandwidth=0 up_bandwidth=0
nimbus-besu-2 ansible_host=64.23.194.65 ipv6=2604:a880:4:1d0::f378:b000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=376 validator_end=384 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[nimbus_erigon]
nimbus-erigon-1 ansible_host=137.184.17.157 ipv6=2604:a880:400:d1:0:2:c4fa:6001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=384 validator_end=392 bandwidth=0 down_bandwidth=0 up_bandwidth=0
nimbus-erigon-2 ansible_host=147.182.199.212 ipv6=2604:a880:4:1d0::f379:3000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=392 validator_end=400 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[nimbus_geth]
nimbus-geth-1 ansible_host=206.189.232.65 ipv6=2604:a880:400:d1:0:2:c4fc:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=320 validator_end=328 bandwidth=0 down_bandwidth=0 up_bandwidth=0
nimbus-geth-2 ansible_host=134.199.233.147 ipv6=2604:a880:4:1d0::f37a:1000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=328 validator_end=336 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[nimbus_nethermind]
nimbus-nethermind-1 ansible_host=192.241.147.61 ipv6=2604:a880:400:d1:0:2:c4fb:2001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=336 validator_end=344 bandwidth=0 down_bandwidth=0 up_bandwidth=0
nimbus-nethermind-2 ansible_host=137.184.80.76 ipv6=2604:a880:4:1d0::f379:6000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=344 validator_end=352 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[nimbus_reth]
nimbus-reth-1 ansible_host=157.230.61.223 ipv6=2604:a880:400:d1:0:2:c4fb:a001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=352 validator_end=360 bandwidth=0 down_bandwidth=0 up_bandwidth=0
nimbus-reth-2 ansible_host=143.198.137.172 ipv6=2604:a880:4:1d0::f37a:4000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=360 validator_end=368 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_besu]
prysm-besu-1 ansible_host=198.199.74.91 ipv6=2604:a880:400:d1:0:2:c4fb:9001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=48 validator_end=56 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-besu-2 ansible_host=134.199.210.40 ipv6=2604:a880:4:1d0::f379:e000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_erigon]
prysm-erigon-1 ansible_host=159.223.120.250 ipv6=2604:a880:400:d1:0:2:c4fa:9001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=64 validator_end=72 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-erigon-2 ansible_host=143.110.149.79 ipv6=2604:a880:4:1d0::f379:a000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_geth]
prysm-geth-1 ansible_host=67.205.147.113 ipv6=2604:a880:400:d1:0:2:c4fb:5001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-geth-2 ansible_host=143.198.230.70 ipv6=2604:a880:4:1d0::f379:f000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=8 validator_end=16 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_nethermind]
prysm-nethermind-1 ansible_host=64.227.6.3 ipv6=2604:a880:400:d1:0:2:c4fa:3001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=16 validator_end=24 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-nethermind-2 ansible_host=147.182.233.103 ipv6=2604:a880:4:1d0::f378:a000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=24 validator_end=32 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[prysm_reth]
prysm-reth-1 ansible_host=142.93.8.112 ipv6=2604:a880:400:d1:0:2:c4fa:8001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=32 validator_end=40 bandwidth=0 down_bandwidth=0 up_bandwidth=0
prysm-reth-2 ansible_host=64.23.207.238 ipv6=2604:a880:4:1d0::f379:7000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=40 validator_end=48 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_besu]
teku-besu-1 ansible_host=162.243.170.146 ipv6=2604:a880:400:d1:0:2:c4fa:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=208 validator_end=216 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-besu-2 ansible_host=147.182.253.69 ipv6=2604:a880:4:1d0::f378:e000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=216 validator_end=224 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_erigon]
teku-erigon-1 ansible_host=192.241.155.104 ipv6=2604:a880:400:d1:0:2:c4fa:d001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=224 validator_end=232 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-erigon-2 ansible_host=137.184.3.91 ipv6=2604:a880:4:1d0::f378:f000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=232 validator_end=240 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_geth]
teku-geth-1 ansible_host=159.223.98.19 ipv6=2604:a880:400:d1:0:2:c4fb:7001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=160 validator_end=168 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-geth-2 ansible_host=64.23.187.55 ipv6=2604:a880:4:1d0::f37a:5000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=168 validator_end=176 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_nethermind]
teku-nethermind-1 ansible_host=192.241.156.75 ipv6=2604:a880:400:d1:0:2:c4fa:4001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=176 validator_end=184 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-nethermind-2 ansible_host=143.198.233.76 ipv6=2604:a880:4:1d0::f379:8000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=184 validator_end=192 bandwidth=0 down_bandwidth=0 up_bandwidth=0

[teku_reth]
teku-reth-1 ansible_host=162.243.169.124 ipv6=2604:a880:400:d1:0:2:c4fb:4001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=192 validator_end=200 bandwidth=0 down_bandwidth=0 up_bandwidth=0
teku-reth-2 ansible_host=24.199.115.139 ipv6=2604:a880:4:1d0::f379:4000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=200 validator_end=208 bandwidth=0 down_bandwidth=0 up_bandwidth=0


# Consensus client groups

[lighthouse:children]
lighthouse_besu
lighthouse_erigon
lighthouse_geth
lighthouse_nethermind
lighthouse_reth
[lodestar:children]
lodestar_besu
lodestar_erigon
lodestar_geth
lodestar_nethermind
lodestar_reth
[nimbus:children]
nimbus_besu
nimbus_erigon
nimbus_geth
nimbus_nethermind
nimbus_reth
[teku:children]
teku_besu
teku_erigon
teku_geth
teku_nethermind
teku_reth
[prysm:children]
prysm_besu
prysm_erigon
prysm_geth
prysm_nethermind
prysm_reth
[grandine:children]
grandine_besu
grandine_erigon
grandine_geth
grandine_nethermind
grandine_reth

# Execution client groups

[besu:children]
grandine_besu
lighthouse_besu
lodestar_besu
nimbus_besu
prysm_besu
teku_besu
[ethereumjs:children]
[geth:children]
grandine_geth
lighthouse_geth
lodestar_geth
nimbus_geth
prysm_geth
teku_geth
[nethermind:children]
grandine_nethermind
lighthouse_nethermind
lodestar_nethermind
nimbus_nethermind
prysm_nethermind
teku_nethermind
[erigon:children]
grandine_erigon
lighthouse_erigon
lodestar_erigon
nimbus_erigon
prysm_erigon
teku_erigon
[reth:children]
grandine_reth
lighthouse_reth
lodestar_reth
nimbus_reth
prysm_reth
teku_reth
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine
lighthouse
lodestar
nimbus
prysm
teku

[execution_node:children]
besu
erigon
geth
nethermind
reth

[ethereum_node:children]
consensus_node
execution_node

; [chaosd:children]
; ethereum_node
