# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dugtrio.yaml.j2

dugtrio:
  fullnameOverride: dugtrio
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dugtrio
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: beacon.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  dugtrioFrontendTitle: "Dugtrio: fusaka-devnet-ssl-perf-peerdas-3"
  dugtrioProxyCount: 2
  dugtrioProxyBlockedPaths:
    - "^/teku/v[0-9]+/admin/.*"

  endpoints:
  # Rpc
  - url: http://prysm-geth-001:5052
    name: rpc-prysm-geth-001
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: bootnode-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-1.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-10.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-10
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-11.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-11
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-12.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-12
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-13.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-13
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-14.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-14
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-15.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-15
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-16.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-16
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-2.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-2
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-3.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-3
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-4.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-4
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-5.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-5
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-6.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-6
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-7.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-7
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-8.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-8
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-9.fusaka-devnet-ssl-perf-peerdas-3.yolkie.xyz
    name: prysm-geth-9
