xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-devnet-ssl-part-msg-2-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-devnet-ssl-part-msg-2"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://121be1d840189b7e2b3f32b754e263630f6a62a451a602d0838c13f79414d2aa14c16d656c2fe9cb1244f05c49e6a9251b13f04d655820b32b8bf8156c3d7bba@165.232.95.146:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
