# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: fusaka-devnet-ssl-perf-peerdas-1
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-perf-peerdas-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
    clientArgs:
      networks:
        fusaka-devnet-ssl-perf-peerdas-1:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://bbd790475866c009bfc840bf8c597a09ef3cab7f17ee5b69f596984b662f8c0fdeaac3e9fa0a820a6cec8850ca3a41ff4332fa0993118d81a5d9c3352ae978af@64.227.71.121:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz:443
              - --tx-pool-max-prioritized-by-type="BLOB=72"
              - --target-gas-limit=100000000
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://bbd790475866c009bfc840bf8c597a09ef3cab7f17ee5b69f596984b662f8c0fdeaac3e9fa0a820a6cec8850ca3a41ff4332fa0993118d81a5d9c3352ae978af@64.227.71.121:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --EthStats.Enabled=true
              - --EthStats.Name=localhost
              - --EthStats.Secret=5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd
              - --EthStats.Server=wss://ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Blocks.TargetBlockGasLimit=100000000
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7037582131
              - --syncmode=full
              - --bootnodes=enode://bbd790475866c009bfc840bf8c597a09ef3cab7f17ee5b69f596984b662f8c0fdeaac3e9fa0a820a6cec8850ca3a41ff4332fa0993118d81a5d9c3352ae978af@64.227.71.121:30303?discport=30303,enode://85fabd02edca279bbb16270539eac37b578cfe9db24f0956cf77098b7b77701ce77bbd974cc74b301519c07b971ae8349b348f94e24abd169e4b6496b0196bd6@161.35.13.98:30303?discport=30303,enode://1eda411b04a514d97836b46144aa96dc6a3aebd685c9e3117093a36189d22ec0895048787e14523bbb25ea8f2e48e5864acca230748dd8723cbe01880fab36f0@64.23.172.171:30303?discport=30303,enode://91e2975bcfa01b2599e253715aba5c4f61a2abcb3aa8e60984bd2a7f10aed2e36fc112bacb28ae1fdbee7a2112d9f5d12d33f0383bad02101b0c64f685c185b4@167.71.9.75:30303?discport=30303,enode://0ec7404e71f13aa52c6a30fd3d1304df08e8d6d4d1e6fb2853b3e40f394b759ec7552ad749bf972ae4176ece3c3f10d9863bcb94583bfcf05b13b5baa9f62c27@46.101.83.126:30303?discport=30303,enode://384a155d13898104b648ecc1fb99ea37751e3247dc23fad0944f7a5736767a2ff3aa1b064d7d0334935a940614ae47faa0393e0455889a7966f6223c24941722@208.68.39.234:30303?discport=30303,enode://ba57a07ed972b84e0934e43bc56beebec740ea2b84b9bdb12e6f98a463990fc3931c41c2d84b8c9293815fe5ef26a95183537495b218d186a618237ccdab3662@64.23.161.244:30303?discport=30303,enode://cdde25540fa0472fa93571c018a3de9815646487780f224c1f4fa8bbaf08c936b53543179ca6fd8653a8b4484a2a26eebbfb99d96bca5f89f56b526775cc9d27@192.81.211.236:30303?discport=30303,enode://a26822755464d76cf51e4ceaa24a3a07730f2a481e6e7f581c321d7f305129a9ff47496765844d15401edd2faace736f6d8dc0a6df6734a6c723a584a8a8dd6c@64.23.131.124:30303?discport=30303,enode://8ef3236a32ec747812a6264e328f81ccffeed4becc6df0c3e235440ec27a246541f626f04c6ce1c63f22b48a7c73ab54477909af7b33ab67338aeca6330a15eb@142.93.142.41:30303?discport=30303,enode://ea19235a2ccbc96f4f4fd6700bf290dae86448239e91cf89a01778667d986a2dac861f27727a84ad25b7363ce557393db237875b67df70957b570f641f67905f@46.101.85.22:30303?discport=30303,enode://d893cbef73e1eacc60b98ba5e78280dda78daed72cb3f8beedcd56d498abc316aefcec73f05b1b1ac8aba3a52a045aaa392cab821b292e1b73defc3a45704c7b@137.184.28.231:30303?discport=30303,enode://370b56ead8edb89bbbae8945fab31b9e834391c6310b06c5ea742ca3fb96129b8c9b9110405cd8bae5f820e5a885393bf5d2d0c0913cdd2759b25f42bd6b359a@143.198.50.118:30303?discport=30303,enode://e40709aab5da7441f2e29043332cf1e305dcddf57cfbc85d900ffdd3a6f137d3c1dd171c16e6ecc6f5b504b0f92a63b305a3c906c234e98b39bfaa11506971be@157.230.213.225:30303?discport=30303,enode://64d75707e92fa783202f42bfcfd09dcba463e89b9ea87f32b2dae8dcd4a17b68cea398241feb2dbca8591ca26993f19af929c1bd3d7b61514ca302c179eb16a8@134.199.218.212:30303?discport=30303,enode://41205ce6ef57e751ff46d5454c0d7653647a51bdf1e305635e6a97240c5df8b8311a4de30c57b2071afab155a472a3344135063247b477faddb5ba73b94d446b@134.209.201.220:30303?discport=30303,enode://13bbab33e190415c35fb99414472d679fb4d9b364d13a69e943ca8cbff40a9817610b540e3b3dcce8d999b1969ddf0e3fcfd35fc821ac4172d7ca169daee3e7a@134.209.21.233:30303?discport=30303
              - --miner.gaslimit=100000000
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --no-downloader
              - --networkid=7037582131
              - --db.size.limit=500GB
              - --bootnodes=enode://bbd790475866c009bfc840bf8c597a09ef3cab7f17ee5b69f596984b662f8c0fdeaac3e9fa0a820a6cec8850ca3a41ff4332fa0993118d81a5d9c3352ae978af@64.227.71.121:30303?discport=30303
              - --miner.gaslimit=100000000
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QCOhs4G_VsVa6UbRu-vClR1zh1e6nT-6b_nFh9HjdcqWFe2mq7IpwnA66HWcAGTkhNglG6Kf06ndW3gZvQHuciaGAZjIXJPogmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QO-MY7XqKXxuhnbSVJKgJMVdiw5doL-ZQqwQgHmKeqT8G41SCTS534YWXn5Y_B-cD-BMiEDrRv5FvVXGEpVm-zsHh2F0dG5ldHOIAAAAAAAMAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAguPvqKx8y9yBarN96FkFb_EWSsWZUyhhUgTPbsvusUsg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --logLevel=debug
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QCOhs4G_VsVa6UbRu-vClR1zh1e6nT-6b_nFh9HjdcqWFe2mq7IpwnA66HWcAGTkhNglG6Kf06ndW3gZvQHuciaGAZjIXJPogmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QO-MY7XqKXxuhnbSVJKgJMVdiw5doL-ZQqwQgHmKeqT8G41SCTS534YWXn5Y_B-cD-BMiEDrRv5FvVXGEpVm-zsHh2F0dG5ldHOIAAAAAAAMAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAguPvqKx8y9yBarN96FkFb_EWSsWZUyhhUgTPbsvusUsg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=debug
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QCOhs4G_VsVa6UbRu-vClR1zh1e6nT-6b_nFh9HjdcqWFe2mq7IpwnA66HWcAGTkhNglG6Kf06ndW3gZvQHuciaGAZjIXJPogmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QO-MY7XqKXxuhnbSVJKgJMVdiw5doL-ZQqwQgHmKeqT8G41SCTS534YWXn5Y_B-cD-BMiEDrRv5FvVXGEpVm-zsHh2F0dG5ldHOIAAAAAAAMAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAguPvqKx8y9yBarN96FkFb_EWSsWZUyhhUgTPbsvusUsg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QCOhs4G_VsVa6UbRu-vClR1zh1e6nT-6b_nFh9HjdcqWFe2mq7IpwnA66HWcAGTkhNglG6Kf06ndW3gZvQHuciaGAZjIXJPogmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QO-MY7XqKXxuhnbSVJKgJMVdiw5doL-ZQqwQgHmKeqT8G41SCTS534YWXn5Y_B-cD-BMiEDrRv5FvVXGEpVm-zsHh2F0dG5ldHOIAAAAAAAMAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAguPvqKx8y9yBarN96FkFb_EWSsWZUyhhUgTPbsvusUsg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --sync-light-client=false
              - --light-client-data-serve=false
              - --light-client-data-import-mode=none
              - --bootstrap-node=enr:-Iq4QCOhs4G_VsVa6UbRu-vClR1zh1e6nT-6b_nFh9HjdcqWFe2mq7IpwnA66HWcAGTkhNglG6Kf06ndW3gZvQHuciaGAZjIXJPogmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QO-MY7XqKXxuhnbSVJKgJMVdiw5doL-ZQqwQgHmKeqT8G41SCTS534YWXn5Y_B-cD-BMiEDrRv5FvVXGEpVm-zsHh2F0dG5ldHOIAAAAAAAMAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAguPvqKx8y9yBarN96FkFb_EWSsWZUyhhUgTPbsvusUsg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: master-9ce40d1
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31883
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: fusaka-devnet-ssl-perf-peerdas-1
      testnet: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_network: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/chainspec.json;
            GENESIS_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/genesis.json;
            BESU_GENESIS_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/besu.json;
            ENODES_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:master-9ce40d1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-perf-peerdas-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain
      tag: fusaka-devnet-3-cdd44dd
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32210
    podLabels:
      network: fusaka-devnet-ssl-perf-peerdas-1
      testnet: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_network: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
