# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: fusaka-devnet-ssl-perf-peerdas-1
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-perf-peerdas-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
    clientArgs:
      networks:
        fusaka-devnet-ssl-perf-peerdas-1:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://b5eb98828003337ade8ad379f2dae1e8365a648e7eb0ade181246bc4a5990b2460da3f5c9531a51a91854b5a84cfb1bf5babda3190c92d5f0ad5d088c7aa43f3@64.227.71.121:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz:443
              - --tx-pool-max-prioritized-by-type="BLOB=72"
              - --target-gas-limit=100000000
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://b5eb98828003337ade8ad379f2dae1e8365a648e7eb0ade181246bc4a5990b2460da3f5c9531a51a91854b5a84cfb1bf5babda3190c92d5f0ad5d088c7aa43f3@64.227.71.121:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --EthStats.Enabled=true
              - --EthStats.Name=localhost
              - --EthStats.Secret=5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd
              - --EthStats.Server=wss://ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Blocks.TargetBlockGasLimit=100000000
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7037582131
              - --syncmode=full
              - --bootnodes=enode://b5eb98828003337ade8ad379f2dae1e8365a648e7eb0ade181246bc4a5990b2460da3f5c9531a51a91854b5a84cfb1bf5babda3190c92d5f0ad5d088c7aa43f3@64.227.71.121:30303?discport=30303,enode://22fbe98397c43bb37b2240bcee674fefe54aa448068f67f1403b987aadc53dfc051eb52a00e5d4d533f0f738757df86184bf348d783d7cafd713188bf6b0ca36@161.35.13.98:30303?discport=30303,enode://9d633a45bfc860660cb8eb9c2cdc5118f606581419a719feede9c658d78b855700279297c305bf30a92a7f1c2a372694613972f7f1edc04a23dc912022f2c703@64.23.172.171:30303?discport=30303,enode://3eb61320eb73e4540c7fff1dde36621766d5a6fb6126c177fa9b6fa6fba8c888a3d2edb640c02884ca5537a550d02af59d9b13cee2798fed3e891bf59e0a2c9b@167.71.9.75:30303?discport=30303,enode://8745b9f71eb9d27fddb571b4bb4d68288c4befdc272487bf2d5a8ee6685e748d3a6d04e76d4977b7314d5493d98d6be8c7e56d9b63c06e29de9c28912f8fa85c@46.101.83.126:30303?discport=30303,enode://b4610680dea5af1e37aa764dbaf1c45ba27e4e6db702feccb0125a25380c5fa426126c0e258efa741931f4cbc1c08e7b71c952ddca9bf01debed9af42001edbe@208.68.39.234:30303?discport=30303,enode://e2076fb21c396a1a2236510528b3f53719450518defa043f2e33f465e886c82e88645f0b4f945dfb1451900e06a77cd8d4b66164e60c4474ff78a4abcfdaa9b9@64.23.161.244:30303?discport=30303,enode://10d12dec392fa1313120198e8d78953335f4b5f65ba5c9b3246ea9b49dcc5cd46005ffa0fc6f1645e738e69b0657517fc1d5c260219ab1e9fdcc9a4600d2b22e@137.184.28.231:30303?discport=30303,enode://c62c137f116fc6d4dcd4fd3eea0b5c6150bee3058f70a7ceccc01b2566fc11bbdb2a725706a2db5392c125332562fa5b447cffac6cc9e911116e7f78e311563d@143.198.50.118:30303?discport=30303,enode://d278f35898814df74d1ba99e1cb7a859bbe2cd0d05390d33192c999020f196399a0b43926e45db4e60a3c646b7d94369b341b561b5ba4de61eb747e06ee0f899@192.81.211.236:30303?discport=30303,enode://4b6445dc3352851fdb21a38f7478a314c2535990d5eeccc124743544c8b43808b7ef774428e24972f63995b6194cbf015f99ce51ae1799e9c89aa68f55480771@64.23.131.124:30303?discport=30303,enode://fd8d266cf09a977a648497b8aedaa1c604fcf17265657b4e86fc90cb8fe84890aa0fc727f4bda6d315e3109c380ca20db851c1e060e4727628a1a98260bab415@142.93.142.41:30303?discport=30303,enode://dc79f22975194044fe84cc1fd47444f4ffb86fef718567ebf20891a2488eab17292cb61a3917d6a80b6969c1298d54e6b21bed725e8cf709c59cea6a206c4c5f@46.101.85.22:30303?discport=30303,enode://35adf3c4a48eb8a8ac25d947cfbeb012626ed2b5f9c4137c05cf56ac9ad5b7d5674e3eff30005d74694aa33f091708ba7f0b7f46af1bfb77a6e028e2c3a718c0@157.230.213.225:30303?discport=30303,enode://7c4d9fb2ae5a8b835051c4c2c8a7dc36ef38ccddc30d774fc97a2eff995773197b1b2449bc2f6fcc5092cbd1cf5f4e2d7b97541a40d0b9bed5d5903f48f223ca@134.199.218.212:30303?discport=30303,enode://56eba248cdb6968701c9165404e8ee513bae17cc7b3275265c5592c716cc3c6b76a05f2069772393c441a65eb4e1b29534fcd49a4d5f7098963574d40bc9a31f@134.209.201.220:30303?discport=30303,enode://c6b1faa287e74995d420d46657ad492ec9cadd34482cb4990cede168497b3f06edf63754a9213e76de769e67631749ed9eee3cd470c240af26ccbf61fb0835ee@134.209.21.233:30303?discport=30303
              - --miner.gaslimit=100000000
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --no-downloader
              - --networkid=7037582131
              - --db.size.limit=500GB
              - --bootnodes=enode://b5eb98828003337ade8ad379f2dae1e8365a648e7eb0ade181246bc4a5990b2460da3f5c9531a51a91854b5a84cfb1bf5babda3190c92d5f0ad5d088c7aa43f3@64.227.71.121:30303?discport=30303
              - --miner.gaslimit=100000000
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QOxclqSX5kSFRhw0yD6sbE6u461JHSX__EI014DESktSJWsxI44DysItFXOihHzu_AL5IVe6ra6yp248XITmsSKGAZjOCw9MgmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QMikImS9TAERVIDwktwND1w3RdwzD5kismDgdFIahvjxYzFSQWrGP1z7sLm158RHQApkgqEVTUqhkK76zozjB3IHh2F0dG5ldHOIAAAAAAAYAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAkmZMC7q_9pYEZ68vgG-Qhzw5o_gV6arptfvLhfq2J2xg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --logLevel=debug
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QOxclqSX5kSFRhw0yD6sbE6u461JHSX__EI014DESktSJWsxI44DysItFXOihHzu_AL5IVe6ra6yp248XITmsSKGAZjOCw9MgmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QMikImS9TAERVIDwktwND1w3RdwzD5kismDgdFIahvjxYzFSQWrGP1z7sLm158RHQApkgqEVTUqhkK76zozjB3IHh2F0dG5ldHOIAAAAAAAYAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAkmZMC7q_9pYEZ68vgG-Qhzw5o_gV6arptfvLhfq2J2xg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=debug
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --rest-api-docs-enabled
              - --p2p-private-key-file=/tmp/remote_key1
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --bootstrap-node=enr:-Iq4QOxclqSX5kSFRhw0yD6sbE6u461JHSX__EI014DESktSJWsxI44DysItFXOihHzu_AL5IVe6ra6yp248XITmsSKGAZjOCw9MgmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QMikImS9TAERVIDwktwND1w3RdwzD5kismDgdFIahvjxYzFSQWrGP1z7sLm158RHQApkgqEVTUqhkK76zozjB3IHh2F0dG5ldHOIAAAAAAAYAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAkmZMC7q_9pYEZ68vgG-Qhzw5o_gV6arptfvLhfq2J2xg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QOxclqSX5kSFRhw0yD6sbE6u461JHSX__EI014DESktSJWsxI44DysItFXOihHzu_AL5IVe6ra6yp248XITmsSKGAZjOCw9MgmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QMikImS9TAERVIDwktwND1w3RdwzD5kismDgdFIahvjxYzFSQWrGP1z7sLm158RHQApkgqEVTUqhkK76zozjB3IHh2F0dG5ldHOIAAAAAAAYAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAkmZMC7q_9pYEZ68vgG-Qhzw5o_gV6arptfvLhfq2J2xg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --sync-light-client=false
              - --light-client-data-serve=false
              - --light-client-data-import-mode=none
              - --bootstrap-node=enr:-Iq4QOxclqSX5kSFRhw0yD6sbE6u461JHSX__EI014DESktSJWsxI44DysItFXOihHzu_AL5IVe6ra6yp248XITmsSKGAZjOCw9MgmlkgnY0gmlwhEDjR3mJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QMikImS9TAERVIDwktwND1w3RdwzD5kismDgdFIahvjxYzFSQWrGP1z7sLm158RHQApkgqEVTUqhkK76zozjB3IHh2F0dG5ldHOIAAAAAAAYAACDY2djBIRldGgykPjlYYdwMVSFAQAAAAAAAACCaWSCdjSCaXCEQONHeYNuZmSE7ogSsolzZWNwMjU2azGhAkmZMC7q_9pYEZ68vgG-Qhzw5o_gV6arptfvLhfq2J2xg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: master-9ce40d1
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31883
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: fusaka-devnet-ssl-perf-peerdas-1
      testnet: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_network: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/chainspec.json;
            GENESIS_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/genesis.json;
            BESU_GENESIS_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/besu.json;
            ENODES_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:master-9ce40d1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-perf-peerdas-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain
      tag: fusaka-devnet-3-cdd44dd
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32210
    podLabels:
      network: fusaka-devnet-ssl-perf-peerdas-1
      testnet: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_network: fusaka-devnet-ssl-perf-peerdas-1
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.fusaka-devnet-ssl-perf-peerdas-1.yolkie.xyz/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
