# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/assertoor.yaml.j2

assertoor:
  fullnameOverride: assertoor

  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/assertoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor.fusaka-devnet-ssl-chaos-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  ingressAdmin:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor-admin.fusaka-devnet-ssl-chaos-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  persistence:
    enabled: true

  endpoints:
    - name:  bootnode-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
    - name:  grandine-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.grandine-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.grandine-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
    - name:  lighthouse-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
    - name:  prysm-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.prysm-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
    - name:  teku-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.teku-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn.teku-geth-1.fusaka-devnet-ssl-chaos-1.yolkie.xyz

  validatorNamesInventory: https://config.fusaka-devnet-ssl-chaos-1.yolkie.xyz/api/v1/nodes/validator-ranges
  globalVariables:
    walletPrivkey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.assertoor_private_key}>"
    clientPairNames:
      - bootnode-1
      - grandine-geth-1
      - lighthouse-geth-1
      - prysm-geth-1
      - teku-geth-1
    validatorPairNames:
      - grandine-geth-1
      - lighthouse-geth-1
      - teku-geth-1

  assertoorTests: []