# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: http://geth-prysm-001:8545
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://rpc.bootnode-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.grandine-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.grandine-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.grandine-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.grandine-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.lighthouse-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.prysm-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.prysm-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.prysm-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.prysm-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.teku-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.teku-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.teku-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
- url: https://rpc.teku-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
