# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: http://prysm-geth-001:5052
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://bn.bootnode-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn.grandine-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-geth-1
  authGroup: pandaops
  priority: -1
- url: https://bn.grandine-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-geth-2
  authGroup: pandaops
  priority: -1
- url: https://bn.grandine-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-nethermind-1
  authGroup: pandaops
  priority: -1
- url: https://bn.grandine-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: grandine-nethermind-2
  authGroup: pandaops
  priority: -1
- url: https://bn.lighthouse-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn.lighthouse-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn.lighthouse-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn.lighthouse-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn.prysm-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-geth-2
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-nethermind-1
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: prysm-nethermind-2
  authGroup: pandaops
  priority: -1
- url: https://bn.teku-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-geth-1
  authGroup: pandaops
  priority: -1
- url: https://bn.teku-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-geth-2
  authGroup: pandaops
  priority: -1
- url: https://bn.teku-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-nethermind-1
  authGroup: pandaops
  priority: -1
- url: https://bn.teku-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
  name: teku-nethermind-2
  authGroup: pandaops
  priority: -1

