# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  name: fusaka-devnet-ssl-oplabs-1
  configPath: "https://config.fusaka-devnet-ssl-oplabs-1.yolkie.xyz/cl/config.yaml"
  validatorNamesInventory: "https://config.fusaka-devnet-ssl-oplabs-1.yolkie.xyz/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: FRONTEND_SHOW_VALIDATOR_SUMMARY
      value: "true"
    - name: API_ENABLED
      value: "true"
    - name: API_CORS_ORIGINS
      value: "*"
    - name: FRONTEND_SHOW_PEER_DAS_INFOS
      value: "true"
    - name: FRONTEND_ETH_EXPLORER_LINK
      value: "https://explorer.fusaka-devnet-ssl-oplabs-1.yolkie.xyz"
    - name: FRONTEND_PUBLIC_RPC_URL
      value: "https://rpc.fusaka-devnet-ssl-oplabs-1.yolkie.xyz"
    - name: FRONTEND_SHOW_SUBMIT_DEPOSIT
      value: "true"
    - name: FRONTEND_SHOW_SUBMIT_EL_REQUESTS
      value: "true"
    - name: EXECUTIONAPI_GENESIS_CONFIG
      value: "https://config.fusaka-devnet-ssl-oplabs-1.yolkie.xyz/el/genesis.json"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
    image:
      repository: bitnamilegacy/postgresql 
  mevRelays:
    - index: 0
      name: "Flashbots"
      url: "http://mev-relay-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz:9062/"

  authGroups:
    pandaops:
      credentials:
        username: ""
        password: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>"

  endpoints:
  # Rpc
  - url: http://prysm-geth-001:5052
    name: rpc-prysm-geth-001
    authGroup: pandaops
    archive: true
    priority: 1
  - url: https://bn.bootnode-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: bootnode-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.grandine-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-geth-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.grandine-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-geth-2
    authGroup: pandaops
    priority: -1
  - url: https://bn.grandine-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-nethermind-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.grandine-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-nethermind-2
    authGroup: pandaops
    priority: -1
  - url: https://bn.lighthouse-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-geth-1
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-geth-2
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-nethermind-1
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-nethermind-2
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.prysm-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-geth-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.prysm-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-geth-2
    authGroup: pandaops
    priority: -1
  - url: https://bn.prysm-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-nethermind-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.prysm-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-nethermind-2
    authGroup: pandaops
    priority: -1
  - url: https://bn.teku-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-geth-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.teku-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-geth-2
    authGroup: pandaops
    priority: -1
  - url: https://bn.teku-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-nethermind-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.teku-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-nethermind-2
    authGroup: pandaops
    priority: -1
  executionEndpoints:
  # Rpc
  - url: http://geth-prysm-001:8545
    name: rpc-prysm-geth-001
    authGroup: pandaops
    archive: true
    priority: 1
  - url: https://rpc.bootnode-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: bootnode-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.grandine-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-geth-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.grandine-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-geth-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.grandine-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-nethermind-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.grandine-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: grandine-nethermind-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-geth-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-geth-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-nethermind-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: lighthouse-nethermind-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.prysm-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-geth-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.prysm-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-geth-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.prysm-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-nethermind-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.prysm-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: prysm-nethermind-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.teku-geth-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-geth-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.teku-geth-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-geth-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.teku-nethermind-1.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-nethermind-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.teku-nethermind-2.fusaka-devnet-ssl-oplabs-1.yolkie.xyz
    name: teku-nethermind-2
    authGroup: pandaops
    priority: -1
    archive: false
