# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: http://prysm-geth-001:5052
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://bn.bootnode-1.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-1.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-1
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-10.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-10
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-11.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-11
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-12.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-12
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-2.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-2
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-3.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-3
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-4.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-4
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-5.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-5
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-6.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-6
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-7.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-7
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-8.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-8
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-full-9.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-full-9
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-super-1.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-super-1
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-super-2.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-super-2
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-super-3.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-super-3
  authGroup: pandaops
  priority: -1
- url: https://bn.prysm-geth-super-4.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
  name: prysm-geth-super-4
  authGroup: pandaops
  priority: -1

