localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-teku-2

[bootnode]
bootnode-1 ansible_host=68.183.2.180 ipv6=2a03:b0c0:2:f0::bb9f:d001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True 

[teku_geth]
teku-geth-1 ansible_host=167.172.110.170 ipv6=2a03:b0c0:3:f0:0:1:6f5:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0
teku-geth-10 ansible_host=165.232.118.240 ipv6=2a03:b0c0:3:f0:0:1:6f8:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0
teku-geth-11 ansible_host=46.101.162.248 ipv6=2a03:b0c0:3:f0:0:1:6f5:f000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=80 validator_end=88 bandwidth=0
teku-geth-12 ansible_host=46.101.232.174 ipv6=2a03:b0c0:3:f0:0:1:6f8:d000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0
teku-geth-13 ansible_host=164.92.200.189 ipv6=2a03:b0c0:3:f0:0:1:6f8:1000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=96 validator_end=104 bandwidth=0
teku-geth-14 ansible_host=164.90.217.144 ipv6=2a03:b0c0:3:f0:0:1:6f6:1000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0
teku-geth-15 ansible_host=134.122.94.237 ipv6=2a03:b0c0:3:f0:0:1:6f8:2000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=112 validator_end=120 bandwidth=0
teku-geth-16 ansible_host=159.223.22.99 ipv6=2a03:b0c0:3:f0:0:1:6f7:5000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=120 validator_end=128 bandwidth=0
teku-geth-17 ansible_host=165.227.132.9 ipv6=2a03:b0c0:3:f0:0:1:6f7:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=128 validator_end=136 bandwidth=0
teku-geth-18 ansible_host=165.232.79.164 ipv6=2a03:b0c0:3:f0:0:1:6f8:3000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=136 validator_end=144 bandwidth=0
teku-geth-19 ansible_host=159.65.115.123 ipv6=2a03:b0c0:3:f0:0:1:6f7:b000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=144 validator_end=152 bandwidth=0
teku-geth-2 ansible_host=64.227.124.254 ipv6=2a03:b0c0:3:f0:0:1:6f5:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=8 validator_end=16 bandwidth=0
teku-geth-20 ansible_host=134.209.227.184 ipv6=2a03:b0c0:3:f0:0:1:6f5:e000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=152 validator_end=160 bandwidth=0
teku-geth-21 ansible_host=207.154.235.149 ipv6=2a03:b0c0:3:f0:0:1:6f7:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=160 validator_end=168 bandwidth=0
teku-geth-22 ansible_host=134.122.80.166 ipv6=2a03:b0c0:3:f0:0:1:6f7:f000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=168 validator_end=176 bandwidth=0
teku-geth-23 ansible_host=167.172.105.26 ipv6=2a03:b0c0:3:f0:0:1:6f8:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=176 validator_end=184 bandwidth=0
teku-geth-24 ansible_host=64.226.120.52 ipv6=2a03:b0c0:3:f0:0:1:6f5:b000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=184 validator_end=192 bandwidth=0
teku-geth-25 ansible_host=167.71.42.191 ipv6=2a03:b0c0:3:f0:0:1:6f8:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=192 validator_end=200 bandwidth=0
teku-geth-26 ansible_host=207.154.204.89 ipv6=2a03:b0c0:3:f0:0:1:6f7:2000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=200 validator_end=208 bandwidth=0
teku-geth-27 ansible_host=159.89.16.232 ipv6=2a03:b0c0:3:f0:0:1:6f5:d000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=208 validator_end=216 bandwidth=0
teku-geth-28 ansible_host=142.93.101.20 ipv6=2a03:b0c0:3:f0:0:1:6f8:b000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=216 validator_end=224 bandwidth=0
teku-geth-29 ansible_host=164.92.229.64 ipv6=2a03:b0c0:3:f0:0:1:6f5:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=224 validator_end=232 bandwidth=0
teku-geth-3 ansible_host=64.226.83.16 ipv6=2a03:b0c0:3:f0:0:1:6f6:e000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=16 validator_end=24 bandwidth=0
teku-geth-30 ansible_host=64.225.110.248 ipv6=2a03:b0c0:3:f0:0:1:6f6:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=232 validator_end=240 bandwidth=0
teku-geth-31 ansible_host=64.227.126.92 ipv6=2a03:b0c0:3:f0:0:1:6f5:c000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=240 validator_end=248 bandwidth=0
teku-geth-32 ansible_host=164.92.242.29 ipv6=2a03:b0c0:3:f0:0:1:6f6:c000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=248 validator_end=256 bandwidth=0
teku-geth-33 ansible_host=64.226.99.112 ipv6=2a03:b0c0:3:f0:0:1:6f7:0 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=256 validator_end=264 bandwidth=0
teku-geth-34 ansible_host=164.90.234.18 ipv6=2a03:b0c0:3:f0:0:1:6f6:3000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=264 validator_end=272 bandwidth=0
teku-geth-35 ansible_host=167.71.41.46 ipv6=2a03:b0c0:3:f0:0:1:6f6:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=272 validator_end=280 bandwidth=0
teku-geth-36 ansible_host=159.89.3.160 ipv6=2a03:b0c0:3:f0:0:1:6f7:d000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=280 validator_end=288 bandwidth=0
teku-geth-37 ansible_host=159.223.29.254 ipv6=2a03:b0c0:3:f0:0:1:6f7:1000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=288 validator_end=296 bandwidth=0
teku-geth-38 ansible_host=164.92.141.134 ipv6=2a03:b0c0:3:f0:0:1:6f6:b000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=296 validator_end=304 bandwidth=0
teku-geth-39 ansible_host=165.227.146.4 ipv6=2a03:b0c0:3:f0:0:1:6f7:4000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=304 validator_end=312 bandwidth=0
teku-geth-4 ansible_host=142.93.173.125 ipv6=2a03:b0c0:3:f0:0:1:6f8:4000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=24 validator_end=32 bandwidth=0
teku-geth-40 ansible_host=46.101.227.17 ipv6=2a03:b0c0:3:f0:0:1:6f6:2000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=312 validator_end=320 bandwidth=0
teku-geth-41 ansible_host=64.227.115.253 ipv6=2a03:b0c0:3:f0:0:1:6f8:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=320 validator_end=328 bandwidth=0
teku-geth-42 ansible_host=164.90.221.64 ipv6=2a03:b0c0:3:f0:0:1:6f6:d000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=328 validator_end=336 bandwidth=0
teku-geth-43 ansible_host=164.92.134.120 ipv6=2a03:b0c0:3:f0:0:1:6f6:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=336 validator_end=344 bandwidth=0
teku-geth-44 ansible_host=138.68.105.47 ipv6=2a03:b0c0:3:f0:0:1:6f7:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=344 validator_end=352 bandwidth=0
teku-geth-45 ansible_host=46.101.97.105 ipv6=2a03:b0c0:3:f0:0:1:6f8:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=352 validator_end=360 bandwidth=0
teku-geth-46 ansible_host=164.90.222.147 ipv6=2a03:b0c0:3:f0:0:1:6f7:3000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=360 validator_end=368 bandwidth=0
teku-geth-47 ansible_host=157.230.108.83 ipv6=2a03:b0c0:3:f0:0:1:6f6:5000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=368 validator_end=376 bandwidth=0
teku-geth-48 ansible_host=138.68.75.2 ipv6=2a03:b0c0:3:f0:0:1:6f6:0 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=376 validator_end=384 bandwidth=0
teku-geth-49 ansible_host=207.154.233.221 ipv6=2a03:b0c0:3:f0:0:1:6f7:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=384 validator_end=392 bandwidth=0
teku-geth-5 ansible_host=207.154.249.222 ipv6=2a03:b0c0:3:f0:0:1:6f8:5000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=32 validator_end=40 bandwidth=0
teku-geth-50 ansible_host=167.71.36.63 ipv6=2a03:b0c0:3:f0:0:1:6f6:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=392 validator_end=400 bandwidth=0
teku-geth-6 ansible_host=165.232.68.5 ipv6=2a03:b0c0:3:f0:0:1:6f8:c000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=40 validator_end=48 bandwidth=0
teku-geth-7 ansible_host=134.209.237.74 ipv6=2a03:b0c0:3:f0:0:1:6f7:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=48 validator_end=56 bandwidth=0
teku-geth-8 ansible_host=46.101.100.183 ipv6=2a03:b0c0:3:f0:0:1:6f6:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0
teku-geth-9 ansible_host=164.92.242.37 ipv6=2a03:b0c0:3:f0:0:1:6f5:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=64 validator_end=72 bandwidth=0


# Consensus client groups

[lighthouse:children]
[lodestar:children]
[nimbus:children]
[teku:children]
teku_geth
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
teku_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]

# Global groups

[consensus_node:children]
teku

[execution_node:children]
geth

[ethereum_node:children]
consensus_node
execution_node

[spamoor:children]
bootnode
