# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/syncoor-web.yaml.j2

syncoor-web:
  fullnameOverride: syncoor-web
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.ethquokkaops.io/dh/ethpandaops/syncoor-web
            tag: master
            pullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 128Mi

  configMaps:
    config:
      enabled: true
      data:
        config.json: |
          {
            "directories": [
              {
                "name": "cl-full-checkpoint-sync",
                "displayName": "CL Fullnode + CL Checkpoint Sync",
                "url": "https://syncoor-data.yolkie.xyz/devnets/fusaka-devnet-ssl-part-msg-2"
              },
              {
                "name": "cl-super-checkpoint-sync",
                "displayName": "CL Supernode + CL Checkpoint Sync",
                "url": "https://syncoor-data.yolkie.xyz/devnets/fusaka-devnet-ssl-part-msg-2-clsupernode"
              },
              {
                "name": "cl-full-genesis-sync",
                "displayName": "CL Fullnode + CL Genesis Sync",
                "url": "https://syncoor-data.yolkie.xyz/devnets/fusaka-devnet-ssl-part-msg-2-clcheckpointsyncdisabled"
              },
              {
                "name": "cl-super-genesis-sync",
                "displayName": "CL Supernode + CL Genesis Sync",
                "url": "https://syncoor-data.yolkie.xyz/devnets/fusaka-devnet-ssl-part-msg-2-clsupernode-clcheckpointsyncdisabled"
              }
            ],
            "syncoorApiEndpoints": [
              {
                "name": "Syncoor",
                "url": "https://syncoor-api.fusaka-devnet-ssl-part-msg-2.yolkie.xyz"
              }
            ]
          }

  ingress:
    main:
      className: ingress-nginx-public
      enabled: true
      hosts:
        - host: syncoor.fusaka-devnet-ssl-part-msg-2.yolkie.xyz
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
