secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:XUvcLTUhyLIz2r+riick6nV/qQ3L9sTVtsNeeWfoGunWRjw7VkM=,iv:bozOJ7qWiv1rpojlNPXW9ArCgXhnwwRgmb5dLV/RC/U=,tag:LEiMqW1IHzXa+GorqFYdfA==,type:str]
    username: ENC[AES256_GCM,data:PkT7WUik,iv:BLYFoYxUVjaLf/ZDVmb56lP2JC0ekoKplhvJ8QBpEbw=,tag:4ZL4R4qF27xdmIh7uth//A==,type:str]
    password: ENC[AES256_GCM,data:5KXIFghfnhkcR3RP,iv:1QCdjvAdwpbI4Yr0UoaTj+853QOfzDEZIgAdoqsI2pc=,tag:l2zCfNgaxnKA4Fc6zJ5zOg==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:2tQN4kEMf/yjl3suLzyXGqfkEWxXCbMUIQ==,iv:NSVVwTRxvaZlQ8B2IMsbMKOfvIPj2sIzTj9AIIXgykw=,tag:T9XSGlcUOpeYrZkm4XY9oA==,type:str]
    username: ENC[AES256_GCM,data:EV57CnWc,iv:1qeRNEvy53Noh13okn4ssh14faUhG0nthRjA291R86A=,tag:l6fVzV3oAM14PomzK9Rvow==,type:str]
    password: ENC[AES256_GCM,data:tb/L0X06TtGhiJG2,iv:5nKg4KAlLbU9vL+LOP1pqb9QAmBuMq+/IjYtKNFOP1E=,tag:nn4bcwvQSOJiZ1TwtCsoJA==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:G0x52Gk9gYr+TXLnLAEhpc2n7EhEO59xCQDnAI9RFIroSCsnAISf9XGA7Pxn3WgIRKIfSDbuqibIjc5G71UAjg==,iv:GK+5KxVxq082KavrylgvcjRGxgYDhA2QDxigtBiCkvU=,tag:Lc4tAY3HsQ3q0DywqRk2uw==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:itVCPIRodDl7XZKbkICONoWW/pBIrg==,iv:UoB5k7cNpvf3JiXiA14GeV1ww4UobpjmsjHtJQF8fb0=,tag:GHdpWlD03fPwjwIZ8Zy0VQ==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:aLRXvwFh2hxHGMnzXGRkrDL624UDxo0+HEDX56XTl0B6k8oJCKpgh2wzaAvEvThEX+sTThExu7Sq74r3yVz4Rzm4GkFGxyNKPoKkyGi+wc9DvjLGGQY=,iv:WEQSH0KDkKY8Q9U5J5j1K5plnm6klyTDhySlHUI/faY=,tag:Wi7ILgpsoS0mGTi4ogAVNQ==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:WEJEADfzsrbI,iv:SMdxx8AevsqqZKviudSODSfIlKStV4XndV/ZsBkQkI8=,tag:a1LcWJB5+fPpGk9ziYUrlg==,type:str]
    password: ENC[AES256_GCM,data:7Ch8OcZY3LbSfQjX,iv:5d/iWxy6uH2BX5FJZo8s9LVFdEf4ec/z2ZsaaEic2nM=,tag:s0rhrfhq5lN/LJIyzL51DQ==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:qMSSeok6t2Q3,iv:SPTlr8hJMeLZCHtAGafVA55s057mJCgopbpHEmFiuv8=,tag:1+7/OVqxiKleYPkt0SkYgw==,type:str]
    password: ENC[AES256_GCM,data:3m6Bs+UETNWkgE9a,iv:TW6UaiJ5FiZn6cNy0prxW3kzfnYRBJdny2AlE7Vdf1s=,tag:kA+N0YalhQVp/U5pPys8kA==,type:str]
    server_address: ENC[AES256_GCM,data:K30S883yiGu/hbupZbrPE98t,iv:ICL3d+hDC3WVVlNQvy88dFrde8quOKMuQyJkG6/1gWo=,tag:6onDMSmcmxFZCXhi4Gbu6w==,type:str]
secret_ethstats: ENC[AES256_GCM,data:H/anmugRwlt6V4tVTUgi/k4H8c0jq+LDtMEcpNWRdaW18e3Mym5a/XEH8bEQaoav6vd+TxyC+XuPH7LjR23aUw==,iv:h5l7g8DTrp37si9e/JT3DvHEfoI55j9KyGT00ibqgzg=,tag:0j5iq8ozyshrGY5J3G0hBg==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:DICDQAB7RXIUE2rZS40iEn3bQ5lUdB7HuR/D0qvMqZ5zoUijjACyXPjbIClV3PFrk/kfkL8EeNfNUIHqB69D+3HQ4of/4pl8fwyzjPmc0joX/fNfbqs4wf+wJNN7XyxDCqLa09I3BgGTvsQ+rdM3i/3H/9O4MkgPqkaf4cEYCnQmoaZ9XQDOgYG/2F6ReAxzoH1a,iv:PmyjWwuOv7hXQulU8NV9/ZedrqztpXKzi4XZvUdqmtE=,tag:dAOf7oZTV/07q6n0YlYY+g==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:gn/EbETNDfJ/sYZWq77gV5LFtzY3u1ZdJ0fvy7f7Qvd4lEj1PHH7hUhsY2N3hFIrEOKEnt6Bg87IOv/z4Ik+F3FffzmmFopLOzHpwPnSsgTJBl/X6zfFasd7sOe4+306bFCGfOZuxY43MsbdzIBjty4m2T8/OvuR1kme7geOVjn2xfvEgHuwmgdadfwVsSzC3OLH48o=,iv:kJN6+Hgu3fZdz/TdO3Xuafy/Cti3eROXjSORhgGPJgI=,tag:RpZsEPS66VbKJYPsA6K7YQ==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:jS9+1HRM1OGDPP/n+fklJt8biPjeBXnpDu2z3P4fy/xiahDkfPBYOaUNopfR95qqNwTmeKkJh42ylgx7eqqUgQ==,iv:2B2yVyH07yn3/MYUJ7uVsHkyDXLoVlOXrNnKwWY4xMk=,tag:yw/PbDBpEJ/6jsS+kH5yNQ==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:y/kImoyc/CGLrW/H13QR8RNoBrz0lnO3J+cpkpMS3bF1qstAKToUMYgI4N7l1dBCxEBQK/66fo9II9bbtT4gsQ==,iv:U5TmuDgvLAgYJWzdp3U627rve3s5x6+vfVOoxxXPgZg=,tag:I6oqkQjZhuvU+ZjIMMms9g==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:N0DeYt9jWP5G3jjXIIa2xoyYHaoQ9H8eQIbLRqMqRdW29c5EGl0QLN0KgRI0t7wf5Ul4Q/toifMgBMXyuVwRxA==,iv:yqo/aLbPHQTRIBRc0NGXoJKfIdRl5yPAA+BMd9+rq48=,tag:oYeGGg/ACGY0WIHCG/6BgA==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:yMaL8EIVbyC9v3z1oi3Uc9rFHYDXQ71tDGAvMRtfHjp8WKrubQ4+ZMraEwdga6RgGvxdqOl01OoKaEiKlWj50g==,iv:KzaVF50hcOFYLaxBiwVe5bYk+xoXhCKWSk/IoHD8ZgU=,tag:VzO6k7F1KKjsozqgM+uRqQ==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:hty0sOgRQbXz,iv:5x71shjNDdh2e2G1VQYF/iyJZ4XrQBdUgt5ZTdCPhPI=,tag:oAuur0h6/kekgUz1X50Q4A==,type:str]
goomy_private_key: ENC[AES256_GCM,data:GF5HIrLuZVR8PYS7cVKwfNC4KWQ5qxcfBPIh9PknveMWpYUdFFvhjoFIEpAj6CH13VS1OZTQEgK+rITXXLa5ww==,iv:xdu6ejV3WDO9TTpSJcL3NCcb/x+DGe12BXz/NpTh3XQ=,tag:Ovesoe8xXnyxMcd+mcwCUg==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:OgXak4XoM+9ryWLts+xcBtUUGcqcdBtuC+wJFqmunFhrXy/XRp0ZWvOzqkvlnkQaTnVJBSaxFAlzxqmBSATu1A==,iv:EROXAuXh84hB5A9sYYL12hFdl2CLO+eFB11fDI7Zcxg=,tag:aPopqk8t8+HlTv8dqX3PDA==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:6tVTM4KDw1qT,iv:phERDfI2TlN5k8wnJIH2RJJkIbG2vDw/p3lnG/7K77A=,tag:hb2C6LJBGPTdvMkdUHexUw==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:RqPf6dZaYk6VfBMY,iv:wLuWcvl+NVKESdktaOsFabj/YayaZ4R2ulSETVNg9yI=,tag:ZxdeqKQGM7oZrJ8VI2MLaQ==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:KinhpFFK2V2cOFNaBOXSPFsRBgz1gysYZYsJU6xU6hQAoaOr6MdeLQ6UWiK24gKwL/QFHY/Cl5dpHW2IzYd9yg==,iv:PZpJbyCU2svim1T+bKeo35CSjBJl8cXre1+Dh2bO8eU=,tag:NY9pHExesImNSvCCV8CZ5w==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:A2Lh5khyLnrD5u+A,iv:yoreM4H9LHy1wLXaN7gibiHHbR7WZBdAs0M5LPbgWnE=,tag:noV/rb6uqqbp64FSUWVMOA==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:1PHy10OIMSQu,iv:7FUx2qYXg99IkzAc2YcoyambhGFQOlbjLhxk4eFsp4A=,tag:4fvXBjP4mSajCdJt5hOS/w==,type:str]
sops:
    lastmodified: "2025-06-23T16:42:19Z"
    mac: ENC[AES256_GCM,data:huYg1JfgbtICJzqOlkO2qDAWQ3UqGbEU+Lsi0r8K3WZtNgc8GVutAEt24pAooqy4ko0f0AiTzD2H2vPxKUjjNmX9W9cdDdY/l2Tk6sS55nUUsUDN55M3hBqCjEMY6oarErWZLf0gCuhc18hgKW9ywZkpa0/YnTlZGVieE0z5xhc=,iv:xjQxynPTK4sJGbfLiHNcH3zf8LN2LxfuFhpAnnf4QEk=,tag:w6BL+2zQT6Gtxre511wJvg==,type:str]
    pgp:
        - created_at: "2025-06-23T16:42:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQARAAxaMpvSdny1dFwoUwWkfoxfZJ1ZyS4qhLu1KDBy1uhdl/
            vPtS96enPLJ2PB56BzFY0QMBSJHoIr0wYk5vKPnYZChEa4M0KE3EYJ4IkGI5ixso
            BNxoNBg78hnklqUfArbz7kXFE5RcBQd+XE61OD9X3d+ChPat00/3PpHudfack/Pq
            MGSpXO2fTkIahixEBmShWgNCeVTp4hR7IF6KGv0oNqjeGxX5TFUqo67oFpuerVBH
            mAnne/goXT9d1b+ot3a39FYXyQZGhh1QdkDmyAKd1I5f2j2ZD7igaRZC64cGQw53
            PaS/QD+L9xPQ7M+gEikr7asrXPNjqEHA004WrFQtJRQX6vgO7HY5De5rcns9MJDg
            4UHxf/rdr7HuOmsG+eP8QZgCW7t53SiMojRcma6B2/vSHhNJY13cs3SXHcNb1cuH
            OJxAMS7SkCtE4j6M5Q/n37E+M3XKfb08dhiz2SE2KCB5Khj5/qVl6b7NlTT5z75Y
            +9S7/5Blk3nIerxnmlURCb6kfPyPS+fIoOJnOnlq1EGndpiI3fm21XMP7/dKf6l2
            PglT/ga9aMnUof6l2QSRGhX466VeiXcECK8tPA0tfrup088EhkoSBmXxk6DudWKa
            ZIqvETkBxdVTdGn3D1xKkbdUmXrL6geTcK8+ozAoXlVGKgxwlv6YcoFCJFYwJTXU
            aAEJAhBbQwX7eIBMpLCqm8PAc6msEALUeMXT+/AHEs2fjZojgqC4C7wJbRtbUfqX
            ONst2d+FqMP048SfWgSpOrO5cE2UW8DeSNBBaJyBNIRREr7ZeasGRgrEh/l4JY/a
            BLbuVZQrVPb4
            =qIQZ
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
