# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: fusaka-devnet-ssl-7
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-7: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-7.yolkie.xyz
    clientArgs:
      networks:
        fusaka-devnet-ssl-7:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://ffb9ee9820001b301b9467f64c9f0ca5800d41ef4a69a0723441f7feb6c1ef29de565e792df7e96c1a8f87c99fb017081d940583822f9f8ea228a60fbc3c1e9b@157.245.69.192:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-7.yolkie.xyz:443
              - --tx-pool-max-prioritized-by-type="BLOB=72"
              - --target-gas-limit=45000000
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://ffb9ee9820001b301b9467f64c9f0ca5800d41ef4a69a0723441f7feb6c1ef29de565e792df7e96c1a8f87c99fb017081d940583822f9f8ea228a60fbc3c1e9b@157.245.69.192:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --EthStats.Enabled=true
              - --EthStats.Name=localhost
              - --EthStats.Secret=5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd
              - --EthStats.Server=wss://ethstats.fusaka-devnet-ssl-7.yolkie.xyz/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Blocks.TargetBlockGasLimit=45000000
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7017928245
              - --syncmode=full
              - --bootnodes=enode://ffb9ee9820001b301b9467f64c9f0ca5800d41ef4a69a0723441f7feb6c1ef29de565e792df7e96c1a8f87c99fb017081d940583822f9f8ea228a60fbc3c1e9b@157.245.69.192:30303?discport=30303,enode://34a20de360be7ef5f0a172b16dcb04faee93eaf9618590ac6ea2fdd4b7e2f933ea8fbe8b0631e1c57cd0bc3a58a8199eefaa2a82f51991ecb32661b1daf6b425@142.93.201.115:30303?discport=30303,enode://a7ace4bb0935c92dc8a8ff66521f97ae84477d3447707f70b768cddd4d7e167edb0215b6ad2a6d81c5c068a2e381a23f645bedd920b6a683adee919a1d8fe54b@159.223.205.212:30303?discport=30303,enode://045e283bdb1ee973bc9f0fc767fb463a5ba26bdfec7e6781f38ea3da573fdb38f77fd2619f690e1aa5d7befe66f7152a84fff18e3ff021b9e94f99222a08d1aa@159.223.228.109:30303?discport=30303,enode://d8b291567ebf9905863837fdb1a1f5e4bde8705c2becb84508c1112f573aba41156c6e79c1a737e028bb213b658beb06774632ade3ee8632e1c4abbf3fbeda25@159.65.90.34:30303?discport=30303,enode://a706e3afe8b0a9f7b25b331ea9ade764ca442a5a1ade64cc9bbf8c9db2eefbf4e1b16bf07b1d421717006370ae7c665036b1751a448a174c33f64f9093e01939@159.203.181.77:30303?discport=30303,enode://83f7f964bdcf8318f16d307582703c054d8f15ea354269ecfab5968752efe24c1110a313cdc09eaefd3c5bde360dc8630d3e1c1d15d4e0e250f28ce4fe01f450@164.92.76.43:30303?discport=30303,enode://00777880037c2d7c87861488c462ee3108146ba9e98c932fede894125801786dc41d8c8f401e6006628420fe909e63b366012d513576df37ef8577c690ddec96@142.93.231.46:30303?discport=30303,enode://05b4f677e2a2299a9389f1f6a8ccefcb86704069d74527b3e464c0afc79cf06185845fea95f6fcf5eaa477d45d287aac3ddd34689eb0bbf2594a144b63b7ed4c@178.128.169.33:30303?discport=30303,enode://2a45854f48f108a8729d60df925f69dc3df1425af2426b1e6859762c5314df1400a815a5bdec722c2eb41414e13e798168b848609fa64787fe298981f4a7593b@134.122.85.88:30303?discport=30303,enode://08cc9a99fc5d2617d5bb558bbd585aaf0a3b9c1928fc2a63340c13d2af93e8ed5caeb637e737e452ef4069010f7ddeeae387524d67948a73f129486d501d3e45@167.99.189.126:30303?discport=30303,enode://dd68413875efbd984b22ce47b7288b1ae14100595b3ad2d0d66687e9bb82497d2793d93e4927035598c3deca65c9e7e78fa1f11872528be1650daea5197d053d@139.59.18.253:30303?discport=30303,enode://cb0cd2e07d03da1dcbd0eda94f6a87377e59621fb4bdd3db64fad4d05dac393dde6ae955680690a73daf720bcbf58b3c8120219a27d4266799efd582a87bfe83@134.199.167.191:30303?discport=30303,enode://21b3cfff7d83cf9d4e2f12a6c8db9456992be1d4eb28094aaf45eeeae1918618956fc1cbfa50984166df30445b2a1600d346362adfffd3cc62635424ff589588@159.223.190.159:30303?discport=30303,enode://5d8b2be416244d1d5038dc425d8715fd41f6b2cef2a8911522f951175fbbd8a1cba751937c3c42b7b0f277b0186c720b57eb38d4efb6eb4ab62c675bea795726@147.182.206.102:30303?discport=30303,enode://72ed1eb2c7ccd80b6c58d84406a34029d88d0286939a0ef65af28497f4665f2c792ad496763d58713ebeff52eddc79f2211a8a3541119fa657d58ad4eb15a5ef@142.93.134.48:30303?discport=30303,enode://97f0f9a3f3b9f1734af77ab63e9c1f908d6f25ed4f50e00033e4809621f9344ef5f4642620ef0a4c080c5fd26989bb47d5282925b2ad40558966ca51521a238f@143.110.171.208:30303?discport=30303
              - --miner.gaslimit=45000000
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-7.yolkie.xyz
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --no-downloader
              - --networkid=7017928245
              - --db.size.limit=500GB
              - --bootnodes=enode://ffb9ee9820001b301b9467f64c9f0ca5800d41ef4a69a0723441f7feb6c1ef29de565e792df7e96c1a8f87c99fb017081d940583822f9f8ea228a60fbc3c1e9b@157.245.69.192:30303?discport=30303
              - --miner.gaslimit=45000000
              - --ethstats=localhost:5712f4ec14f9c0923308087b63f8fe638f3eb39813be25836f6b6e10716842bd@ethstats.fusaka-devnet-ssl-7.yolkie.xyz
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QFnW7-2NjL_VVFy0WaXOsOgVNqXQUlk6fj8H46AU9BeKe5blTKURg0oyQVwWxAilPCsT6ZtN5Y1HoaLSpLU0MsGGAZg0DC6ugmlkgnY0gmlwhJ31RcCJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QGsGQCaPfqCZ6IWIqxwvygLIC5XxM_ve9mMR2RAC2wRJegncAG9eJ7Lo6zJiTJXlrlTLTj9PIG2nZfIRR2S_PgkHh2F0dG5ldHOIAAAAGAAAAACDY2djBIRldGgykOG_GOFwkZMFAQAAAAAAAACCaWSCdjSCaXCEnfVFwINuZmSEuuYW7IlzZWNwMjU2azGhAmMU8wcXuBtyz8cm4Dv-YYPBQFNTnu8VAF_M0D7gxG9vg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --logLevel=debug
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QFnW7-2NjL_VVFy0WaXOsOgVNqXQUlk6fj8H46AU9BeKe5blTKURg0oyQVwWxAilPCsT6ZtN5Y1HoaLSpLU0MsGGAZg0DC6ugmlkgnY0gmlwhJ31RcCJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QGsGQCaPfqCZ6IWIqxwvygLIC5XxM_ve9mMR2RAC2wRJegncAG9eJ7Lo6zJiTJXlrlTLTj9PIG2nZfIRR2S_PgkHh2F0dG5ldHOIAAAAGAAAAACDY2djBIRldGgykOG_GOFwkZMFAQAAAAAAAACCaWSCdjSCaXCEnfVFwINuZmSEuuYW7IlzZWNwMjU2azGhAmMU8wcXuBtyz8cm4Dv-YYPBQFNTnu8VAF_M0D7gxG9vg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
              - --p2p-private-key-file=/tmp/remote_key
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QFnW7-2NjL_VVFy0WaXOsOgVNqXQUlk6fj8H46AU9BeKe5blTKURg0oyQVwWxAilPCsT6ZtN5Y1HoaLSpLU0MsGGAZg0DC6ugmlkgnY0gmlwhJ31RcCJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QGsGQCaPfqCZ6IWIqxwvygLIC5XxM_ve9mMR2RAC2wRJegncAG9eJ7Lo6zJiTJXlrlTLTj9PIG2nZfIRR2S_PgkHh2F0dG5ldHOIAAAAGAAAAACDY2djBIRldGgykOG_GOFwkZMFAQAAAAAAAACCaWSCdjSCaXCEnfVFwINuZmSEuuYW7IlzZWNwMjU2azGhAmMU8wcXuBtyz8cm4Dv-YYPBQFNTnu8VAF_M0D7gxG9vg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QFnW7-2NjL_VVFy0WaXOsOgVNqXQUlk6fj8H46AU9BeKe5blTKURg0oyQVwWxAilPCsT6ZtN5Y1HoaLSpLU0MsGGAZg0DC6ugmlkgnY0gmlwhJ31RcCJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI,enr:-MC4QGsGQCaPfqCZ6IWIqxwvygLIC5XxM_ve9mMR2RAC2wRJegncAG9eJ7Lo6zJiTJXlrlTLTj9PIG2nZfIRR2S_PgkHh2F0dG5ldHOIAAAAGAAAAACDY2djBIRldGgykOG_GOFwkZMFAQAAAAAAAACCaWSCdjSCaXCEnfVFwINuZmSEuuYW7IlzZWNwMjU2azGhAmMU8wcXuBtyz8cm4Dv-YYPBQFNTnu8VAF_M0D7gxG9vg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --sync-light-client=false
              - --light-client-data-serve=false
              - --light-client-data-import-mode=none
              - --bootstrap-node=enr:-Iq4QFnW7-2NjL_VVFy0WaXOsOgVNqXQUlk6fj8H46AU9BeKe5blTKURg0oyQVwWxAilPCsT6ZtN5Y1HoaLSpLU0MsGGAZg0DC6ugmlkgnY0gmlwhJ31RcCJc2VjcDI1NmsxoQJtuukir45CAVRyhmqJKcRS2934t-LXmAxJ-k6iZONGlYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QGsGQCaPfqCZ6IWIqxwvygLIC5XxM_ve9mMR2RAC2wRJegncAG9eJ7Lo6zJiTJXlrlTLTj9PIG2nZfIRR2S_PgkHh2F0dG5ldHOIAAAAGAAAAACDY2djBIRldGgykOG_GOFwkZMFAQAAAAAAAACCaWSCdjSCaXCEnfVFwINuZmSEuuYW7IlzZWNwMjU2azGhAmMU8wcXuBtyz8cm4Dv-YYPBQFNTnu8VAF_M0D7gxG9vg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: fusaka-devnet-2-c3168b3
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31911
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: fusaka-devnet-ssl-7
      testnet: fusaka-devnet-ssl-7
      ethereum_network: fusaka-devnet-ssl-7
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/el/chainspec.json;
            GENESIS_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/el/genesis.json;
            BESU_GENESIS_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/el/besu.json;
            ENODES_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:fusaka-devnet-2-c3168b3
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: true
      addresses:
        fusaka-devnet-ssl-7: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.fusaka-devnet-ssl-7.yolkie.xyz
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/prysm-beacon-chain
      tag: fusaka-devnet-2-41eaa96
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32060
    podLabels:
      network: fusaka-devnet-ssl-7
      testnet: fusaka-devnet-ssl-7
      ethereum_network: fusaka-devnet-ssl-7
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.fusaka-devnet-ssl-7.yolkie.xyz/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.fusaka-devnet-ssl-7.yolkie.xyz/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
