secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:irymlzgNQsaJRqT7he0Dr7O+f06eEiYL/o7e+ybiW9t54InzF58=,iv:m6HEW0ov+Rlo2rw+y4NWps7PcuO0X4p2TAGqSjx43TQ=,tag:hOqeVeeduqCiPuKAdscI9Q==,type:str]
    username: ENC[AES256_GCM,data:Dl8RF2o2,iv:qpHtH4f+6nVJ/nwz4mmNgs3/5n0LcBaUMDoa7bvuRVs=,tag:p146MbxVvXzU6S/ut1nSKQ==,type:str]
    password: ENC[AES256_GCM,data:fEcYCZcwgbKqMcAK,iv:EGGkzzvWvwLqyscA0wvcXNnoPZQ4sAsO1ViGb9eUyOY=,tag:ptpNjZZ58s+e+Mc1DOt1fA==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:pHg38LkELKhcK7YPYkfR6GyNCr1g0/d92Q==,iv:J3wkYD5vEV3VifQP9ZUoGoPNhOn9B//zlGfwz16AH6w=,tag:p2OVflkgmBrryMyeMWO5uA==,type:str]
    username: ENC[AES256_GCM,data:Ervnu/1j,iv:qCkw6f3Dj16OwlSVK7I05s1leFd0DUnfsXka9PaI2x4=,tag:tAK8K3U6jZNNVOiLD7ZS7A==,type:str]
    password: ENC[AES256_GCM,data:9a4gvkNzacIod31E,iv:FXe3jlX2n9VHbzAizK1an0kZ2p+ZS1itsBkcJnpRYW8=,tag:+AAsJIppBR1h9xT6ajOSIA==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:NTNGmG8Y95CZYcBrpVZ5JXF5vjYB1MqglxUzdJAiwx6pIZIVeVrZi5GBVwAYko9aPc6XO2gS+bcLyoKZ2CjBaA==,iv:lwNvUY2lWSMRKuQEeld87vz9l/HLL41ZKz0oxRCke5c=,tag:Ydnr2eExgNdJqjskcgB/hQ==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:cbGBgON8AKd93rSr1qBjbR5znPpQVw==,iv:4rxo5LK5JfRiAotROVsg/w7oDDrf5L+iD4y6HG3ca78=,tag:ElAGKpDFgojhMOpqeXVdnQ==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:cr7uwpwWQ3/yUsUaTlx3fk7aXeEZvupJy/vELMzueclWFZW5fYN6z6CUUn/BIrgkzvGtJVy69Dd8pV9Cv9yyfMka5tHtmFpNKhxHB3La8rlaCdJnFfY=,iv:0XNGrrcWzxt6HOHqp7jfZ8mc8T44/Zm5qYDHdy8H4ro=,tag:jmT75nFsCvQy0TBY+qgdzw==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:6PjTScvSywHi,iv:G9AAah0LFW4/AtTj6B3bmjFQ1B24Av+66vF20AQMzLQ=,tag:6+O1Un/qM5/Gjq+ts0FSAg==,type:str]
    password: ENC[AES256_GCM,data:reO28jwZPDqKe9EN,iv:3YRDXDIZWmt0rFTTqFiEjaAWC9ZkMogiNYplDMnsnX0=,tag:MjqOa13Wv85vjgF4iweEdw==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:sOdkfbnRRVZM,iv:4RSMNkiRZhAxfF8+TymZ39FgqwYkWFwSWpzwxCgBVDU=,tag:TbBtujW0ddzEBuHRQwF4+w==,type:str]
    password: ENC[AES256_GCM,data:p9NnXc1YZY/YfjFd,iv:TlgHiuAjDnV6VcZI8OQlBTKXPnxRz10btpCsGqfQHHU=,tag:IbpfhcRVShSMBCSYSEhr8A==,type:str]
    server_address: ENC[AES256_GCM,data:kktQtESF92AgS6qqIhkiRx0a,iv:/yww5jtlcGruY2H7vd07SsAt7RBAiu4h8WV1XKv1N+E=,tag:al9xv8oR5T9sFu9cenuUlQ==,type:str]
secret_ethstats: ENC[AES256_GCM,data:KcZWy+/+JYwtlFmoH3dnzS7b+VvLSbFWNl6+e7LCtZJlJ36/8IE2ckQjmkoKv1WBvLvAaHCI9kPq//gOBDhFnQ==,iv:q5F5hv1KEp6K5MOmBroI/04aKtII621bSM1Va7mkHFc=,tag:yvql6uXwgiKnrvrUsuzI+g==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:pPX4uW4jMBmXhycUdQf6iun5/esyu4G6LtygPxZ/0sMhZZUoMLqp5sJ31odyGgMVUm5OW36KE2lTk6//ibSLKtNW2UCKArTRC5Hx/HNEOgVMjNExYONnY6H8olpmwhG4LurrEU19Tgehw//0FgcpoTetejRi8PPkv6U5HCKhaOCcjziqrmAh+YzYPBvMCDpcJgBG,iv:343ZH9Sf3HRuHncj2XLxhh/7bxx89JwA5EiF+4n3CAo=,tag:4zr/uAuX3Eipn21HIss9Eg==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:QiegQOKI0iy56QCPP2GN30uqxRsLKZA8W6MPT2MMWVzPu0FQn9pRuirbAZ0L8XMuTbuJR2BNTjRdnPJqXbMX3kG00J3vUr28To+WVAkzJ2MymGA3c+9RW6TLL/sScJ45blSm44IiWnBnuMmOwNcxWYDp8/nR0H+9OlY0BNzPmwy2RoDfRJPpeIHnfGcGBHHG6rc9B4w=,iv:8oSDMiy94AahONdcneDDRsUm8nbjJvAsAW723FlqwiE=,tag:Mq+Py77ngRZJ1gyI4E7n3Q==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:+JznYHThSyGXHx5zRaVSsNXKAx9sbgJRDXmUN+koeCO4uhYI9fUyUcUMjtElocCj/qyyHWnCcSfSexdhmcmsoQ==,iv:4+XcMQY4fIedTH/+hgaLzwt6X6bK/l40ZozpgbPSwG8=,tag:QZaUtDH5BTLPk+L2xbuqkQ==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:Vcgv5kCmb4y3SgFPZBs7eWqI8SUyBuWLZRwTZ3OjRLnRJmbSYElgFCZkPaCW+shOKavu54gDAjn8EdE6MqIMjQ==,iv:i42mMkQJWGnNmUbMXY6WZfeL54mfv5iv2Eo9Sv4YQ6Q=,tag:aNs7fhydb2KokjEUJQDWzg==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:y1145yRPhWCNiInv7tL3/5HVkI4SNwPhQXAnNwlBsMiCk6TTUtLif7qHZGxUprDgb1N+XbUAPgXNrfbuYL+KVpIw,iv:6Ha7SZf6ObztlBl3rJ9d8Eg9PQOs/Qi1YLHog6Ib8Oo=,tag:N5ftdB2bA+2pTewyNvoI1Q==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:+OuHKqWqLPmA2Uj12rzNF4v7w5TAHNT7wlc6CDrg54Oj76fGUOnVdcWm9OiwCnHuhv3xE5O58xkNrZQB7Q6SdYRk,iv:Xb4pm8PGMgCGFAA4vnMdmm8g5z7apkAm7V4SBlEgSXU=,tag:fLch52ZZJcLl01PCOmZXSg==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:wkM/Sp7cZZKs,iv:bmL601wjOhwB3W3xSPJUMiPT5oTNeZHG/1btkq+57Ac=,tag:FzojNVkUejcyOmseOaGG5A==,type:str]
goomy_private_key: ENC[AES256_GCM,data:75RBkH+eFdiByMpYOIdmtJ/RNWNIMCxKE2tMx7+gzHEf4KGSauCOEDfBI9DbNJ5z3ndsEXvdQuLPT8JwCXC5xw==,iv:TT6XeichfCfr6TB0jqlW409o5nBxFnPxgMfyh6XPHD0=,tag:lwRU7h0JCBnOOLc5IFCo+w==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:z2viZ7SuW4r1qqhI7/WbYCV1QI3eOi1fm7pPbqLPiUDMys404E3QsJpdhbFcBrselRS5bjoU0tKM6ZM9PazFHQ==,iv:uDW033Ig8KjXk0VXDnoAZ4AW2X+tGlnpdqJ9E22+R6Y=,tag:qDkzIpbBdKpkS0/vQC90jw==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:BjmiCy7YDGly,iv:+8lxtdVn4qczSKAwCwylJxysVQmm0jjvOWfsCwO4NTU=,tag:3b5a5bqucpw3uN7FmGQN8w==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:HsvsbX5i7Y4e+0Hn,iv:z9Bk769jYeBcbMAXdNyn+SMA1IJjwH39qe5MwWNuEXM=,tag:8OZqH/9g2YUtcKhR0wVXiA==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:ZGha4OtpHXJFaUmMvLz7ZHGY+Zzrw9lkrUDAJwn46yVjP0Qj+yyVUf7aXwmcFhRGOqS9JGDIw4BR9B98gueGFg==,iv:lLFcNQBOHjXjFsLGSdsmQYidcdeAxB74BJP4cIQQu34=,tag:Ss1vD6jF/xfLmh+MudOR2g==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:o3X1XoEnsDRhqNul,iv:nnPIo3JRkWG46T8oycc1SU/D/A/fKEW+aDm5gPI37OQ=,tag:Il8MAlWsNzSPTgmTB7iiLg==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:zDTyfDH2O/eI,iv:UBXNBqSsxudl4oNXpDW6QxvzhWTSoBT6AjprgvyJLa8=,tag:it7X8EALb1mGd5ohFTI4wQ==,type:str]
sops:
    lastmodified: "2025-11-05T13:00:55Z"
    mac: ENC[AES256_GCM,data:tLE4hwBPoqup5mseBUwj5xXYlTd9Vpj8238xFJ9eH3KrEGomFjyiBrPcfuNGEqAkuWe8opOyTMtxalyLLuK1w+gw7PPq3/3B4aMJ1QkdYgO+fzOHkMyDRqiMt8+DjYqzTK10Sssdy/LLDubb7/c7YDzD1yVxh+/ehHFX/y0EcFs=,iv:QMUwNbo6NUzQoCTw9lzNWhGtW2RVnYXkcX9TRtk2FoY=,tag:q/zB0wkR3TC4ajwDiHl6OQ==,type:str]
    pgp:
        - created_at: "2025-11-05T13:00:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQARAAnIp/WAPb1GZglfEhTrZ1wPYbXJOUN+1DBvDBDJ8mtlHC
            8JWL3HmXRNBT+QDv5tIvOoOTm4ZWCCiYj1VQXm/gkEjrHWwccLO9qc13sm5UNtUl
            4sY080ulcIHvC3rReOYjjeYqpEo1M8PaOjcC3vF9a7Zy9fRafurExAOQyrJtTzjY
            gaufFqPtN0PFGMOMj2ct6ae9q/9VsXgfSlgWOOw8R7ZhQYfEjt3eWip2eKuAz3ma
            U0N/t9nThbE2ryF0U6gKo/plFvRk2f09NWWlaP7wLgj4aXZyo/uyB+asx/pkFCVH
            0gm1f3MtRNYE03klw6jFd3WINv5OMxQBaTSB2LLXfdwHu2CwXCeSOSdNn59EbD+F
            M0ubo/KCyffp8cQLnmvEnj2UCtUX7RicfB7RC9bGmitFFnSdEFfqgpWetxoP0G7U
            EoRxtxkFk7qYfkGFRIw2d43uidUgQrkU42r52rXQxwXSn4NJfjU9kGV8ryv7Fy20
            rNo3uHoGwrH6Cvf5mCpMZZ/bbJJBsyVIKy1YJF7kp6DY0+1jKpzt2X882tdXP60C
            QRemMMPlu+VBN7mmDlBTRLv6DiL4Mp2Pc8TySXWsrSCsWpWOl+4i9b/rh0jErrXE
            hNwLNPUSSxsfl7G74wpgrqtN5HJ3Co66hyE5vOyNAf8FNQ/4WkKI6T71OzOattLU
            aAEJAhCwtz6jWMwf5uFFuksodiK7lC2ou3M6TQSDjvpupwDKNp5eLF6M18Raaofi
            tqU1Lx87IMncAF9JQrJzqzSqaZ++ExALG6J9yH0SCsQ5OUwB24NftHjH/ii3jsZA
            mairaSroXrbs
            =txoE
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
