# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forkmon.yaml.j2

forkmon:
  fullnameOverride: forkmon
  image:
    repository: docker.ethquokkaops.io/dh/skylenet/nodemonitor
    tag: darkmode
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: forkmon.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix
  network: fusaka-devnet-ssl-lighthouse-7
  endpoints:
  # Rpc
  - addr: http://geth-prysm-001:8545
    name: rpc-prysm-geth-001
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: bootnode-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-10.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-10
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-11.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-11
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-12.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-12
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-13.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-13
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-14.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-14
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-15.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-15
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-16.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-16
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-17.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-17
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-18.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-18
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-19.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-19
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-2.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-20.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-20
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-21.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-21
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-22.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-22
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-23.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-23
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-24.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-24
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-25.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-25
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-26.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-26
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-27.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-27
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-28.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-28
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-29.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-29
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-3.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-3
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-30.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-30
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-31.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-31
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-32.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-32
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-33.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-33
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-34.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-34
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-35.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-35
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-36.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-36
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-37.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-37
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-38.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-38
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-39.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-39
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-4.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-4
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-40.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-40
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-41.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-41
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-42.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-42
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-43.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-43
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-44.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-44
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-45.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-45
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-5.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-5
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-6.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-6
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-7.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-7
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-8.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-8
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-full-9.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-full-9
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-super-1.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-super-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-super-2.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-super-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-super-3.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-super-3
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-super-4.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-super-4
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-super-5.fusaka-devnet-ssl-lighthouse-7.yolkie.xyz
    name: lighthouse-geth-super-5

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url  = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = "rpc"
    {{- end }}
