spamoor_container_image: "docker.ethquokkaops.io/dh/ethpandaops/spamoor:master-b212f53"

spamoor_container_command: |
  blobs
  {% for host in groups['execution_node'] %}
  -h=https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.{{ host }}.{{ network_subdomain }}
  {% endfor %}
  -p={{ tx_fuzz_txs_privkey }}
  -t=14
  --blob-v1-percent=100
  --fulu-activation=0
  --throughput-increment-interval=300
  #--max-pending=1000000
  #--count=1000000
