secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:vgPSpz3EaQEVegh161aXjPqZHTm7eAZVGgOFmvAgdxTJ2vc/u8k=,iv:N1ZgdhezYnSB4y7Sj52FPsC4dyi0vAq2VxtgHQCStfc=,tag:CqJkIjWkwUZyunE+WWb44Q==,type:str]
    username: ENC[AES256_GCM,data:1tPLRBTo,iv:e6qwem7nHYhpw2cdJWPEuXJGdkmPd19n3BXy8wZkrVU=,tag:XN0wseHsTiNXXBs+sTOsRg==,type:str]
    password: ENC[AES256_GCM,data:AeOcgG6k85kl0of1,iv:x7lyHQlLWnjd9WdpJ6zZ5pau8xnkULHYRYPYvojadww=,tag:nm/0XpF7AI9ZZ1ukEnlT7A==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:vmcRlUhlio+63v5VbJbkWFsbREvWMHZFog==,iv:HmFTeveFhKW8jqxOoSpG7KhN9w5I8gKqYIfpd/qoh54=,tag:pprbiCObW21EfvsuPC/+Ag==,type:str]
    username: ENC[AES256_GCM,data:8iEAADVJ,iv:bSeLfrkNwLIaOiaugWDRDgclQjkKH7vhBnRHkKDVcJY=,tag:36bKvrzdYsRnZ+pL9v5y8w==,type:str]
    password: ENC[AES256_GCM,data:l93eYspZfjwwcY2b,iv:W8kEHk39070VV3oJgPPX+4M1z8d/BioFMguPqimM0Z4=,tag:MfXaz9O5gx3zxUc30feYBQ==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:m/c8gcgpHdCF/YHSyLdphk1YmFH079PyJRE2U7VZ1n22SgyjmkeWF0lB07gSztsZ+2JWTicuTBcOKWATSPi3GA==,iv:MxC/2KqZVOvrq7elyrOpxf1b3HeOFL49XpiSRqVdAro=,tag:KRkAzgzENVLk35xBsgfK1w==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:J8f7UZiC+5e1WKdutgFOxpF7PtRSSA==,iv:X4avZl3pI4mXDYa0d9vqKX6VtLRHI4vIulfzSVCvg2w=,tag:bYU+07QaE7Oc3DSg2CHbsg==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:X1RkTARIQwJ4COA0oRe0gfsYtxGpent49GQ5DLgoa74zfox3qyMKC7BhO9bmp/mDmDtL3++2Z+f+RkMT+wJDmH1jNonRiuY4UzaSdiB+4Hx2QoM3Ops=,iv:19FXuXxzpvKkVJ9DBL5ChqWK+NfoBTExBaFAeUFJqUI=,tag:AoVN9PATw7C5j9eBwbY6Ew==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:cF8lrXEWpFAt,iv:46BvxS1vHfEv40nAHHp+eqbKcOXQpeAyeAXlkQHcKAU=,tag:TxsI//3ApRqzYuaWzOxwbQ==,type:str]
    password: ENC[AES256_GCM,data:JvqLRAV7fBIt6aZU,iv:aJseI3sZvtCyCgX9Di48LigMW85R7jkVipr7qbT7Jrs=,tag:5G/N4OVaj+1SR2UTn7qAlw==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:kRtdorcWa+me,iv:k00ooflCam+NLfDDvz3tz5m/rljl+LyiWR5x3zAMA1g=,tag:3I8is8yTdobwsRNA+jOVZA==,type:str]
    password: ENC[AES256_GCM,data:fIkX1Xnk3jKY58wS,iv:guiNO5HTH13XPrBqqCmNLViTMfc03knX+ggTQ4fmQso=,tag:lKzzQ/PI9gZ8Oj4GqNCdmw==,type:str]
    server_address: ENC[AES256_GCM,data:C0kMqNBHKKfYVqeRpa/S2Ntv,iv:xAJFJclUss6eGSkJQxIJW++O2QxwYLHnDIGSle8X3IQ=,tag:zyMoKFHhtQf5Y33+lfoHug==,type:str]
secret_ethstats: ENC[AES256_GCM,data:jbzYFuDVuVfD4kZp4neK7t1Vi5atNZVegMt1ASUp/0a52dVlW/7bfpTq6YNztmEXb0SBuzTH6CPAWny1blok8Q==,iv:F/346cGKX1wajBeEz05o/PyoGCKCS/5/jKgLm0m7Z4c=,tag:gTds52LSe0czZiMGUTDZVw==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:srd4Cy1cV2hvV78peg1tfmDwJblpnN29SpHPfcgowdICI9upJ1hDmGU6veD2D6a0Um+Ib1zkzlKRFdE8f3rZZbwo0fgtcdWGpdWWgmOoawgzbBJhqd9u0cCXQE3+DkeLW2gYBuDn+/6YetuyXsRI8Xl+bT8MTbHypVme5yXThSQqvsj9MKCurqiiRIX+wwcjspER,iv:FSAcJdu01/ODCGdsQxMOj0Xm1eydKiaLfC65p4lV1oE=,tag:PXVkNGcXYnXEI4lPEt9oWA==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:SH6tHJr8E/wgjZZxzpoov1PH1q48wJxtdy+7iQ+YYffvi3O5y+2bShYyLSctSGOx0wwbzUtzlJWyV5I47nbneEWBdDTgiyUG7ExJ2wghTsq5RUxS34yvUgCGjSgWU3ocXCasg7O8uQKI+ZW64A4wPEUrFSQctJ/cElLLuk0BAk3SeeB0AeShhUy1N2iwsE0jJUdyEVY=,iv:/L/HeDsEfGeHIjUNN45m0t5E1/xOxJ/jLN5hPbds6xQ=,tag:e7UTRLUbYXJ0ZkyX7BCbag==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:59kT6Eyt4X9voJtOuHaNbh/PNqP8gVDZNYc5M055NdB/nTh8hdQofOn4cEwhN4oe0MiD/FcU5hv/JBD2LxD+hQ==,iv:2/2znB8hQ/7/sGCD1kKI9kqSbo4vcCoB56s5qhqOr+4=,tag:+pCXcOwcGygHOCvxclctZw==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:BrmhUPbMbvqGQhpzw5geb2TL8RooWmhwJ9DUlBIsqA7tuP3ykydH855EZz8yMYqIRaHZz+WbQtS+fUBsB0Yg4w==,iv:OUuzjXuOWii+9wUshdFLJneKq0s4MSXuihY+XuQiCN4=,tag:elt3pqspv9aqWjbkvKxaTA==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:kZCeCDIRsSCwIZ8WaUNNuT+MiMXeMyrGh2nI1j52HO2ZSYmqR27OVIwj6akZUNuvbDg+E/ZV5KZ1JxDd+s61Ig==,iv:FWndcGcwGkSUKpfAxGn/Oon+UncmuOd9SfmRcPA5SpU=,tag:uDv+81zQv7kdGxRGYfsNqQ==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:TlUE0vgjk+zgvJoTzv3PA2GTRh2UiZRMpBRjK4owRDqPgiCpSISq4Y3aAtZPp5MeUuK6tT63nmkM8rueiToNmw==,iv:cu6lnKBVRaRxjVkxvu2WVJgDTqGVh88cp8pcAg2Vj+Y=,tag:aMHh5MNCXEV714KEtmmKLw==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:WJk29giuN7RK,iv:fvLD9DMQLiCI/6408C08oD8dmsj2Dd968ljx0K2yvZQ=,tag:Q+UX9DKv7RkNgNLQ2tSxWg==,type:str]
goomy_private_key: ENC[AES256_GCM,data:fpWn2dyozRHJ2qpBKoezRl0W2TcYhCYoj75f1e/dFRjGhymtRpn7hLfTfjlgQYaqAgDEQ0PgoFvYxrtw9vLSsQ==,iv:yqEcsQa/H6oqVOCxOeWiUQqVCgzel31rY2mq7sS3AbM=,tag:evnYkPB5Sec/HPQAFyFkVQ==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:GjnT/8MQbugd0pvlln7ZGnTdOWg0/Do/7h2y/YZfMzUhV/gJLxp41iODah2Y46sLqpDyophiyOvXEuf/dJvZNA==,iv:3ZK+LvImAnve+5shWk7mNE5YSVMYkasXREkkouESNSw=,tag:8/OUilkqD6TzD4xYHwzjzw==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:35GCRDzWn8SC,iv:0hHLQZRSS97AM3RosIee0OnHOfEKSZ+BGvt+pbGrw2w=,tag:voFW8e05YPY5ahtVdeJRzg==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:xFifiX29d3L9KehL,iv:kb2vA6AVlOWuczdBXilxxh2OuqBLwmeMVjjrgTMiq6Q=,tag:lCfkihfO+rEP2rmOG8GaDA==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:hNR6qFRwtaz9UPWYvx+EX7hEqaEGJGNtmqiANpTBmX+8XrkgGueEDS/zsktIfN2WmJf6YwYiysiRUblYdAmRPQ==,iv:9yALlkDtFuo+QwleORrFefFZc3OW/7DtoEJcuEeW2ts=,tag:ZrQYKT0Pxjj54SHG8ON9aA==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:o8f0GDlaoWixjz4f,iv:pFtF+SLf7FVjLC03WyLYLdGOJ/zNDalM6WDyrSkmOfM=,tag:5ZgI8GonUxCPiZO5oxOfCA==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:aS5AebVvqbLO,iv:YtFc2EuaOMca0XK9E5hXK/MusA8W0o2MmTmROAxuqr4=,tag:TWhHfJUM/pnuoiYFuv8x0A==,type:str]
sops:
    lastmodified: "2025-10-03T16:14:29Z"
    mac: ENC[AES256_GCM,data:oDDxav3Hpfkn63PxDiYZL5F5HJtrmpjj4eZvvwqOnQ5tiHPnr9wTUJ08uMdkfGIHH7/37tp6i0ogm2kfJdktE7pGjtc0EHL1ZiUgea9/mZc9h04udn8kSNY5FfgrcOhmv9TDhfzr/cSq9DjcGUlqNj/hOGBduyLu3O+dECvYkWE=,iv:lP7obqZrNsxEYFJJVzOTbr7oMUHUdDCkoYsnjTXd6Fs=,tag:x6hQUXkNOM3/XHAFwUSE8g==,type:str]
    pgp:
        - created_at: "2025-10-03T16:14:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQAQ//cVy7Z/kolWqsYgswPce8MPga3TR0Mhh+/2FS6ujdHPwA
            RmkVJ47GayG/LJ42mftCcKvcee2uqCLkzx/WtdT9N/Mzx/G8f4ARkwJumTMGTD+g
            kgL1eiSF7Oh0XWUcw45pLnkxJb/uV8Q208yyRnmsupxmYmX3s7ywEYYITzk4FTqW
            VUgtFKZajeDy4VXCxW+FdONnH6kLHiDD4VTEofYuzCE8eZ6PDq9tRy1YKWzySW1b
            ONrXVZsVoy6spmV+Gc6tpizoFMiRIymKhYoojQmssII7by4uA6YUXulg+KZHovD6
            tyAXWpVsnZiH2zxoWtGZ2XcEg5czFaEAcJRIfrpELnNFqhR59YIAeWNEJXpcBp+7
            gojPgDI6XyvGytTzR6TUHz9OqbKl3ZLy6rI6EZYa3Yl9waeasURl2ZL0gSR1CHcF
            dT3UewiUTOUqipg4vshfHxrdk2s66P7AQoaSzcHA3ZwXB6CZdmmG5ohaOoJTGOu5
            KxMCQEnf/i4rylTOTBoJ7htzIKqpNu3+maqGTzUxi5+RHq77UJeBxtEsUs4OEoEn
            zT43Z06weoXNX+aEAC+CQSOtYHWJO/yChPAbzIEzDznaHszemhXtkb1H0fzr0wYV
            iFW2oNfKFU7e6TuIkmZeavy8lcGi4HBuTysYMKAsp0I8HLIOgA00wSuw2WxqdF/U
            aAEJAhCXBtuIeTYRBv/CD5NiH8uTog5WImCWB6Z4fNuR761RP/FiFxnBlzNPMqX8
            PQBWKtx+jzK6UAWeDEooKkNEg+NRqy/XlGiWm7nQHUDwuIkFidoC7nGtvPj7Gz5M
            SqAKEAVnENx7
            =dDgq
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
