xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-devnet-ssl-part-msg-1-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-devnet-ssl-part-msg-1"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://bdd3f9157a44cc89646b8886f6e220ab43737da5b040ccaac5f92e659848d847bb71d400af24130bb8d2d595c625153d7d077510d7b5640cba063c074cf28ca3@209.38.109.57:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
