xatu-mimicry:
  enabled: true
  fullnameOverride: xatu-mimicry
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/xatu
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    name: "fusaka-devnet-ssl-part-msg-3-xatu-mimicry"
    captureDelay: 3m
    ntpServer: time.google.com
    ethereum:
      overrideNetworkName: "fusaka-devnet-ssl-part-msg-3"
    coordinator:
      type: static
      config:
        retryInterval: 60s
        nodeRecords:
          - enode://7dbd33f92b2d6816a5a597c45545996cef1e9ace2f2f2582b7bc49683b829ce6f233718d51d45a046c69d9667659af394c7a14b0ebaa00261405420f778530e6@174.138.5.207:30303?discport=30303
    outputs:
    - name: grpc
      type: xatu
      config:
        address: server.xatu-experimental.ethpandaops.io:443
        maxQueueSize: 51200
        tls: true
        headers:
          authorization: "Basic <path:/secrets/services/services.enc.yaml#xatu | jsonPath {.experimental.event_ingester_auth}>"
        batchTimeout: 5s
        exportTimeout: 30s
        maxExportBatchSize: 512
