secret_prometheus_remote_write:
    endpoint: ENC[AES256_GCM,data:1wvtk4FihLfOgfH851swFK2iNihdVsWVrc2v2oBdTPh63XRneco=,iv:O1TXsO8eSFXEEascmrSfhWLcQZpzQzJPv7j44Pl6BAU=,tag:5gehksk7lrZDtKbMKW9n0A==,type:str]
    username: ENC[AES256_GCM,data:YfrPQLms,iv:ULSMpoSVsDL0Tx1tXe/aHZG5pPC/+/5IVLnfywdhJyE=,tag:KstY7YGf96vdrpjuDl3zzQ==,type:str]
    password: ENC[AES256_GCM,data:dJdSQ7BqG+0JqnLC,iv:oBaqpElfbCnd5iBwzb7oFROcjEJ3uYWngfYETMqAPSQ=,tag:z9dsaSDNo3FVOf+0Hti/Eg==,type:str]
secret_loki:
    endpoint: ENC[AES256_GCM,data:GGU76dg0fqmNSXPGDyEYhTIiN9eF1PIvFA==,iv:uxKcZJ7mLNDisZW/P4sRW4+KpClT0g+DPz1FOMRCk80=,tag:7zw7UJPS3nvUy1wsMe+U9g==,type:str]
    username: ENC[AES256_GCM,data:iGTlm6x7,iv:xeC1hXbzQnYXPSsH/hmJEJW2IZcsnoYU9C6CiDjz5rM=,tag:RgS4tfB70Sxz0R6B/kIaOA==,type:str]
    password: ENC[AES256_GCM,data:C7//E4VQeY5wh/k8,iv:N9Ad7YnGyDWAWdLqB+gl77NGAYcQNkm9omzrBID9ab4=,tag:K7vCOZ5aq/KQAHTRjVyJKw==,type:str]
cl_bootnode_privkey: ENC[AES256_GCM,data:JCpIgY8HZoEpPjpAKHFgprWh8KnpQWU9EKsvHSvPZlZVdYO8Li2HaF/D5LZ5INtHKipPPNVxebNr5PTuHl9mtw==,iv:t/6R1enbqJlP3Uub/5c4Wp4neaz5gBjLCa7+mG/DqF8=,tag:tErgAt9J9Asc/VSxodd7QA==,type:str]
secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:nZ4F08rNDura4oSH+aqG+xIm24Feyw==,iv:QJ1pmdqfT7pvGgrmVCUcop6ll7ZYUAKMJwvtsrgWJoE=,tag:dXm9kzoEkeJ498pk7VJ/EA==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:7CX6no+hQOCylQCC3mInfA05KdoQEE4SXuZ7ncRCTblbD2U0oNMvCW6Znby9Ti2kkSeN7pcxgr8TvGmYixFszzq6LHl+B6dFN+lenOeYq2JnN/GOFr8=,iv:tlikYF26UuY8jguN1nB2jSVUNtRgiPpbzrIC89DB+zI=,tag:ImTa6aP/kRAT0UbTpSba1A==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:tiuTVWyBCQ6A,iv:ck0YK68anxN6/wv3dWy5ZVRQCCFZ+1G/YqZFyZnvPbM=,tag:2Xly8WFIcZEmPQqOovEDjg==,type:str]
    password: ENC[AES256_GCM,data:xEPimOEKy+7NpI3+,iv:glyfKI6LSTqAhlEIIk8A7gjx4j2G4v3Nn3mKmxgv808=,tag:HTx8ifpEIn8AWhkco9A3nA==,type:str]
secret_xatu_sentry:
    user: ENC[AES256_GCM,data:ozspxduihYz7,iv:6ppd09rd5j8tySIBKsoq84Nl+hdJheF9Tw6IEUFHLkw=,tag:d7sGtQhPFyZ04uocMTZsaA==,type:str]
    password: ENC[AES256_GCM,data:ccGLghkOR84ZunLU,iv:rirN9e3uC5YTiDCaSyJ7ccpTZI2PXk/ZzgZ8210phSw=,tag:NTh2Fy+IiuPHNZRU1KseGQ==,type:str]
    server_address: ENC[AES256_GCM,data:C2rUngtkPtH6vtG3ujfzJmvx,iv:vz7iwv5fWaxVr2Nv8nEXDc7sv65O8u4B5y9HcncrRUM=,tag:7ZriNhlGfsN+CJu3a7T7yg==,type:str]
secret_ethstats: ENC[AES256_GCM,data:dnYH8rrI+KXsHiEOj0GJrlVp0Tx0fUbrjnKX/UdrtkkxiRZ3Upjezc7I9nBPExdWMgqK+19lHwk9hz4nxW6oiw==,iv:+lawVfoxLeFpMmyLYsFp/kSp97yhalp8Ogq60J/kjm8=,tag:XjO2QzfYPvpNTL2JwlVhuA==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:XljMjQ4p8tGYA/ZKX9cYdbg678a86G9sOVd6WNxYwYuPCazbrA1/05HNUecTIAHsXj9PN2iiQlxBVyYkIVx3yk+xLpEGl1pj0dN6w5rJcZ007rjZ0kvkqC+uABlrgu1w8GPUcLW9ajq3MPYiC59Umr+WKUBLhbSL93s8KSJK3QWmq6KJfK4J7+pcLaua/WZJ3HKQ,iv:B3ICI18XiH3rYHRAnJi9wh21bmm8bOn0xFxmL+n/itA=,tag:9saBpAmPfu4FNB1CIrhnOw==,type:str]
for_sharing_el_cl_mnemonic: ENC[AES256_GCM,data:8KF5Y45JOlUectVIcqL8gNZ7YZLQSQab/epH5XfcwELUHLJknYhj7lAsdIU9oYiXQFNuYdcqRdQUFlkNgI7k7CI3rYD1qlzPko6TTQ0zW0hwUoNrt+fNutO8tfYC6J6Zzg37mrJmyevYMK6q8FkyDOhRUC/rpJWdaL9YrLKWTmnWLf6Q43K+BBPzAIJKndnkz59mAps=,iv:5GitQ+aSvRmyc95G+dhOnd2B9kYeE98zigVC/mj32QM=,tag:KwmOylEU+34AFGMnAVe4GQ==,type:str]
tx_fuzz_blobs_privkey: ENC[AES256_GCM,data:qrIfszxcYRhzdQm7e40GyRJwVkEPy4+9oXn1k20rN4kxtCWYb9LQX0c2Xj1Hg+x8+3RrPUo5y1L8i1poV1VxSw==,iv:OrL8EeXvQhN8oj31WU+ditfWAsEJ+EiihiFVA94jGyw=,tag:oJMzGXBh7akKwB6TbQo/2A==,type:str]
tx_fuzz_txs_privkey: ENC[AES256_GCM,data:NCEkJqGm6lInvZ7HKea/M+RarQTxr/XBcErBxNyUT6psSJ5RbujVkCTF6Fn6olbWonfbjXVNEjK+nxWxqLYCAg==,iv:9WHJ3+8vNA5CWrPu18IajtQVXKYsHFiIiXcufdB87Sw=,tag:GSsMZ3pWXpY0pakMuDcCAg==,type:str]
secret_mev_signingkey: ENC[AES256_GCM,data:/ddUfAJJg44OiwfO8lzBNIbum5/nsZglzEYujD1Irx+x4Vcl05iAvT2q5Ca3KW0MA8b3A1nB+JdiXeQirJl6fg==,iv:5wEpz1NK8KrfSFN8JczZNHIUaKi5IMa8gR9hlJ7e+YQ=,tag:q5HMaPadohSQz+VlAr9rIw==,type:str]
secret_mev_flood_private_key: ENC[AES256_GCM,data:pB4FAJSYos2nMapsJ/PRwbxwRUu8nwUEn4A2hPK+IuSUWMcFORV5NLLknGVdJivgxT/05KcUMo3QhDp6KQE2yQ==,iv:LL9AQvqOHLCSOqTAdXXCn+pzmM/RodbQFbXqT8LxAoA=,tag:T0SmnPbVPtTtT5wD2+/FMA==,type:str]
secret_mev_flood_user_key: ENC[AES256_GCM,data:ziFOfMaFwXfM,iv:uZzVy0zVzrXjC2TnjztKXg/2RKp0HtmXF6T++kO7CZA=,tag:HI7dnN4DZSVQzApfPUJDJw==,type:str]
goomy_private_key: ENC[AES256_GCM,data:jzDXNwmax7IQW/ef3/osPqQkxmp/LDwbWze0giWkgr/8uHidjCKU2BUQU0nWbSEj4P6kubrRe+o3mtJQuCOr4A==,iv:cpgG+6Sd5udYJZ4UCWjVOVe5p4Azd4a+jAsYn+87Hv4=,tag:OhJhF3HwMO7xvZUFZD+6/Q==,type:str]
secret_xatu_coordinator_secret: ENC[AES256_GCM,data:j454nw8rhJqC92XHXXhtxSVx2SlfmSpCwuFrdqj+vr0nTAVXFl+v48m2+VBh2K8prtTg0EEYEsljHGrrGYtYDg==,iv:pfunw7K6Kyxx3pvk6cv9ikgK89A/0oLeYX1ThXx4y8Q=,tag:9N3ZaL35P1Vnl3BpQ3C9LA==,type:str]
secret_xatu_event_ingester_username: ENC[AES256_GCM,data:GiXJbS8mocMD,iv:2cIea9bLj72F7867N3Z8jn9AWDiRIki6Abc58gerqus=,tag:wXGIUwTbf86b9R0EzGDjlQ==,type:str]
secret_xatu_event_ingester_password: ENC[AES256_GCM,data:J92ivFNO3GA6Nxjs,iv:jLBscuje6vYzX7TegJX1fb/HGvghp5Xou85exW5LZNE=,tag:SLVdtbh4kIEjbwv+NMrp4g==,type:str]
secret_xatu_event_ingester_secret: ENC[AES256_GCM,data:NCdOqTqvAFvFbVRKEcfWJZE36FdJBF2esgRbf3tKgKGJyFM7Ai12sqhVUEp8WY4NBgp99vsuBSzNP4I6gImhwg==,iv:eiVsC6+q3yWJUJ36D47TaYOimuLpwWsRO5wqO2H0kL8=,tag:QZSs4f/MCDQMoXywJXS3Zg==,type:str]
secret_xatu_clickhouse_password: ENC[AES256_GCM,data:GOSbYtLRYPgfyGQX,iv:74hMsPdcNNnelz3yj971kdDjZXyYoHvVQzk7Fky1+CE=,tag:O2jSCbM8MeATXPt7IniuKA==,type:str]
secret_xatu_clickhouse_readonly_password: ENC[AES256_GCM,data:NFMVMqolsPVC,iv:VImQtNi9XOMgX2t34nEVnNq7EjZncDunyBpaaKLRysM=,tag:F1fRpbEu5fw+4DvgkyFpPg==,type:str]
sops:
    lastmodified: "2025-11-25T14:25:14Z"
    mac: ENC[AES256_GCM,data:ORK6z/L2dgHnXhmYbhPPnxV8IBEiWbStqBrqD9lFGUI4l4ZmmXVQi4HlVhMgH6w4RlIxOYNNvXqE0TWsfCzu5zJs6026OhUceE3jdF/a7hHrpZjDdxFstmQW30sb/S78s3f/aJwU6YQc8eiDQgHDsm3pZbL1iYUFrAz9KQ1THF8=,iv:v+Xeo1h2wmMtNgbDJivbjmkkafkS+qP+ZwWJ892s0wA=,tag:SR+RsS++eRRCwCIw0/kysg==,type:str]
    pgp:
        - created_at: "2025-11-25T14:25:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0o0g7KztylQARAA093Brika0POf4AJpBD0mMih4Gl0mRt3b3CRlBs09Ghnp
            yOEGHmjaxGcIVe0iU4jCzh3j+0aFtad0hu0+lPaDGwBUfeS1h1AMZGC2bjvl7noq
            Fc95c7chFhnHVEcXGyYXAKXk7Lxsj5s1xTwPb7U6vpIU6Yl62d7/gxzqErp3ZJW6
            PRkfiUw1FDC1iCX1sFm5sQ+aMwEn5sYHBYL2E76WHOYsMHJqdHgKvsLxZNdV0CX9
            cutfeI796LJu1eogxahIfVMai/iNWWtT2xJIsj2eemSbMRU6DKD85yp0kcoP3i87
            1NcoyVFBEKkXDsu/HsB49Sba+B7MpBiCHO6ngo3OKE07mf1SQH2X7p1vC+8k97nN
            eH2yH3/FBIe3zf3NWt6AR0jKe+hS9XfmFz+w12Ok2c0eh3pu7Ji+qw2zbU2q6Jdg
            aodLYmTMkx5qR0AprYnBaxH80O48ur7TDzQyciCtiUiZ34LrkWUWul4HbvveMR+2
            o/BslKsminKuXbcFMyH3eaAbymK4DR4Y/Wt05qapLu/IKcEO6PDpDB1l5gT0A7VY
            ZlwWSNkOW6dy9FshSuSFmkc76wrYtY9Vt/YZhTQmZtXDPh27yfQYEL6s91ZhxJMt
            7EZbHrjECNnFL8Gev47cd2pnxe1sAYRFnKORO/U3oUeCBUwtHMj4v+boHCHt6ATU
            aAEJAhAtHgRMkf4ZExuP9p/SO7lGbQWNqNx5zA7GM99v5THJYKrqwFyL8RG2BKrx
            l3HN9fywC8WLBE/9c9slG2FioGRxW3tl7xquU4tnp0sgoxDcueoOOhNmh/FtCNuZ
            +zKWL9MoErHs
            =m/1U
            -----END PGP MESSAGE-----
          fp: BD042542AC4246150FA0769DEA6772E43BA2EFF2
    unencrypted_suffix: _unencrypted
    version: 3.10.2
