# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/erpc.yaml.j2

erpc:
  fullnameOverride: erpc
  image:
    repository: docker.ethquokkaops.io/gh/erpc/erpc
    tag: 0.0.49
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: rpc.fusaka-devnet-ssl-prysm-3.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  config: |
    logLevel: info

    database:
      evmJsonRpcCache:
        connectors:
          - id: memory-cache
            driver: memory # Refer to "memory" driver docs below
            memory:
              maxItems: 100000
        policies:
          # Cache all methods with finalized data including empty responses
          - network: "*"
            method: "*"
            finality: finalized
            empty: allow
            connector: memory-cache
            ttl: 0
          # Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
          - network: "*"
            method: "*"
            finality: unfinalized
            empty: ignore
            connector: memory-cache
            ttl: 5s
          # Cache unknown finalization data (eth_trace*) only for 10 seconds
          - network: "*"
            method: "*"
            finality: unknown
            empty: ignore
            connector: memory-cache
            ttl: 10s
          # Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
          - network: "*"
            method: "*"
            finality: realtime
            empty: ignore
            connector: memory-cache
            ttl: 2s

    server:
      httpHostV4: "0.0.0.0"
      listenV6: true
      httpHostV6: "[::]"
      httpPort: 4000
      aliasing:
        rules:
          - matchDomain: "*"
            serveProject: "main"
            serveArchitecture: "evm"
            serveChain: "7032682551"

    metrics:
      enabled: true
      hostV4: "0.0.0.0"
      hostV6: "[::]"
      port: 4001

    projects:
      - id: main
        cors:
          allowedOrigins:
            - "https://*.ethpandaops.io"
          allowedMethods: 
            - "GET"
            - "POST"
            - "OPTIONS"
          allowedHeaders:
            - "Content-Type"
        upstreamDefaults:
          allowMethods:
            - "eth_blockNumber"
            - "eth_call"
            - "eth_chainId"
            - "eth_estimateGas"
            - "eth_feeHistory"
            - "eth_gasPrice"
            - "eth_getBalance"
            - "eth_getBlockByHash"
            - "eth_getBlockByNumber"
            - "eth_getBlockReceipts"
            - "eth_getBlockTransactionCountByHash"
            - "eth_getBlockTransactionCountByNumber"
            - "eth_getCode"
            - "eth_getFilterChanges"
            - "eth_getLogs"
            - "eth_getStorageAt"
            - "eth_getTransactionByBlockHashAndIndex"
            - "eth_getTransactionByBlockNumberAndIndex"
            - "eth_getTransactionByHash"
            - "eth_getTransactionCount"
            - "eth_getTransactionReceipt"
            - "eth_newBlockFilter"
            - "eth_newPendingTransactionFilter"
            - "eth_maxPriorityFeePerGas"
            - "eth_sendRawTransaction"
            - "eth_subscribe"
            - "eth_syncing"
            - "eth_uninstallFilter"
            - "eth_unsubscribe"
            - "net_listening"
            - "net_version"
            - "rpc_modules"
            - "web3_clientVersion"
            - "debug_getRawReceipts"
            - "debug_traceBlock"
            - "trace_transaction"
            - "trace_block"
        upstreams:
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-10.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-11.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-12.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-13.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-14.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-15.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-16.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-17.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-18.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-19.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-2.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-20.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-21.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-22.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-23.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-24.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-25.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-26.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-27.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-28.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-29.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-3.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-30.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-31.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-32.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-33.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-34.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-35.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-36.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-37.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-38.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-39.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-4.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-40.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-41.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-42.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-43.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-44.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-45.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-46.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-47.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-48.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-49.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-5.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-50.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-6.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-7.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-8.fusaka-devnet-ssl-prysm-3.yolkie.xyz
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.prysm-nethermind-9.fusaka-devnet-ssl-prysm-3.yolkie.xyz
