ethereum_cl_bootnodes:
  - enr:-Iq4QDwy3axkEQezLWREhz2sxegxkFIl6NvXt41QiNBYq8YjTTaMKDvWqXw8hjQCjGh6dElT3sjFhTJOrj9KMp6nuZuGAZh_-UMsgmlkgnY0gmlwhJ3mDFKJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
  - enr:-QEauEA68fUM6QKj-lznz4kazrOU9NVAaXs0kIgmCYqDt8zEV3zJZCSRkyt_iWf1re8kLpARrwZX9gHsO7EQmEF4I3ieFYdhdHRuZXRziAAAwAAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEneYMUoNpcDaQJgSogAQAANEAAAACnchwAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaECb_c3JStb4NWSVy-EGUtKwES6tJVZBNGDj7o5Z5aiboWIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauECrmEgVZXGe7KtBChQg7fa1G1bqV3-jnfdLSAh62uVskgSUnPNU77x7qdYFUDRJ_Mm7DUPOrjDMSMIqI0s9lMGuEodhdHRuZXRziAAAGAAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEpePOEINpcDaQJgSogAQAANEAAAACnckAAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEDNEmjpeuOeUF6g0zyY8CjJHWuURIxJqqJsguLWhAuViyIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauEASFSNYQlTMdRenMoTw-KdfYWhn2sDiqTR6AFSxWRjBSWObLJ_3Be5wP471P1dICvWn33BNCZ_GBJ558JyXHpL3FYdhdHRuZXRziGAAAAAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCERLcmc4NpcDaQKgOwwAABAOAAAAAAnMBAAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaECs6f3ZJlI277OgK0mkYBZ1S2yQ3IkAM-DNkIVKD-EXmuIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauECNDfLwPqkvDjQi5g5WW6aPxAtdZn5hfzHWSlz3BtZ0LR75MYjlRnoPylNLjJiaxy2nKLoFfbOw6op2i7tos3beEodhdHRuZXRziAAAAGAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEisUtM4NpcDaQJgSogAgAABQAAAABkUBgAINuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaED03YwUnQBFtN8mGHTobvc2zEKAWgTAQv5wli-NOFKPtyIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauEDLrCGS96-15KuzVftWXADxVkaojCJaqO2Twrx1-BwyPipN9KLl9zRdEFhKr2YvKqmQdGVvRmPT9oEeithsExjQEodhdHRuZXRziAAAAAAAAwAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCE0SZm7oNpcDaQKgOwwAACAPAAAAAA0N_gAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEDcL1rzrcJaWp751a8obQdmqniRtEZPLfiKBBhlW-oZ-eIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauECIrdy2Ti8WIK5BFkck3jK4u--GOI1X8blPFS9nFJ5d4Gia58okxWuog0upwgwy9-75hm-q2JtHhk_flVx3ncDUEodhdHRuZXRziAMAAAAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEneZ7FoNpcDaQKgOwwAADAPAAAAABJyfAAINuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaED0lKZv18Yhf4rnWXqSCbbqBFMCe4dic7QzmimfJBwl5KIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauECD1xkpVa7DXPBzHhhzyNOLdQUGEcPaQDs3OIvps4-JJF3icR8WCmRJ8O1Jhd9k98aimNi4X8Q2rgVv8NdynQGREodhdHRuZXRziAAAAAAAAAwAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEj8YjwYNpcDaQJgSogAytANAAAAAA5ntAAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEDaxtIGm7guiZChga81GcmL56xEK1yPykMXK_yxXmtGk6Ic3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauEDrqLgwC1ooJufk2Zd3mCCr06uyx_98-JcDFs07fix3ZTmbJvRcHM0pPIbKWtgieO3lrfpJcI_8cWbRqG4selXvFYdhdHRuZXRziAAAAAAABgAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEjl3S7YNpcDaQJABhgAEAANAAAAAApB0AAYNuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEC1kuIlytXTc_z3ykIiuok9TXjMekdFDfe2_LbhNtigDaIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauEC4rVdYwAl0-zQrwfcedATq_pQW3-sbAi-ybYTA0yipkxIbXccC4eZj7Pa73gwHSv3x167DDF48CeonEhhioCJRFYdhdHRuZXRziAAAMAAAAAAAg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEj8Y3mYNpcDaQJgSogAAEAdAAAAAA5JiAAINuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEDqyd5u-WkOtDjQlIrd8URq2OeFAoMF0b8lMQoTdofqN-Ic3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  - enr:-QEauEBTpgHZvbv5HnI6rCFPfjUQEKkiDOd771f_iSErG3sYRTZV4u6PNMARKYjPcMYj3mDSg84A-G-CZroGUEcZ08lOFYdhdHRuZXRziAAAAAAAAAADg2NnY4GAhmNsaWVudNGKTGlnaHRob3VzZYU3LjEuMIRldGgykGh_X5ZwEDgTAAEAAAAAAACCaWSCdjSCaXCEhseiLoNpcDaQJABhgAAQAgAAAAAAanHwAINuZmSEq91YxoRxdWljgiMphXF1aWM2giMpiXNlY3AyNTZrMaEDi0mOiIATrNUIRFN-HC6zT453IHDr_IWk5RqkSWZ5fLuIc3luY25ldHMAg3RjcIIjKIR0Y3A2giMog3VkcIIjKIR1ZHA2giMo
  

ethereum_el_bootnodes:
  - enode://3101192d325ecc038e7cb12d6b5aa9655d516954b9957df5b7c6c861dcebedc1e5d8e962f5d7e753e0766e2bae310e544c719732f956f88ab994e50d133e2cf1@157.230.12.82:30303?discport=30303
  - enode://150298264583ac10fd8ce3df4a2e2a09c3a5fdb04fe359facf7ac986d00b2d39bc421d95d7b0047375113524ccba97433a4efec71e93188d9f52f44ff9d896d7@165.227.206.16:30303?discport=30303
  - enode://09486ef98819d2a19ef150b8e7ec9116c21adea2ec1b46cd1b80d1d3099e23d4cb57bd635fd3cc6acd5f4a126af0f64272afd96ea2191d0686ea9ee4d93aa4f4@68.183.38.115:30303?discport=30303
  - enode://d8bb448db6634db5c849e55b3763f220f3762eddda29678341c2296b111774c597471a74a724cddb1de8e40023926774cca20e48e6eb055b5f19a06251358e48@138.197.45.51:30303?discport=30303
  - enode://869fc296e78ab3077158ccc46816aa575f43dc59fc75b265ff8e7936a7c99ad25877f08b54c51aedbce907a53a9929b4b004abef88e6929d9fb6eeb163844f14@209.38.102.238:30303?discport=30303
  - enode://c6a12c6920c23a63631958146f9f2332874e2d4146df519a0ac3190afbbcfd890a17d78d1f8aec354f165ea95ee5472186b734d2a33494223dd36c761a3ab3ec@157.230.123.22:30303?discport=30303
  - enode://44b0bb34da620d549d556c4fe17ee4d3452c445f9364161cb59067ec7d7e251bc75cb4eb9a5c8fea849e0bfbc947a72a3a8c44033d22b0cd1e727dfd6cf99387@143.198.35.193:30303?discport=30303
  - enode://98571a281cc01d0a8762fb98eb1a9100ea3fabb318243f92ee71164112541f9b0df77bcf1784e05cbe51a9a791675748a51ee94ce146f91ff87104ae9f93157e@142.93.210.237:30303?discport=30303
  - enode://1c7fc1f531d2aa0e40b19ddfc8a5c6d4e5df2eb77f5f42057c69c65b30c9024049d7b93294bbdd0d1a8884ced97dcac83a5e35549ac7037d361edf9422630370@143.198.55.153:30303?discport=30303
  - enode://38f7f9bfc57148b7970064480720230a664ccab48e604b8c5f8a7c8b76e0c62c19a7aea8b1e9c1f9853cee1496261dee5d84eb993d82a3f20aa86d59aab0097c@134.199.162.46:30303?discport=30303

# role: ethpandaops.general.docker_network
# disable ipv6
docker_network_ipam_config: []
docker_network_enable_ipv6: false
global_ipv6_enabled: false
ethereum_node_ipv6_enabled: false

# role: ethpandaops.general.prometheus
prometheus_remote_push_url: "{{ secret_prometheus_remote_write.endpoint }}"
prometheus_remote_write_username: "{{ secret_prometheus_remote_write.username }}"
prometheus_remote_write_password: "{{ secret_prometheus_remote_write.password }}"

prometheus_remote_ef_push_url: "{{ secret_prometheus_remote_write_ef.endpoint }}"
prometheus_remote_ef_write_username: "{{ secret_prometheus_remote_write_ef.username }}"
prometheus_remote_ef_write_password: "{{ secret_prometheus_remote_write_ef.password }}"

prometheus_config: |
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      origin: "sunnyside"
      instance: "{{ ethereum_network_name }}-ssl-{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      network: "{{ ethereum_network_name }}"
      testnet: "{{ ethereum_network_name }}"
      execution_client: "{{ ethereum_node_el }}"
      consensus_client: "{{ ethereum_node_cl }}"
      supernode: "{{ ethereum_node_cl_supernode_enabled | bool }}"
  remote_write:
    # - queue_config:
    #     batch_send_deadline: 5s
    #     max_backoff: 500ms
    #     max_samples_per_send: 500
    #     min_backoff: 50ms
    #     max_shards: 100
    #   url: {{ prometheus_remote_push_url }}
    #   remote_timeout: 10s
    #   headers:
    #     x-api-key: {{ prometheus_remote_write_password }}
    - url: {{ prometheus_remote_ef_push_url }}
      queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_ef_write_username }}
        password: {{ prometheus_remote_ef_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "ssl-{{ inventory_hostname }}"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "ssl-{{ inventory_hostname }}"
    - job_name: "exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["ethereum-metrics-exporter:9090"]
          labels:
            instance: "ssl-{{ inventory_hostname }}"
    - job_name: "consensus_node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["{{ vars[ethereum_node_cl + '_container_name'] }}:{{ ethereum_node_cl_ports_metrics }}"]
          labels:
            instance: "ssl-{{ inventory_hostname }}"
            supernode: "{{ ethereum_node_cl_supernode_enabled | bool }}"

# role: ethpandaops.general.xatu_sentry
# --limit lighthouse-geth-1,lighthouse-geth-3,lighthouse-geth-12,lighthouse-geth-28,lighthouse-geth-45,lighthouse-geth-63,lighthouse-geth-79,lighthouse-geth-84,lighthouse-geth-91,lighthouse-geth-106,lighthouse-geth-117,lighthouse-geth-123,lighthouse-geth-139,lighthouse-geth-146,lighthouse-geth-158,lighthouse-geth-169,lighthouse-geth-177,lighthouse-geth-182,lighthouse-geth-194,lighthouse-geth-201,lighthouse-geth-214,lighthouse-geth-219,lighthouse-geth-225,lighthouse-geth-227,lighthouse-geth-228,prysm-geth-1,prysm-geth-3,prysm-geth-8,prysm-geth-15,prysm-geth-19,prysm-geth-26,prysm-geth-41,prysm-geth-52,prysm-geth-64,prysm-geth-69,prysm-geth-74,prysm-geth-85,prysm-geth-88,prysm-geth-93,prysm-geth-98,prysm-geth-101,prysm-geth-112,prysm-geth-118,prysm-geth-129,prysm-geth-133,prysm-geth-144,prysm-geth-151,prysm-geth-156,prysm-geth-163,prysm-geth-166
ethereum_node_xatu_sentry_enabled: false
xatu_sentry_container_image: "{{ default_tooling_images.xatu_sentry }}"
xatu_sentry_config_name: "{{ ethereum_network_name }}-ssl-{{ inventory_hostname }}"
xatu_sentry_config_server_address: "{{ secret_xatu_sentry.server_address }}"
xatu_sentry_config_server_auth_user: "{{ secret_xatu_sentry.user }}"
xatu_sentry_config_server_auth_password: "{{ secret_xatu_sentry.password }}"

xatu_sentry_config_server_ef_address: "{{ secret_xatu_sentry_ef.server_address }}"
xatu_sentry_config_server_ef_auth_user: "{{ secret_xatu_sentry_ef.user }}"
xatu_sentry_config_server_ef_auth_password: "{{ secret_xatu_sentry_ef.password }}"

xatu_sentry_config_network_name_override: "{{ ethereum_network_name }}"
xatu_sentry_config: |
  logging: "info"
  metricsAddr: ":9090"
  name: "{{ xatu_sentry_config_name }}"
  ethereum:
    beaconNodeAddress: {{ xatu_sentry_config_beacon_uri }}
    overrideNetworkName: {{ xatu_sentry_config_network_name_override }}
    beaconSubscriptions:
    - attestation
    - block
    - block_gossip
    - chain_reorg
    - finalized_checkpoint
    - head
    - voluntary_exit
    - contribution_and_proof
    - blob_sidecar
    - data_column_sidecar
  attestationData:
    enabled: false
  beaconCommittees:
    enabled: false
  forkChoice:
    enabled: false
  outputs:
  - name: grpc-ef
    type: xatu
    config:
      address: {{ xatu_sentry_config_server_ef_address }}
      tls: false
      headers:
        authorization: "Basic {{ (xatu_sentry_config_server_ef_auth_user + ":" + xatu_sentry_config_server_ef_auth_password) | b64encode }}"
  # - name: grpc
  #   type: xatu
  #   config:
  #     address: {{ xatu_sentry_config_server_address }}
  #     tls: false
  #     headers:
  #       authorization: "Basic {{ (xatu_sentry_config_server_auth_user + ":" + xatu_sentry_config_server_auth_password) | b64encode }}"