localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-perf-peerdas-2

[bootnode]
bootnode-1 ansible_host=68.183.10.74 ipv6=2a03:b0c0:2:f0::e4eb:1 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False 

[prysm_geth]
prysm-geth-1 ansible_host=165.22.1.183 ipv6=2604:a880:400:d1:0:2:d7a3:a001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=0 validator_end=8 bandwidth=0
prysm-geth-10 ansible_host=164.92.76.17 ipv6=2604:a880:4:1d0::fca6:4000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0
prysm-geth-11 ansible_host=159.223.8.240 ipv6=2a03:b0c0:2:f0::e4eb:3001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=80 validator_end=88 bandwidth=0
prysm-geth-12 ansible_host=159.65.60.131 ipv6=2a03:b0c0:1:e0::af74:e001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0
prysm-geth-13 ansible_host=209.38.206.9 ipv6=2a03:b0c0:3:f0:0:1:4e7e:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=96 validator_end=104 bandwidth=0
prysm-geth-14 ansible_host=143.110.222.119 ipv6=2604:a880:cad:d0::fd78:9001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0
prysm-geth-15 ansible_host=157.245.110.163 ipv6=2400:6180:100:d0::ba57:b001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=112 validator_end=120 bandwidth=0
prysm-geth-16 ansible_host=170.64.152.144 ipv6=2400:6180:10:200::76a6:0 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=120 validator_end=128 bandwidth=0
prysm-geth-2 ansible_host=64.23.159.76 ipv6=2604:a880:4:1d0::fca6:3000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=8 validator_end=16 bandwidth=0
prysm-geth-3 ansible_host=157.245.69.247 ipv6=2a03:b0c0:2:f0::e4eb:1001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=16 validator_end=24 bandwidth=0
prysm-geth-4 ansible_host=138.68.187.71 ipv6=2a03:b0c0:1:e0::af74:f001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=24 validator_end=32 bandwidth=0
prysm-geth-5 ansible_host=209.38.217.50 ipv6=2a03:b0c0:3:f0:0:1:4e7f:3000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=32 validator_end=40 bandwidth=0
prysm-geth-6 ansible_host=143.198.34.61 ipv6=2604:a880:cad:d0::fd78:7001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=40 validator_end=48 bandwidth=0
prysm-geth-7 ansible_host=209.38.120.144 ipv6=2400:6180:100:d0::ba57:8001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=48 validator_end=56 bandwidth=0
prysm-geth-8 ansible_host=170.64.134.201 ipv6=2400:6180:10:200::76a6:a000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0
prysm-geth-9 ansible_host=134.209.212.85 ipv6=2604:a880:400:d1:0:2:d7a3:9001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=64 validator_end=72 bandwidth=0


# Consensus client groups

[lighthouse:children]
[lodestar:children]
[nimbus:children]
[teku:children]
[prysm:children]
prysm_geth
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
prysm_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]

# Global groups

[consensus_node:children]
prysm

[execution_node:children]
geth

[ethereum_node:children]
consensus_node
execution_node

[spamoor:children]
bootnode
