# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dugtrio.yaml.j2

dugtrio:
  fullnameOverride: dugtrio
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dugtrio
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: beacon.fusaka-devnet-ssl-chaos-6.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  dugtrioFrontendTitle: "Dugtrio: fusaka-devnet-ssl-chaos-6"
  dugtrioProxyCount: 2
  dugtrioProxyBlockedPaths:
    - "^/teku/v[0-9]+/admin/.*"

  endpoints:
  # Rpc
  - url: http://prysm-geth-001:5052
    name: rpc-prysm-geth-001
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-bootnode-1.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: bootnode-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-geth-1.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-geth-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-geth-2.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-geth-2
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-geth-3.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-geth-3
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-geth-4.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-geth-4
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-geth-5.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-geth-5
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-nethermind-1.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-nethermind-1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-nethermind-2.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-nethermind-2
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-nethermind-3.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-nethermind-3
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-nethermind-4.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-nethermind-4
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@bn-prysm-nethermind-5.srv.fusaka-devnet-ssl-chaos-6.yolkie.xyz
    name: prysm-nethermind-5
