- hosts: ethereum_node
  tasks:
    - name: Remove all bandwidth limits from the node
      tags: [remove_bandwidth]
      shell: |
        tc qdisc del dev eth0 root || true
        tc qdisc del dev eth0 ingress || true
        tc qdisc del dev ifb0 root || true
        echo "Bandwidth limits removed from $interface"