localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-lighthouse-7

[bootnode]
bootnode-1 ansible_host=161.35.144.9 ipv6=2a03:b0c0:2:f0::f685:a001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False bandwidth=0 

[lighthouse_geth_full]
lighthouse-geth-full-1 ansible_host=157.230.222.14 ipv6=2604:a880:400:d1:0:3:116a:7001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=40 validator_end=48 bandwidth=0
lighthouse-geth-full-10 ansible_host=64.23.230.16 ipv6=2604:a880:4:1d0:0:1:1f06:a000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=112 validator_end=120 bandwidth=0
lighthouse-geth-full-11 ansible_host=159.223.211.88 ipv6=2a03:b0c0:2:f0::f685:5001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=120 validator_end=128 bandwidth=0
lighthouse-geth-full-12 ansible_host=134.209.30.19 ipv6=2a03:b0c0:1:e0::bf03:6001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=128 validator_end=136 bandwidth=0
lighthouse-geth-full-13 ansible_host=161.35.223.74 ipv6=2a03:b0c0:3:f0:0:1:7478:1000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=136 validator_end=144 bandwidth=0
lighthouse-geth-full-14 ansible_host=143.198.35.6 ipv6=2604:a880:cad:d0:0:1:10ab:b001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=144 validator_end=152 bandwidth=0
lighthouse-geth-full-15 ansible_host=128.199.23.207 ipv6=2400:6180:100:d0::c67e:5001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=152 validator_end=160 bandwidth=0
lighthouse-geth-full-16 ansible_host=170.64.218.231 ipv6=2400:6180:10:200::7f3b:8000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=160 validator_end=168 bandwidth=0
lighthouse-geth-full-17 ansible_host=159.223.147.69 ipv6=2604:a880:400:d1:0:3:116a:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=168 validator_end=176 bandwidth=0
lighthouse-geth-full-18 ansible_host=64.23.163.158 ipv6=2604:a880:4:1d0:0:1:1f06:c000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=176 validator_end=184 bandwidth=0
lighthouse-geth-full-19 ansible_host=167.99.36.213 ipv6=2a03:b0c0:2:f0::f685:7001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=184 validator_end=192 bandwidth=0
lighthouse-geth-full-2 ansible_host=24.199.111.83 ipv6=2604:a880:4:1d0:0:1:1f06:b000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=48 validator_end=56 bandwidth=0
lighthouse-geth-full-20 ansible_host=144.126.203.44 ipv6=2a03:b0c0:1:e0::bf03:5001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=192 validator_end=200 bandwidth=0
lighthouse-geth-full-21 ansible_host=207.154.198.103 ipv6=2a03:b0c0:3:f0:0:1:7477:d000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=200 validator_end=208 bandwidth=0
lighthouse-geth-full-22 ansible_host=138.197.140.198 ipv6=2604:a880:cad:d0:0:1:10ab:f001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=208 validator_end=216 bandwidth=0
lighthouse-geth-full-23 ansible_host=143.110.249.72 ipv6=2400:6180:100:d0::c67e:b001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=216 validator_end=224 bandwidth=0
lighthouse-geth-full-24 ansible_host=209.38.21.128 ipv6=2400:6180:10:200::7f3b:c000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=224 validator_end=232 bandwidth=0
lighthouse-geth-full-25 ansible_host=159.223.174.59 ipv6=2604:a880:400:d1:0:3:116a:6001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=232 validator_end=240 bandwidth=0
lighthouse-geth-full-26 ansible_host=164.92.108.117 ipv6=2604:a880:4:1d0:0:1:1f06:d000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=240 validator_end=248 bandwidth=0
lighthouse-geth-full-27 ansible_host=209.38.103.169 ipv6=2a03:b0c0:2:f0::f685:8001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=248 validator_end=256 bandwidth=0
lighthouse-geth-full-28 ansible_host=165.22.122.166 ipv6=2a03:b0c0:1:e0::bf03:4001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=256 validator_end=264 bandwidth=0
lighthouse-geth-full-29 ansible_host=142.93.166.14 ipv6=2a03:b0c0:3:f0:0:1:7477:c000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=264 validator_end=272 bandwidth=0
lighthouse-geth-full-3 ansible_host=159.223.7.52 ipv6=2a03:b0c0:2:f0::f685:3001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0
lighthouse-geth-full-30 ansible_host=178.128.225.111 ipv6=2604:a880:cad:d0:0:1:10ab:d001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=272 validator_end=280 bandwidth=0
lighthouse-geth-full-31 ansible_host=134.209.157.3 ipv6=2400:6180:100:d0::c67e:7001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=280 validator_end=288 bandwidth=0
lighthouse-geth-full-32 ansible_host=134.199.175.168 ipv6=2400:6180:10:200::7f3b:9000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=288 validator_end=296 bandwidth=0
lighthouse-geth-full-33 ansible_host=192.241.139.10 ipv6=2604:a880:400:d1:0:3:116a:8001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=296 validator_end=304 bandwidth=0
lighthouse-geth-full-34 ansible_host=164.92.122.103 ipv6=2604:a880:4:1d0:0:1:1f06:7000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=304 validator_end=312 bandwidth=0
lighthouse-geth-full-35 ansible_host=161.35.82.16 ipv6=2a03:b0c0:2:f0::f685:b001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=312 validator_end=320 bandwidth=0
lighthouse-geth-full-36 ansible_host=144.126.227.139 ipv6=2a03:b0c0:1:e0::bf03:2001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=320 validator_end=328 bandwidth=0
lighthouse-geth-full-37 ansible_host=167.172.184.163 ipv6=2a03:b0c0:3:f0:0:1:7478:0 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=328 validator_end=336 bandwidth=0
lighthouse-geth-full-38 ansible_host=146.190.246.182 ipv6=2604:a880:cad:d0:0:1:10ab:c001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=336 validator_end=344 bandwidth=0
lighthouse-geth-full-39 ansible_host=64.227.148.195 ipv6=2400:6180:100:d0::c67e:8001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=344 validator_end=352 bandwidth=0
lighthouse-geth-full-4 ansible_host=134.209.189.67 ipv6=2a03:b0c0:1:e0::bf03:7001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=64 validator_end=72 bandwidth=0
lighthouse-geth-full-40 ansible_host=209.38.20.157 ipv6=2400:6180:10:200::7f3b:b000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=352 validator_end=360 bandwidth=0
lighthouse-geth-full-41 ansible_host=165.227.87.9 ipv6=2604:a880:400:d1:0:3:116b:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=360 validator_end=368 bandwidth=0
lighthouse-geth-full-42 ansible_host=146.190.115.224 ipv6=2604:a880:4:1d0:0:1:1f06:e000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=368 validator_end=376 bandwidth=0
lighthouse-geth-full-43 ansible_host=209.38.37.77 ipv6=2a03:b0c0:2:f0::f685:9001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=False validator_start=376 validator_end=384 bandwidth=0
lighthouse-geth-full-44 ansible_host=144.126.202.56 ipv6=2a03:b0c0:1:e0::bf03:3001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=384 validator_end=392 bandwidth=0
lighthouse-geth-full-45 ansible_host=139.59.154.170 ipv6=2a03:b0c0:3:f0:0:1:7477:e000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=392 validator_end=400 bandwidth=0
lighthouse-geth-full-5 ansible_host=104.248.130.121 ipv6=2a03:b0c0:3:f0:0:1:7477:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0
lighthouse-geth-full-6 ansible_host=147.182.156.189 ipv6=2604:a880:cad:d0:0:1:10ab:e001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=80 validator_end=88 bandwidth=0
lighthouse-geth-full-7 ansible_host=128.199.21.139 ipv6=2400:6180:100:d0::c67e:6001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0
lighthouse-geth-full-8 ansible_host=134.199.155.171 ipv6=2400:6180:10:200::7f3b:a000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=96 validator_end=104 bandwidth=0
lighthouse-geth-full-9 ansible_host=159.89.231.14 ipv6=2604:a880:400:d1:0:3:116a:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0

[lighthouse_geth_super]
lighthouse-geth-super-1 ansible_host=147.182.129.241 ipv6=2604:a880:400:d1:0:3:116b:7001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0
lighthouse-geth-super-2 ansible_host=143.110.238.196 ipv6=2604:a880:4:1d0:0:1:1f06:8000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=True validator_start=8 validator_end=16 bandwidth=0
lighthouse-geth-super-3 ansible_host=134.209.84.154 ipv6=2a03:b0c0:2:f0::f685:6001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=16 validator_end=24 bandwidth=0
lighthouse-geth-super-4 ansible_host=165.22.113.249 ipv6=2a03:b0c0:1:e0::bf03:8001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=True validator_start=24 validator_end=32 bandwidth=0
lighthouse-geth-super-5 ansible_host=64.226.96.206 ipv6=2a03:b0c0:3:f0:0:1:7477:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=32 validator_end=40 bandwidth=0


# Consensus client groups

[lighthouse:children]
lighthouse_geth_full
lighthouse_geth_super
[lodestar:children]
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
lighthouse_geth_full
lighthouse_geth_super
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]

# Global groups

[consensus_node:children]
lighthouse

[execution_node:children]
geth

[ethereum_node:children]
consensus_node
execution_node

[spamoor:children]
bootnode

[dns_server:children]
bootnode

[mev_boost:children]
consensus_node

[arm]
