# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  name: fusaka-devnet-ssl-perf-peerdas-4
  configPath: "https://config.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz/cl/config.yaml"
  validatorNamesInventory: "https://config.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz/api/v1/nodes/validator-ranges"
  ethExplorerLink: "https://explorer.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  publicRpcUrl: "https://rpc.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  rainbowkitProjectId: ""
  executionGenesisConfig: "https://config.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz/el/genesis.json"
  apiRequireAuth: False
  apiAuthSecret: "<path:/secrets/services/services.enc.yaml#dora | jsonPath {.api_secret}>"
  apiWhitelistedIPs: []
  apiDefaultRateLimit: 60
  apiDisableDefaultRateLimit: false
  proxyCount: 2
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: API_CORS_ORIGINS
      value: "*"
    - name: FRONTEND_ENABLE_DAS_GUARDIAN_MASS_SCAN
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"

  mevRelays:
    - index: 0
      name: "Flashbots"
      url: "http://mev-relay-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz:9062/"

  authGroups:
    pandaops:
      credentials:
        username: ""
        password: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>"

  endpoints:
  # Rpc
  - url: http://prysm-geth-001:5052
    name: rpc-prysm-geth-001
    authGroup: pandaops
    archive: true
    priority: 1
  - url: https://bn.bootnode-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: bootnode-1
    authGroup: pandaops
    priority: -1
  - url: https://bn.lighthouse-geth-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-1
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-10.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-10
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-11.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-11
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-12.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-12
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-13.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-13
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-14.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-14
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-15.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-15
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-16.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-16
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-2.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-2
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-3.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-3
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-4.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-4
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-5.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-5
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-6.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-6
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-7.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-7
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-8.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-8
    authGroup: pandaops
    priority: -1
    archive: true
  - url: https://bn.lighthouse-geth-9.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-9
    authGroup: pandaops
    priority: -1
    archive: true
  executionEndpoints:
  # Rpc
  - url: http://geth-prysm-001:8545
    name: rpc-prysm-geth-001
    authGroup: pandaops
    archive: true
    priority: 1
  - url: https://rpc.bootnode-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: bootnode-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-1
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-10.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-10
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-11.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-11
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-12.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-12
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-13.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-13
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-14.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-14
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-15.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-15
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-16.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-16
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-2.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-2
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-3.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-3
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-4.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-4
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-5.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-5
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-6.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-6
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-7.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-7
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-8.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-8
    authGroup: pandaops
    priority: -1
    archive: false
  - url: https://rpc.lighthouse-geth-9.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
    name: lighthouse-geth-9
    authGroup: pandaops
    priority: -1
    archive: false
