localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-chaos-6

[bootnode]
bootnode-1 ansible_host=104.248.198.10 ipv6=2a03:b0c0:2:f0::f108:1 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True 

[prysm_geth]
prysm-geth-1 ansible_host=64.227.6.51 ipv6=2604:a880:400:d1:0:2:feb6:c001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0
prysm-geth-2 ansible_host=143.198.56.117 ipv6=2604:a880:4:1d0:0:1:181e:5000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=True validator_start=8 validator_end=16 bandwidth=0
prysm-geth-3 ansible_host=178.62.208.115 ipv6=2a03:b0c0:2:f0::f108:1001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=16 validator_end=24 bandwidth=0
prysm-geth-4 ansible_host=178.62.53.180 ipv6=2a03:b0c0:1:e0::ba4b:e001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=True validator_start=24 validator_end=32 bandwidth=0
prysm-geth-5 ansible_host=164.90.189.34 ipv6=2a03:b0c0:3:f0:0:1:69c1:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=32 validator_end=40 bandwidth=0

[prysm_nethermind]
prysm-nethermind-1 ansible_host=167.99.232.15 ipv6=2604:a880:400:d1:0:2:feb6:e001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=40 validator_end=48 bandwidth=0
prysm-nethermind-2 ansible_host=143.198.236.146 ipv6=2604:a880:4:1d0:0:1:181e:4000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=True validator_start=48 validator_end=56 bandwidth=0
prysm-nethermind-3 ansible_host=178.128.241.250 ipv6=2a03:b0c0:2:f0::f108:2001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=56 validator_end=64 bandwidth=0
prysm-nethermind-4 ansible_host=178.62.109.222 ipv6=2a03:b0c0:1:e0::ba4b:f001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=True validator_start=64 validator_end=72 bandwidth=0
prysm-nethermind-5 ansible_host=209.38.239.23 ipv6=2a03:b0c0:3:f0:0:1:69c1:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=72 validator_end=80 bandwidth=0


# Consensus client groups

[lighthouse:children]
[lodestar:children]
[nimbus:children]
[teku:children]
[prysm:children]
prysm_geth
prysm_nethermind
[grandine:children]

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
prysm_geth
[nethermind:children]
prysm_nethermind
[erigon:children]
[reth:children]
[nimbusel:children]

# Global groups

[consensus_node:children]
prysm

[execution_node:children]
geth
nethermind

[ethereum_node:children]
consensus_node
execution_node

[chaosd:children]
ethereum_node
