# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/spamoor.yaml.j2

spamoor:
  fullnameOverride: spamoor
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/spamoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: spamoor.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz
        paths:
          - path: /
            pathType: Prefix

  customArgs:
    - --fulu-activation=1759769417

  persistence:
    enabled: true

  privateKey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.spamoor_private_key}>"
  rpcEndpoints:
  # Rpc
  - "http://geth-prysm-001:8545"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.bootnode-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-10.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-11.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-12.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-13.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-14.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-15.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-16.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-2.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-3.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-4.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-5.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-6.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-7.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-8.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
  - "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.none-devnets.node_ingress.combined}>@rpc.lighthouse-geth-9.fusaka-devnet-ssl-perf-peerdas-4.yolkie.xyz"
