localhost

[all:vars]
ethereum_network_name=fusaka-devnet-ssl-grandine-2

[bootnode]
bootnode-1 ansible_host=64.225.67.23 ipv6=2a03:b0c0:2:f0::bb9f:4001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True 

[grandine_geth]
grandine-geth-1 ansible_host=137.184.74.58 ipv6=2604:a880:400:d1:0:2:4c19:2001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=0 validator_end=8 bandwidth=0
grandine-geth-10 ansible_host=209.38.142.207 ipv6=2604:a880:4:1d0::cd7b:c000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=72 validator_end=80 bandwidth=0
grandine-geth-11 ansible_host=157.245.73.95 ipv6=2a03:b0c0:2:f0::bb9f:5001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=80 validator_end=88 bandwidth=0
grandine-geth-12 ansible_host=178.62.92.38 ipv6=2a03:b0c0:1:e0::8c62:7001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=88 validator_end=96 bandwidth=0
grandine-geth-13 ansible_host=46.101.107.44 ipv6=2a03:b0c0:3:f0:0:1:6ef:9000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=96 validator_end=104 bandwidth=0
grandine-geth-14 ansible_host=138.197.153.68 ipv6=2604:a880:cad:d0::d46e:e001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=104 validator_end=112 bandwidth=0
grandine-geth-15 ansible_host=64.227.191.138 ipv6=2400:6180:100:d0::941d:4001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=112 validator_end=120 bandwidth=0
grandine-geth-16 ansible_host=170.64.214.174 ipv6=2400:6180:10:200::5edb:7000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=120 validator_end=128 bandwidth=0
grandine-geth-17 ansible_host=198.199.71.44 ipv6=2604:a880:400:d1:0:2:4c18:f001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=128 validator_end=136 bandwidth=0
grandine-geth-18 ansible_host=64.23.134.192 ipv6=2604:a880:4:1d0::cd7b:a000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=136 validator_end=144 bandwidth=0
grandine-geth-19 ansible_host=206.189.6.160 ipv6=2a03:b0c0:2:f0::bb9f:2001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=144 validator_end=152 bandwidth=0
grandine-geth-2 ansible_host=134.199.219.9 ipv6=2604:a880:4:1d0::cd7b:e000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=8 validator_end=16 bandwidth=0
grandine-geth-20 ansible_host=165.227.234.153 ipv6=2a03:b0c0:1:e0::8c62:8001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=152 validator_end=160 bandwidth=0
grandine-geth-21 ansible_host=139.59.141.157 ipv6=2a03:b0c0:3:f0:0:1:6ef:5000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=160 validator_end=168 bandwidth=0
grandine-geth-22 ansible_host=137.184.165.215 ipv6=2604:a880:cad:d0::d46e:f001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=168 validator_end=176 bandwidth=0
grandine-geth-23 ansible_host=139.59.47.104 ipv6=2400:6180:100:d0::941c:d001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=176 validator_end=184 bandwidth=0
grandine-geth-24 ansible_host=170.64.230.243 ipv6=2400:6180:10:200::5edb:9000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=184 validator_end=192 bandwidth=0
grandine-geth-25 ansible_host=68.183.131.204 ipv6=2604:a880:400:d1:0:2:4c19:1 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=192 validator_end=200 bandwidth=0
grandine-geth-26 ansible_host=137.184.186.161 ipv6=2604:a880:4:1d0::cd7b:b000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=200 validator_end=208 bandwidth=0
grandine-geth-27 ansible_host=159.223.4.244 ipv6=2a03:b0c0:2:f0::bb9e:f001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=208 validator_end=216 bandwidth=0
grandine-geth-28 ansible_host=157.245.38.40 ipv6=2a03:b0c0:1:e0::8c62:9001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=216 validator_end=224 bandwidth=0
grandine-geth-29 ansible_host=64.226.102.228 ipv6=2a03:b0c0:3:f0:0:1:6ef:7000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=224 validator_end=232 bandwidth=0
grandine-geth-3 ansible_host=134.122.55.95 ipv6=2a03:b0c0:2:f0::bb9f:6001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=16 validator_end=24 bandwidth=0
grandine-geth-30 ansible_host=159.203.31.110 ipv6=2604:a880:cad:d0::d46e:d001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=232 validator_end=240 bandwidth=0
grandine-geth-31 ansible_host=64.227.173.38 ipv6=2400:6180:100:d0::941d:3001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=240 validator_end=248 bandwidth=0
grandine-geth-32 ansible_host=209.38.91.31 ipv6=2400:6180:10:200::5edb:b000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=248 validator_end=256 bandwidth=0
grandine-geth-33 ansible_host=192.241.156.66 ipv6=2604:a880:400:d1:0:2:4c18:d001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=256 validator_end=264 bandwidth=0
grandine-geth-34 ansible_host=165.232.130.25 ipv6=2604:a880:4:1d0::cd7b:9000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=264 validator_end=272 bandwidth=0
grandine-geth-35 ansible_host=134.209.89.205 ipv6=2a03:b0c0:2:f0::bb9f:1 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=272 validator_end=280 bandwidth=0
grandine-geth-36 ansible_host=161.35.173.209 ipv6=2a03:b0c0:1:e0::8c62:6001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=280 validator_end=288 bandwidth=0
grandine-geth-37 ansible_host=164.92.136.181 ipv6=2a03:b0c0:3:f0:0:1:6ef:6000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=288 validator_end=296 bandwidth=0
grandine-geth-38 ansible_host=143.198.37.176 ipv6=2604:a880:cad:d0::d46e:c001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=296 validator_end=304 bandwidth=0
grandine-geth-39 ansible_host=206.189.138.173 ipv6=2400:6180:100:d0::941d:2001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=304 validator_end=312 bandwidth=0
grandine-geth-4 ansible_host=165.227.231.109 ipv6=2a03:b0c0:1:e0::8c62:b001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=24 validator_end=32 bandwidth=0
grandine-geth-40 ansible_host=170.64.172.96 ipv6=2400:6180:10:200::5edb:6000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=312 validator_end=320 bandwidth=0
grandine-geth-41 ansible_host=68.183.27.73 ipv6=2604:a880:400:d1:0:2:4c19:3001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=320 validator_end=328 bandwidth=0
grandine-geth-42 ansible_host=159.223.204.175 ipv6=2604:a880:4:1d0::cd7b:f000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=328 validator_end=336 bandwidth=0
grandine-geth-43 ansible_host=188.166.62.92 ipv6=2a03:b0c0:2:f0::bb9f:1001 cloud=digitalocean cloud_region=ams3 ethereum_node_cl_supernode_enabled=True validator_start=336 validator_end=344 bandwidth=0
grandine-geth-44 ansible_host=138.68.170.230 ipv6=2a03:b0c0:1:e0::8c62:a001 cloud=digitalocean cloud_region=lon1 ethereum_node_cl_supernode_enabled=False validator_start=344 validator_end=352 bandwidth=0
grandine-geth-45 ansible_host=139.59.142.17 ipv6=2a03:b0c0:3:f0:0:1:6ef:8000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=352 validator_end=360 bandwidth=0
grandine-geth-46 ansible_host=68.183.199.207 ipv6=2604:a880:cad:d0::d46f:1 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=360 validator_end=368 bandwidth=0
grandine-geth-47 ansible_host=143.110.177.127 ipv6=2400:6180:100:d0::941d:1001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=368 validator_end=376 bandwidth=0
grandine-geth-48 ansible_host=170.64.137.227 ipv6=2400:6180:10:200::5edb:a000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=376 validator_end=384 bandwidth=0
grandine-geth-49 ansible_host=146.190.76.16 ipv6=2604:a880:400:d1:0:2:4c19:4001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=384 validator_end=392 bandwidth=0
grandine-geth-5 ansible_host=157.230.22.124 ipv6=2a03:b0c0:3:f0:0:1:6ef:a000 cloud=digitalocean cloud_region=fra1 ethereum_node_cl_supernode_enabled=True validator_start=32 validator_end=40 bandwidth=0
grandine-geth-50 ansible_host=24.199.126.209 ipv6=2604:a880:4:1d0::cd7b:d000 cloud=digitalocean cloud_region=sfo3 ethereum_node_cl_supernode_enabled=False validator_start=392 validator_end=400 bandwidth=0
grandine-geth-6 ansible_host=159.203.21.59 ipv6=2604:a880:cad:d0::d46e:a001 cloud=digitalocean cloud_region=tor1 ethereum_node_cl_supernode_enabled=False validator_start=40 validator_end=48 bandwidth=0
grandine-geth-7 ansible_host=64.227.143.226 ipv6=2400:6180:100:d0::941d:5001 cloud=digitalocean cloud_region=blr1 ethereum_node_cl_supernode_enabled=True validator_start=48 validator_end=56 bandwidth=0
grandine-geth-8 ansible_host=170.64.191.251 ipv6=2400:6180:10:200::5edb:8000 cloud=digitalocean cloud_region=syd1 ethereum_node_cl_supernode_enabled=False validator_start=56 validator_end=64 bandwidth=0
grandine-geth-9 ansible_host=147.182.140.232 ipv6=2604:a880:400:d1:0:2:4c19:1001 cloud=digitalocean cloud_region=nyc1 ethereum_node_cl_supernode_enabled=True validator_start=64 validator_end=72 bandwidth=0


# Consensus client groups

[lighthouse:children]
[lodestar:children]
[nimbus:children]
[teku:children]
[prysm:children]
[grandine:children]
grandine_geth

# Execution client groups

[besu:children]
[ethereumjs:children]
[geth:children]
grandine_geth
[nethermind:children]
[erigon:children]
[reth:children]
[nimbusel:children]

# Global groups

[consensus_node:children]
grandine

[execution_node:children]
geth

[ethereum_node:children]
consensus_node
execution_node

[spamoor:children]
bootnode
